const root=document.getElementById('rules'),message=document.getElementById('message');let rules=[],revision=0,stations={};
const label=(text,control)=>{const l=document.createElement('label');l.append(document.createTextNode(text),control);return l;};
function field(r,k,title,type='text'){const i=document.createElement('input');i.type=type;i.value=r[k]||'';i.oninput=()=>r[k]=i.value;return label(title,i);}
function station(r,k,title,optional=false){const s=document.createElement('select');if(optional)s.add(new Option('Geen',''));for(const [id,names] of Object.entries(stations))s.add(new Option(names[0],id));s.value=r[k]||'';s.onchange=()=>r[k]=s.value;return label(title,s);}
function render(){root.replaceChildren();for(const r of rules){const box=document.createElement('details'),summary=document.createElement('summary');summary.textContent=`${stations[r.station]?.[0]||r.station} · ${r.incoming} → ${r.outgoing}${r.enabled===false?' · Uitgeschakeld':''}`;box.append(summary);const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=r.enabled!==false;enabled.onchange=()=>r.enabled=enabled.checked;box.append(label('Monitoren',enabled),station(r,'station','Overstapstation'),field(r,'incoming','Aankomende trein'),field(r,'outgoing','Vertrekkende trein'),field(r,'fromDate','Vanaf datum (optioneel)','date'),field(r,'untilDate','Tot datum, exclusief (optioneel)','date'));
const more=document.createElement('details'),title=document.createElement('summary');title.textContent='Uitzonderingen en voorwaarden';more.append(title,field(r,'departureBefore','Vertrek vóór (optioneel)','time'),field(r,'departureAfter','Vertrek na (optioneel)','time'),station(r,'fallbackStation','Terugvalstation',true),field(r,'alternativeTrain','Andere vertrekkende trein als aansluiting niet lukt'),field(r,'origin','Verplichte herkomst (bijvoorbeeld wien hbf)'),field(r,'incomingCategory','Verplichte treinsoort (bijvoorbeeld ICE)'));
for(const [key,title,list] of [['alternativeArrival','Andere aankomende trein bij ontbreken','categories'],['alternativeDeparture','Andere vertrekkende trein bij ontbreken','destinations']]){const area=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=title;area.append(legend);const w=r[key]||{from:'',to:'',[list]:[]},check=document.createElement('input');check.type='checkbox';check.checked=!!r[key];check.onchange=()=>{if(check.checked)r[key]=w;else delete r[key];};area.append(label('Gebruiken',check),field(w,'from','Vanaf','time'),field(w,'to','Tot en met','time'));const input=document.createElement('input');input.value=w[list].join(', ');input.oninput=()=>w[list]=input.value.split(',').map(x=>x.trim()).filter(Boolean);area.append(label(list==='categories'?'Treinsoorten, met komma (RJ, RJX)':'Bestemmingen, met komma (basel, zurich)',input));more.append(area);}
const note=document.createElement('p');note.textContent='Vaste vervangers: 225 → 1255, 224 → 1254, 122 → 152, 124 → 154. Alleen als de oorspronkelijke trein planmatig ontbreekt.';more.append(note);box.append(more);root.append(box);}}
async function api(data){const r=await fetch('/stationschef/api/aansluitingen',{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const j=await r.json();if(!r.ok)throw Error(j.error);return j;}
document.getElementById('add').onclick=()=>{rules.push({id:'custom-'+crypto.randomUUID(),station:'mannheim',incoming:'',outgoing:'',enabled:true});render();root.lastChild.open=true;root.lastChild.scrollIntoView({block:'nearest'});};
document.getElementById('save').onclick=async e=>{e.target.disabled=true;message.textContent='Opslaan…';try{const result=await api({rules,revision});revision=result.revision;rules=result.rules;render();message.textContent='Opgeslagen. De monitor verwerkt dit binnen één minuut.';}catch(error){message.textContent=error.message;}finally{e.target.disabled=false;}};
try{const data=await api();({rules,revision,stations}=data);render();}catch(e){message.textContent=e.message;}
