import {createHash} from 'node:crypto';
import {connectionDate,normalized} from './connections-rules.mjs';
import {readConnections} from './connections-store.mjs';
let db;const queues=new Map();
export const dayReportStatus={startedAt:null,lastError:null,lastScreenSample:null};
const hash=value=>createHash('sha256').update(value).digest('hex');
async function query(sql,args=[]){if(db.pool)return (await db.pool.query(sql,args)).rows;const bound=[];return db.sqlite.prepare(sql.replace(/\$(\d+)/g,(_,n)=>{bound.push(args[Number(n)-1]);return '?';})).all(...bound);}
export async function initDayReports(connection){db=connection;const sql='CREATE TABLE IF NOT EXISTS day_reports(report_date TEXT PRIMARY KEY,revision INTEGER NOT NULL,payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS day_report_meta(id INTEGER PRIMARY KEY,started_at BIGINT NOT NULL)';if(db.pool)await db.pool.query(sql);else db.sqlite.exec(sql);await query('INSERT INTO day_report_meta VALUES(1,$1) ON CONFLICT(id) DO NOTHING RETURNING id',[Date.now()]);dayReportStatus.startedAt=Number((await query('SELECT started_at FROM day_report_meta WHERE id=1'))[0].started_at);}
export function normalizeReportEvent(t,source,observedAt){
 const planned=Number(t.plannedTimestamp),number=String(t.number||t.trainNumber||''),station=String(t.observedAt||t.station||''),mode=t.eventMode||t.mode||'';
 if(!number||!station||!Number.isFinite(planned)||planned<=0)return null;
 const valid=value=>Number.isFinite(Number(value))&&Number(value)>0?Number(value):null;
 const actual=valid(t.actualTimestamp),expected=valid(t.expectedTimestamp),category=String(t.category||''),origin=String(t.from||t.origin||''),destination=String(t.to||t.destination||'');
 const isPlan=/PLAN|GTFS/i.test(source),delay=actual||expected?Math.round(((actual||expected)-planned)/60000):Math.round(Number(t.delay)||0);
 const realtime=!isPlan&&(!!actual||t.hasRealtime===true||(delay!==0&&!!expected));
 const date=connectionDate(planned),identity=[t.serviceDate||date,category,number,normalized(origin),normalized(destination)];
 if(!origin||!destination)identity.push(source,String(t.sourceTripId||t.trainKey||''));
 return {run:hash(identity.join('|')),date,number,category,station,mode,origin,destination,source,observedAt:Number(observedAt),planned,expected,actual,delay,realtime,cancelled:!!t.cancelled,country:String(t.countryCode||'').toUpperCase()};
}
export function mergePeaks(old=[],incoming=[]){const groups=new Map();for(const e of [...old,...incoming]){if(!e.realtime||e.cancelled||e.delay<=0)continue;const key=e.source==='RFI'?hash([e.date,e.category,e.number,normalized(e.destination)].join('|')):e.run;const previous=groups.get(key);if(!previous||e.delay>previous.delay||(e.delay===previous.delay&&e.observedAt<previous.observedAt))groups.set(key,e);}return [...groups.values()].sort((a,b)=>b.delay-a.delay||a.observedAt-b.observedAt).slice(0,5);}
export function targetFor(e){
 if(e.number==='225'&&normalized(e.station)==='mannheim hbf'&&e.mode==='arrival')return '225-mannheim';
 if(e.number==='40421'&&normalized(e.station)==='wien hbf'&&e.mode==='arrival')return '40421-wien';
 if(e.number==='40490'&&(e.country==='NL'||['amsterdam centraal','utrecht centraal','arnhem centraal','amersfoort centraal','deventer'].includes(normalized(e.station))))return '40490-nl';
 return null;
}
function blank(date){return {date,peaks:[],screenPeaks:[],targets:{},sources:{},screenFirst:null,screenLast:null,updatedAt:null,backfill:null};}
async function update(date,mutate){const oldQueue=queues.get(date)||Promise.resolve();const next=oldQueue.catch(()=>{}).then(async()=>{for(let attempt=0;attempt<8;attempt++){const row=(await query('SELECT revision,payload FROM day_reports WHERE report_date=$1',[date]))[0],revision=Number(row?.revision||0),value=row?JSON.parse(row.payload):blank(date);mutate(value);const saved=await query('INSERT INTO day_reports(report_date,revision,payload) VALUES($1,$2,$3) ON CONFLICT(report_date) DO UPDATE SET revision=excluded.revision,payload=excluded.payload WHERE day_reports.revision=$4 RETURNING revision',[date,revision+1,JSON.stringify(value),revision]);if(saved.length)return;}throw Error('Dagverslag kon niet gelijktijdig worden bijgewerkt');});queues.set(date,next);try{await next;}finally{if(queues.get(date)===next)queues.delete(date);}}
export async function recordDayReportEvents(trains,source,observedAt=Date.now(),{screen=false,backfill=false}={}){
 if(!db)return;const groups=new Map();for(const t of trains){const e=normalizeReportEvent(t,source||t.source||'DB',t._reportObservedAt||observedAt);if(!e||(!e.realtime&&!targetFor(e)))continue;if(!groups.has(e.date))groups.set(e.date,[]);groups.get(e.date).push(e);}
 for(const [date,events] of groups)await update(date,report=>{
 if(screen){report.screenPeaks=mergePeaks(report.screenPeaks,events);report.screenFirst=Math.min(report.screenFirst||observedAt,observedAt);report.screenLast=Math.max(report.screenLast||0,observedAt);}
 else{report.peaks=mergePeaks(report.peaks,events);for(const e of events){const coverage=report.sources[e.source]||{first:e.observedAt,last:e.observedAt};coverage.first=Math.min(coverage.first,e.observedAt);coverage.last=Math.max(coverage.last,e.observedAt);report.sources[e.source]=coverage;const target=targetFor(e);if(!target)continue;const key=[target,normalized(e.station),e.mode].join('|'),previous=report.targets[key];const rank=x=>(x.actual?1000:0)+(x.realtime?100:0)+(x.source==='NDOV'?20:x.source==='DB'?10:0);if(!previous||rank(e)>rank(previous)||(rank(e)===rank(previous)&&e.observedAt>previous.observedAt))report.targets[key]={...e,target};}}
 report.updatedAt=Math.max(report.updatedAt||0,observedAt);if(backfill)report.backfill='Aanvulling uit nog beschikbare bronhistorie; kan onvolledig zijn.';
 });
}
export function reportDayBounds(date){let start=null,end=null;const base=Date.parse(date+'T00:00:00Z');for(let t=base-4*3600000;t<base+28*3600000;t+=3600000)if(connectionDate(t)===date){if(start===null)start=t;end=t+3600000;}return {start,end};}
export async function backfillDayReport(date){
 const {start,end}=reportDayBounds(date);
 // Only scalar columns: never bring raw train payloads into report memory.
 const fields='service_date,train_number,category,station_name,event_mode,source_id,observed_at,planned_timestamp,expected_timestamp,actual_timestamp,delay_minutes,cancelled,origin,destination,country_code';
 const peaks=await query(`SELECT ${fields} FROM (SELECT ${fields},ROW_NUMBER() OVER(PARTITION BY source_id,service_uid ORDER BY delay_minutes DESC,observed_at ASC) AS rn FROM event_observations WHERE service_date >= $3 AND service_date <= $4 AND planned_timestamp >= $1 AND planned_timestamp < $2 AND delay_minutes>0 AND cancelled=FALSE AND source_id NOT LIKE '%PLAN%') ranked WHERE rn=1 ORDER BY delay_minutes DESC LIMIT 100`,[start,end,connectionDate(start-3*86400000),date]);
 const targets=await query(`SELECT ${fields} FROM (SELECT ${fields},ROW_NUMBER() OVER(PARTITION BY source_id,train_number,station_name,event_mode ORDER BY observed_at DESC) AS rn FROM event_observations WHERE service_date >= $3 AND service_date <= $4 AND planned_timestamp >= $1 AND planned_timestamp < $2 AND ((train_number='40490' AND country_code='NL') OR (train_number='40421' AND station_name='Wien Hbf' AND event_mode='arrival') OR (train_number='225' AND station_name='Mannheim Hbf' AND event_mode='arrival'))) ranked WHERE rn=1 LIMIT 100`,[start,end,connectionDate(start-3*86400000),date]);
 const items=[...peaks,...targets].map(e=>({number:e.train_number,category:e.category,station:e.station_name,eventMode:e.event_mode,source:e.source_id,serviceDate:e.service_date,plannedTimestamp:Number(e.planned_timestamp),expectedTimestamp:Number(e.expected_timestamp)||null,actualTimestamp:Number(e.actual_timestamp)||null,delay:Number(e.delay_minutes),cancelled:!!e.cancelled,from:e.origin,to:e.destination,countryCode:e.country_code,_reportObservedAt:Number(e.observed_at)}));
 await recordDayReportEvents(items,null,Date.now(),{backfill:true});
}
export async function getDayReport(date){const row=(await query('SELECT payload FROM day_reports WHERE report_date=$1',[date]))[0];const report=row?JSON.parse(row.payload):blank(date),connections=await readConnections(date);return {...report,registrationStartedAt:dayReportStatus.startedAt,provisional:date>=connectionDate(Date.now()),connections:connections.filter(r=>r.status!=='not-planned'&&(r.eligible||r.lastKnown)).map(r=>({key:r.key,ruleId:r.ruleId,station:r.incoming?.stationName||r.station,incoming:r.incoming?.number||r.requestedIncoming,outgoing:r.outgoing?.number||r.requestedOutgoing,status:r.status,reason:r.reason,minutes:r.minutes,lastKnown:r.lastKnown||null,evaluatedAt:r.evaluatedAt})),system:dayReportStatus};}
export function startDayReports(screenProvider){let running=false;const tick=async()=>{if(running)return;running=true;try{const rows=screenProvider();await recordDayReportEvents(rows,null,Date.now(),{screen:true});dayReportStatus.lastScreenSample=Date.now();dayReportStatus.lastError=null;}catch(e){dayReportStatus.lastError=e.message;console.error('Dagverslagen:',e.message);}finally{running=false;}};const timer=setInterval(()=>void tick(),60000);timer.unref();const startup=setTimeout(async()=>{try{for(const offset of [-2,-1,0])await backfillDayReport(connectionDate(Date.now()+offset*86400000));}catch(e){dayReportStatus.historyError=e.message;console.error('Dagverslag historie:',e.message);}await tick();},15000);startup.unref();}
export async function handleDayReports(req,res,url){if(url.pathname!=='/api/day-reports')return false;const send=(code,value)=>{res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value));};if(req.method!=='GET'){send(405,{error:'Alleen lezen toegestaan'});return true;}const date=url.searchParams.get('date')||connectionDate(Date.now());if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date){send(400,{error:'Ongeldige datum'});return true;}send(200,await getDayReport(date));return true;}
