import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {initDayReports,normalizeReportEvent,mergePeaks,targetFor,recordDayReportEvents,getDayReport,backfillDayReport,reportDayBounds,handleDayReports} from './day-reports.mjs';
import {initConnections} from './connections-store.mjs';
const now=Date.parse('2026-09-14T12:00:00+02:00'),base={number:'225',category:'ICE',station:'Mannheim Hbf',eventMode:'arrival',plannedTimestamp:now,expectedTimestamp:now+20*60000,hasRealtime:true,from:'Amsterdam',to:'Basel',countryCode:'DE'};
test('peak ranking deduplicates matching services across stations and sources',()=>{const a=normalizeReportEvent(base,'DB',now),b=normalizeReportEvent({...base,station:'Basel',expectedTimestamp:now+30*60000},'SBB',now+1);assert.equal(mergePeaks([], [a,b]).length,1);assert.equal(mergePeaks([], [a,b])[0].delay,30);assert.equal(mergePeaks([],[{...a,cancelled:true}]).length,0);assert.equal(mergePeaks([],[{...a,realtime:false}]).length,0);assert.equal(mergePeaks([],Array.from({length:100},(_,i)=>({...a,run:String(i),delay:i}))).length,5);});
test('target selection is station, country and mode specific',()=>{const e=normalizeReportEvent(base,'DB',now);assert.equal(targetFor(e),'225-mannheim');assert.equal(targetFor({...e,mode:'departure'}),null);assert.equal(targetFor({...e,number:'40490',country:'NL'}),'40490-nl');assert.equal(targetFor({...e,number:'40490',country:'DE'}),null);assert.equal(targetFor({...e,number:'40421',station:'Wien Hbf'}),'40421-wien');assert.equal(targetFor({...e,station:'Stockholm Central'}),null);});
test('local calendar days respect daylight saving transitions',()=>{const march=reportDayBounds('2026-03-29'),oct=reportDayBounds('2026-10-25');assert.equal(march.end-march.start,23*3600000);assert.equal(oct.end-oct.start,25*3600000);});
test('durable summary, concurrent batches, history backfill and separate screen ranking',async()=>{
 const sqlite=new DatabaseSync(':memory:');await initConnections({sqlite});await initDayReports({sqlite});
 await Promise.all([recordDayReportEvents([base],'DB',now),recordDayReportEvents([{...base,expectedTimestamp:now+30*60000}],'DB',now+1)]);
 let report=await getDayReport('2026-09-14');assert.equal(report.peaks[0].delay,30);assert.equal(report.screenPeaks.length,0);assert.equal(Object.values(report.targets)[0].delay,30);
 await recordDayReportEvents([{...base,actualTimestamp:now+35*60000}],'DB',now+2);await recordDayReportEvents([{...base,expectedTimestamp:now}],'DB',now+3);report=await getDayReport('2026-09-14');assert.equal(Object.values(report.targets)[0].actual,now+35*60000);
 await recordDayReportEvents([base],'DB',now,{screen:true});report=await getDayReport('2026-09-14');assert.equal(report.screenPeaks[0].delay,20);assert.equal(report.peaks[0].delay,35);
 sqlite.exec('CREATE TABLE event_observations(service_uid TEXT,service_date TEXT,train_number TEXT,category TEXT,station_name TEXT,event_mode TEXT,source_id TEXT,observed_at BIGINT,planned_timestamp BIGINT,expected_timestamp BIGINT,actual_timestamp BIGINT,delay_minutes INTEGER,cancelled BOOLEAN,origin TEXT,destination TEXT,country_code TEXT)');
 sqlite.prepare('INSERT INTO event_observations VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('a','2026-09-14','999','IC','Test','departure','DB',now,now,now+60*60000,null,60,0,'A','B','DE');
 await backfillDayReport('2026-09-14');report=await getDayReport('2026-09-14');assert.equal(report.peaks[0].number,'999');assert.equal(report.screenPeaks.length,1);assert.ok(report.backfill);
 await initDayReports({sqlite});assert.equal((await getDayReport('2026-09-14')).peaks[0].delay,60);
 const res={writeHead(code){this.code=code;},end(body){this.value=JSON.parse(body);}};await handleDayReports({method:'GET'},res,new URL('http://x/api/day-reports?date=2026-02-30'));assert.equal(res.code,400);await handleDayReports({method:'GET'},res,new URL('http://x/api/day-reports?date=2026-09-14'));assert.equal(res.code,200);assert.equal(res.value.peaks.length,2);sqlite.close();
});

test('RFI boarding station is not a separate service origin',()=>{const a=normalizeReportEvent({...base,number:'9802',category:'FR',station:'Rimini',from:'Rimini',to:'Milano Centrale'},'RFI',now),b=normalizeReportEvent({...base,number:'9802',category:'FR',station:'Bologna Centrale',from:'Bologna Centrale',to:'Milano Centrale'},'RFI',now+1);assert.equal(mergePeaks([],[a,b]).length,1);});
