import {fetchBookings} from './flora-sanity.mjs';
import {rebuildStoredEvidence,INTERPRETATION_VERSION} from './flora-reconcile.mjs';
import {randomUUID} from 'node:crypto';
import {floraGoogle} from './flora-google.mjs';
import {readMail,writeMail,readFlora,writeFlora} from './flora-store.mjs';
import {activeBooking,waitingBooking,reservationScope,currentBookings,normalize,stays,hash,evaluate,controlOrder} from './flora-engine.mjs';
import {planFollowup} from './flora-followup.mjs';
import {extractMessage} from './flora-mail-source.mjs';
import {bookingQuery,cancellationApplies,parseDocument,matchEvidence,cancellation,hotelReplyReview,resolveEvidence,receiptCancellations,latestNSTickets,conversationCancellations} from './flora-mail-parser.mjs';

const stamp=()=>new Date().toISOString();
const needsRead=m=>m.version!==6||m.hasLinks||m.issues?.length;
export function rememberCancellation(state,c){const key=c.provider+'|'+c.reference,map=state.emailCancellations??={};if(!map[key]||map[key].at<c.at)map[key]=c;}
export function latestReservationState(state,e){const c=Object.values(state.emailCancellations||{}).filter(c=>cancellationApplies(c,e)).sort((a,b)=>b.at.localeCompare(a.at))[0];return c&&(!e.observedAt||e.observedAt<=c.at)?{...e,status:'cancelled',source:c.source,observedAt:c.at}:e;}

export function mailPlan(state,pilot=false,now=stamp(),mode='manual'){const attention=new Set(state.findings.filter(f=>f.status==='attention').map(f=>String(f.trip)));if(mode==='rules-only')return controlOrder(state,[...attention].filter(id=>!state.bookings.some(b=>String(b.index)===id&&!reservationScope(b,state.evidence,now))));const selected=mode==='attention'?attention:planFollowup(state).trips;return controlOrder(state,currentBookings(state.bookings).filter(b=>pilot?[6685,6677,6667,6657,6656].includes(Number(b.index)):((activeBooking(b.status)||waitingBooking(b.status))||state.evidence.some(e=>e.trip===String(b.index)&&e.status==='confirmed'))&&reservationScope(b,state.evidence,now)&&(selected.has(String(b.index))||mode!=='attention'&&state.emailChecks?.[b.index]?.parserVersion!==INTERPRETATION_VERSION)).map(b=>String(b.index)));}
export function createMailControl({read=readMail,write=writeMail,readState=readFlora,writeState=writeFlora,google=floraGoogle,extract=extractMessage,sync=fetchBookings,clock=()=>Date.now()}={}){
 let running=false;
 async function status(){const {value}=await read('job');const {queue,baseline,...publicJob}=value;return {...publicJob,total:queue?.length||0,stalled:value.status==='running'&&value.lease<clock()};}
 async function start({pilot=false,mode='manual',trips=[],findingIds=[]}={}){
  const referenceIds=[];if(!Array.isArray(findingIds)||findingIds.length>1000||findingIds.some(id=>typeof id!=='string'))throw Error('Ongeldige meldingselectie.');
  if(findingIds.length){if(mode!=='targeted')throw Error('Gebruik gerichte controle voor een meldingselectie.');const {state}=await readState();trips=[];for(const id of new Set(findingIds)){const f=state.findings.find(f=>f.id===id);if(!f)throw Error('Een geselecteerde melding bestaat niet meer. Vernieuw de selectie.');if(/^\d+$/.test(String(f.trip)))trips.includes(String(f.trip))||trips.push(String(f.trip));else{const proof=(f.evidence||[]).map(e=>state.evidence.find(x=>x.id===e.id)).filter(e=>e&&/^[A-Za-z0-9/-]{5,40}$/.test(e.reference||''));if(!proof.length)throw Error('Geen controleerbare referentie bij '+f.title+'.');referenceIds.push(...proof.map(e=>e.id));}}}

  if(mode==='targeted'){if(!Array.isArray(trips)||(!trips.length&&!referenceIds.length)||trips.length>200||trips.some(t=>!/^\d+A?$/i.test(String(t))))throw Error('Selecteer 1 tot 200 geldige boekingen.');trips=[...new Set(trips.map(t=>String(t).replace(/a$/i,'')))];}
  if(mode!=='rules-only'&&!(await google.status()).connected)throw Error('Koppel Gmail eerst.');
  const {value,revision}=await read('job');if(['running','queued'].includes(value.status))return {...await status(),alreadyRunning:true};
  if(!findingIds.length&&value.status==='failed'&&value.parserVersion===INTERPRETATION_VERSION&&value.pilot===pilot&&value.mode===mode&&(mode!=='targeted'||JSON.stringify([...value.requestedTrips||[]].sort())===JSON.stringify([...trips].sort()))&&value.done<value.queue.length){value.status='queued';value.phase='Hervatten vanaf de laatste opgeslagen boeking';delete value.owner;delete value.lease;await write('job',value,revision);return status();}
  if(mode==='targeted'&&trips.length){
   const freshBookings=await sync({trips});for(const id of trips){const matches=currentBookings(freshBookings).filter(b=>String(b.index)===id);if(matches.length!==1)throw Error('Boeking '+id+'A ontbreekt of heeft meerdere dossiers. Controleer de koppeling.');}
   for(let retry=0;retry<5;retry++){const fresh=await readState();fresh.state.bookings=fresh.state.bookings.filter(b=>!trips.includes(String(b.index))).concat(freshBookings.filter(b=>trips.includes(String(b.index))));Object.assign(fresh.state,evaluate(fresh.state,stamp(),{trips:new Set(trips)}));fresh.state.audit.push({at:stamp(),user:'FloRA',action:'Gerichte extra controle gestart',detail:trips.map(id=>id+'A').join(', ')});try{await writeState(fresh.state,fresh.revision);break;}catch(e){if(e.status!==409||retry===4)throw e;}}
  }
  const {state}=await readState(),queue=mode==='targeted'?controlOrder(state,trips).concat([...new Set(referenceIds)].map(id=>'reference:'+id)):mailPlan(state,pilot,stamp(),mode),selected=new Set(queue);
  const baseline=state.findings.filter(f=>(selected.has(String(f.trip))||findingIds.includes(f.id))).map(f=>({id:f.id,status:f.status,priority:f.priority,task:/^\d+$/.test(String(f.trip))?String(f.trip):'reference:'+f.evidence?.[0]?.id}));
  await write('job',{id:randomUUID(),parserVersion:INTERPRETATION_VERSION,status:'queued',mode,pilot,requestedTrips:mode==='targeted'?queue:undefined,queue,baseline,done:0,startedAt:stamp(),updatedAt:stamp(),phase:mode==='rules-only'?'Wacht op herbeoordeling opgeslagen bewijs':'Wacht op e-mailcontrole',messages:0,documents:0,errors:0,outcome:{selected:baseline.filter(f=>f.status==='attention').length,reviewed:0,resolved:0,remaining:baseline.filter(f=>f.status==='attention').length,reclassified:0}},revision);return status();
 }
 async function processBooking(b,get,job,onProgress=async()=>{},knownEvidence=[],allBookings=[b]){const query=bookingQuery(b),ids=[];
  const refs=[...new Set([...knownEvidence.filter(e=>e.trip===String(b.index)).map(e=>e.reference),...stays(b).map(t=>t.reference)].flatMap(r=>String(r||'').split(/[^A-Za-z0-9-]+/)).filter(r=>/^[A-Za-z0-9-]{5,40}$/.test(r)))],searchedRefs=new Set(),referenceQueries=[];
  let cancellationLimited=false;
  async function searchRefs(references){for(const ref of references){if(searchedRefs.has(ref))continue;if(searchedRefs.size>=50){cancellationLimited=true;return;}searchedRefs.add(ref);let token='',found=0;const q='"'+ref+'" -in:spam -in:trash';referenceQueries.push(q);do{const result=await get('messages',{q,maxResults:'100',...(token?{pageToken:token}:{})});ids.push(...(result.messages||[]).map(m=>m.id));found+=(result.messages||[]).length;token=result.nextPageToken||'';if(found>=200&&token){cancellationLimited=true;break;}}while(token);}}
  await searchRefs(refs);
  let page='',limited=cancellationLimited;const deadline=clock()+120000;do{const result=await get('messages',{q:query,maxResults:'100',...(page?{pageToken:page}:{})});ids.push(...(result.messages||[]).map(m=>m.id));page=result.nextPageToken||'';if(ids.length>=200&&page){limited=true;break;}}while(page);
  const messages=[],errors=[],events=[],threads=new Set();
  let processed=0;const readIds=new Set();for(let cursor=0;cursor<ids.length;cursor++){const id=ids[cursor];if(readIds.has(id))continue;readIds.add(id);await onProgress({processed,total:new Set(ids).size});processed++;if(clock()>deadline){limited=true;break;}const cached=await read('message:'+id);let m=cached.value;
   try{if(needsRead(m)){m=await extract(await get('messages/'+id,{format:'full'}),get);m.version=6;await write('message:'+id,m,cached.revision);}messages.push(m);if(m.threadId&&!threads.has(m.threadId)){threads.add(m.threadId);const thread=await get('threads/'+m.threadId,{format:'minimal'});ids.push(...(thread.messages||[]).map(x=>x.id));}if(/cancel|annul|refund|storn|wijzig|amend|changed|änder/i.test(m.subject)&&!cancellation(m)&&!(/@teldartravel\.com\b/i.test(m.from)&&/days to cancel|without charge/i.test(m.subject)&&m.docs.some(d=>parseDocument(d,m)))&&!m.docs.some(d=>parseDocument(d,m))&&m.docs.some(d=>d.text.includes(String(b.index)+'A')||stays(b).some(t=>t.reference&&d.text.includes(t.reference))))errors.push({message:id,detail:'Mogelijke annulering of wijziging: handmatige beoordeling nodig.'});for(const doc of m.docs){const e=parseDocument(doc,m);if(e){events.push(e);await searchRefs([String(e.reference||'').split('/')[0]].filter(r=>/^[A-Za-z0-9-]{5,40}$/.test(r)));}}errors.push(...m.issues.map(s=>({message:id,detail:s})));}catch(e){errors.push({message:id,detail:e.message});}
  }
   limited ||= cancellationLimited;
   const byRef=new Map();for(const e of latestNSTickets(events,messages).sort((a,b)=>a.observedAt.localeCompare(b.observedAt))){const key=e.provider+'|'+e.reference,old=byRef.get(key);if(!old||!e.partialEvidence||old.partialEvidence||e.start!==old.start)byRef.set(key,e);}
   for(const m of messages){const provider=hotelReplyReview(m);if(provider&&!events.some(e=>e.messageId===m.id)&&!events.some(e=>e.provider===provider&&e.observedAt>=m.at))errors.push({message:m.id,detail:'Nieuw hotelantwoord over de reservering: bevestiging, wijziging of afwijzing handmatig beoordelen.'});}
  const retired=new Set(messages.flatMap(m=>m.retiredLinks||[]));for(const [key,e] of byRef)if(e.ticketLink&&retired.has(e.ticketLink))byRef.set(key,{...e,status:'cancelled'});
  const cancellations=[...messages.map(cancellation).filter(Boolean),...receiptCancellations(messages,events),...conversationCancellations(messages,events)];for(const c of cancellations){for(const [key,old] of byRef)if(cancellationApplies(c,old)&&old.observedAt<=c.at)byRef.set(key,{...old,status:'cancelled',source:c.source,observedAt:c.at});}
  const linked=[];for(const e of byRef.values()){const match=e.tripHint&&e.tripHint!==String(b.index)?resolveEvidence(e,allBookings):matchEvidence(e,b);if(match?.trip===String(b.index)&&match.todoKey)linked.push(match);}
  for(const t of stays(b)){const group=linked.filter(e=>e.todoKey===t._key&&e.status==='confirmed'&&e.provider==='Premier Inn');if(group.length>1&&group.length===Number(t.quantity)&&group.every(e=>e.messageId===group[0].messageId&&e.start===group[0].start&&e.end===group[0].end)){for(const e of group){e.group=hash([String(b.index),t._key,e.messageId]);e.roomGroupVerified=true;}}}
  const checks=stays(b).map(t=>{const proof=linked.filter(e=>e.todoKey===t._key),words=normalize(t.title.split('|')[0]).split(' ').filter(w=>w.length>3&&!['hotel','mail','email','double','twin','standard','comfort','tweepersoonskamer','standaard','personen','buitenhut','binnenhut','privé','best','western','premier'].includes(w)),candidates=messages.filter(m=>{if(proof.some(e=>e.messageId===m.id))return true;const text=normalize(m.subject+' '+m.docs.map(d=>d.text).join(' '));if(t.reference)return text.replace(/ /g,'').includes(normalize(t.reference).replace(/ /g,''));if(t.type==='Hotel'&&/nsinternational|oebb/i.test(m.from))return false;if(t.type==='Nachttrein')return /nsinternational|oebb/i.test(m.from);return words.some(w=>text.includes(w));}),sourceErrors=errors.filter(e=>candidates.some(m=>m.id===e.message)||!messages.some(m=>m.id===e.message));return {todoKey:t._key,title:t.title,provider:t.provider,at:stamp(),query,referenceQueries,state:limited||sourceErrors.length?'incomplete':proof.length?'found':candidates.length?'candidates':'not-found',explanation:limited?'Zoeklimiet of tijdslimiet bereikt; niet alles gecontroleerd.':sourceErrors.length?'Een of meer bronnen konden niet volledig worden gelezen.':proof.length?'Reserveringsgegevens uit bron gelezen; inhoudelijke uitkomst staat bij Meldingen.':candidates.length?'Mogelijke berichten gevonden, maar geen eenduidig uitleesbare bevestiging gekoppeld.':'Geen bericht gevonden met deze zoekopdracht; dit bewijst niet dat er geen reservering is.',references:proof.map(e=>e.reference),sources:candidates.map(m=>({id:m.id,subject:m.subject,url:m.url,at:m.at,documents:m.docs.map(d=>d.label),retiredTickets:(m.retiredLinks||[]).length,issues:m.issues})),fields:proof.map(e=>({reference:e.reference,provider:e.provider,start:e.start,end:e.end,name:e.name,capacity:e.capacity,occupants:e.occupants,product:e.product,document:e.document,source:e.source})),errors:sourceErrors};});
  return {checks,linked,messages:messages.length,documents:messages.reduce((n,m)=>n+m.docs.length,0),errors:errors.length+(limited?1:0),cancellations,retiredLinks:[...retired],fingerprint:hash(b),trip:String(b.index)};
 }
 async function save(result){for(let retry=0;retry<5;retry++){const {state,revision}=await readState(),b=currentBookings(state.bookings).find(b=>String(b.index)===result.trip);if(!b||hash(b)!==result.fingerprint)throw Error('Boeking is tijdens de controle gewijzigd; voer opnieuw uit.');for(const e of state.evidence)if((!result.scoped||e.trip===result.trip)&&e.ticketLink&&result.retiredLinks.includes(e.ticketLink))e.status='cancelled';
  for(const c of result.cancellations){rememberCancellation(state,c);for(const e of state.evidence)if((!result.scoped||e.trip===result.trip)&&cancellationApplies(c,e)&&(!e.observedAt||e.observedAt<=c.at)){e.status='cancelled';e.source=c.source;e.observedAt=c.at;}}
  (state.emailChecks??={})[result.trip]={at:stamp(),parserVersion:INTERPRETATION_VERSION,stays:result.checks};const ids=new Set(result.linked.map(e=>e.id)),refs=new Set(result.linked.map(e=>e.provider+'|'+e.reference));state.evidence=state.evidence.filter(e=>!ids.has(e.id)&&!(e.automaticEmail&&e.trip===result.trip&&refs.has(e.provider+'|'+e.reference))).concat(result.linked.map(e=>{const old=state.evidence.find(x=>x.id===e.id);return {...latestReservationState(state,old?.manualSourceReview&&old.messageId===e.messageId?old:e.partialEvidence&&old&&!old.partialEvidence&&old.start===e.start?old:e),importedAt:stamp(),automaticEmail:true};}));Object.assign(state,evaluate(state,stamp(),{trips:new Set([result.trip])}));try{await writeState(state,revision);return;}catch(e){if(e.status!==409||retry===4)throw e;}}}
 // Discovery must resolve the reference history before publishing newly found reservations.
 async function verifyReferences(proofs,get){
  const refs=[...new Set(proofs.map(e=>String(e.reference||'').split('/')[0]).filter(r=>/^[A-Za-z0-9-]{5,40}$/.test(r)))],messages=[],seen=new Set(),threads=new Set();
  if(refs.length>50)throw Error('Te veel referenties; referentiecontrole niet voltooid.');
  for(const ref of refs){let page='',count=0;do{const result=await get('messages',{q:'"'+ref+'" -in:spam -in:trash',maxResults:'100',...(page?{pageToken:page}:{})});for(const {id} of result.messages||[]){if(seen.has(id))continue;seen.add(id);const cached=await read('message:'+id);let m=cached.value;if(needsRead(m)){m=await extract(await get('messages/'+id,{format:'full'}),get);m.version=6;await write('message:'+id,m,cached.revision);}if(m.issues?.length)throw Error('Referentiebron niet volledig leesbaar.');messages.push(m);if(m.threadId&&!threads.has(m.threadId)){threads.add(m.threadId);const thread=await get('threads/'+m.threadId,{format:'minimal'});result.messages.push(...(thread.messages||[]));}}count+=(result.messages||[]).length;page=result.nextPageToken||'';if(count>=200&&page)throw Error('Referentiecontrole bereikte de zoeklimiet.');}while(page);}
  const events=messages.flatMap(m=>m.docs.map(d=>parseDocument(d,m)).filter(Boolean));
  const cancellations=[...messages.map(cancellation).filter(Boolean),...receiptCancellations(messages,events),...conversationCancellations(messages,events)];
  for(const m of messages)if(/annuleringsbevestiging|cancellation|stornierung|wijzig|amend|changed|änder/i.test(m.subject)&&!cancellations.some(c=>c.source===m.url)&&!m.docs.some(d=>parseDocument(d,m)))throw Error('Mogelijke annulering of wijziging nog niet eenduidig leesbaar.');
  const latest=new Map();for(const e of latestNSTickets([...proofs,...events],messages).sort((a,b)=>a.observedAt.localeCompare(b.observedAt))){if(!refs.includes(String(e.reference).split('/')[0]))continue;const key=e.provider+'|'+e.reference,old=latest.get(key);if(!old||!e.partialEvidence||old.partialEvidence||e.start!==old.start)latest.set(key,e);}
  return {proofs:[...latest.values()],cancellations};
 }
 async function discover(get,job,progress){
  const watermark=await read('discovery');const from=job.discoveryFrom||(watermark.value.at?new Date(Date.parse(watermark.value.at)-7*86400000).toISOString().slice(0,10):new Date(clock()-90*86400000).toISOString().slice(0,10));
  if(!job.cancelFixApplied&&job.lastIssues?.some(e=>/cancel is not defined/.test(e.detail))){job.errors=Math.max(0,job.errors-(job.discoveryErrors||0));job.discoveryErrors=0;job.discoveryPage='';job.discoveryMessages=0;job.lastIssues=[];}job.cancelFixApplied=true;job.discoveryFrom=from;job.discoveryErrors??=0;let page=job.discoveryPage||'';
  do{job.phase='Mailbox doorzoeken op niet-gekoppelde reserveringen (ondersteunde leveranciers)';await progress();const list=await get('messages',{q:'after:'+from+' {from:expediataap.nl from:nsinternational.nl from:oebb.at from:finnlines.com from:whitbread.com from:premierinn.com from:hotelabc.ch from:postchur.ch from:lhotel-montpellier.com from:teldartravel.com from:ratehawk.com from:bernerhof-interlaken.ch from:hotel-federale.ch} -in:spam -in:trash',maxResults:'20',...(page?{pageToken:page}:{})});
   for(const {id} of list.messages||[]){const cache=await read('message:'+id);let m=cache.value;try{if(needsRead(m)){m=await extract(await get('messages/'+id,{format:'full'}),get);m.version=6;await write('message:'+id,m,cache.revision);}const rawProofs=m.docs.map(d=>parseDocument(d,m)).filter(Boolean),verified=await verifyReferences(rawProofs,get),proofs=verified.proofs,cancels=[...verified.cancellations,...[cancellation(m)].filter(Boolean)];
    for(let retry=0;retry<4;retry++){const {state,revision}=await readState(),bookings=currentBookings(state.bookings);const changed=new Set();
     for(const cancel of cancels){rememberCancellation(state,cancel);
     if(cancel)for(const e of state.evidence)if(cancellationApplies(cancel,e)&&(!e.observedAt||e.observedAt<=cancel.at)){e.status='cancelled';e.source=cancel.source;e.observedAt=cancel.at;changed.add(e.trip||'onbekend');}}
     for(const proof of proofs){const e=latestReservationState(state,proof);if(e.end<stamp().slice(0,10))continue;const linked=resolveEvidence(e,bookings);const previous=state.evidence.find(x=>x.id===linked.id);if(previous&&!previous.partialEvidence&&linked.partialEvidence&&previous.start===linked.start||previous?.observedAt>=linked.observedAt&&!(previous.partialEvidence&&!linked.partialEvidence))continue;if(linked.trip&&state.emailChecks)delete state.emailChecks[linked.trip];state.evidence=state.evidence.filter(x=>x.id!==linked.id).concat({...linked,automaticEmail:true,importedAt:stamp()});changed.add(linked.trip||'onbekend');}
     if(changed.size)Object.assign(state,evaluate(state,stamp(),{trips:changed}));state.emailDiscovery={from,checkedAt:stamp(),coverage:'Expedia TAAP, NS International, ÖBB, Finnlines, Premier Inn, Hotel ABC, Post Chur, Best Western Montpellier, Teldar, RateHawk, Bernerhof en Federale. Andere afzenders alleen via boekingsgerichte zoekopdrachten.'};try{await writeState(state,revision);break;}catch(e){if(e.status!==409||retry===3)throw e;}}
    job.discoveryMessages=(job.discoveryMessages||0)+1;
   }catch(e){job.errors++;job.discoveryErrors++;job.lastIssues=[{trip:"Mailbox",detail:"Referentiecontrole niet afgerond; geen nieuwe melding uit dit bericht gepubliceerd. "+e.message}];}await progress();}
   page=list.nextPageToken||'';job.discoveryPage=page;await progress();
  }while(page);
  if(!job.discoveryErrors){const latest=await read('discovery');await write('discovery',{at:job.startedAt},latest.revision);}
 }
 async function checkUnlinkedCancellations(get,job,progress){
  const snapshot=await readState(),refs=[...new Set(snapshot.state.evidence.filter(e=>!e.trip&&e.status==='confirmed').map(e=>String(e.reference||'').split('/')[0]).filter(r=>/^[A-Za-z0-9-]{5,40}$/.test(r)))];
  for(let offset=0;offset<refs.length;offset+=20){let page='',count=0;do{
   job.phase='Annuleringen zoeken bij reserveringen zonder gekoppelde reis';await progress();
   const list=await get('messages',{q:'{'+refs.slice(offset,offset+20).map(r=>'"'+r+'"').join(' ')+'} {subject:annuleringsbevestiging subject:cancellation subject:stornierung subject:refund} -in:spam -in:trash',maxResults:'100',...(page?{pageToken:page}:{})});
   for(const {id} of list.messages||[]){const cached=await read('message:'+id);let m=cached.value;if(needsRead(m)){m=await extract(await get('messages/'+id,{format:'full'}),get);m.version=6;await write('message:'+id,m,cached.revision);}const c=cancellation(m);job.messages++;if(!c){job.errors++;continue;}for(let retry=0;retry<5;retry++){const {state,revision}=await readState();rememberCancellation(state,c);const changed=new Set();for(const e of state.evidence)if(cancellationApplies(c,e)&&(!e.observedAt||e.observedAt<=c.at)){e.status='cancelled';e.source=c.source;e.observedAt=c.at;changed.add(e.trip||'onbekend');}if(changed.size)Object.assign(state,evaluate(state,stamp(),{trips:changed}));try{await writeState(state,revision);break;}catch(e){if(e.status!==409||retry===4)throw e;}}await progress();}
   count+=(list.messages||[]).length;page=list.nextPageToken||'';if(count>=200&&page){job.errors++;break;}
  }while(page);}
  job.unlinkedCancellationsChecked=true;await progress();
 }
 async function updateOutcome(job){const {state}=await readState(),current=new Map(state.findings.map(f=>[f.id,f])),baseline=(job.baseline||[]).filter(f=>f.status==='attention');job.outcome={selected:baseline.length,reviewed:baseline.filter(f=>job.queue.slice(0,job.done).includes(f.task||f.id.split(':')[0])).length,resolved:baseline.filter(f=>!current.has(f.id)||current.get(f.id).status==='checked').length,remaining:baseline.filter(f=>current.get(f.id)?.status==='attention').length,reclassified:baseline.filter(f=>current.has(f.id)&&(current.get(f.id).priority!==f.priority||current.get(f.id).status!==f.status)).length,alarms:state.findings.filter(f=>job.queue.includes(f.trip)&&f.status==='alarm').length};}
 async function reassess(job,progress){
  while(job.done<job.queue.length){
   const batch=job.queue.slice(job.done,job.done+10),trips=new Set(batch);job.current=batch.join(', ');job.phase='Opgeslagen bewijs opnieuw beoordelen: '+batch.map(t=>t+'A').join(', ');await progress();
   const snapshot=await readState(),ids=new Set(snapshot.state.evidence.filter(e=>trips.has(e.trip||'onbekend')).map(e=>e.messageId).filter(Boolean));
   for(const trip of batch)for(const stay of snapshot.state.emailChecks?.[trip]?.stays||[])for(const m of stay.sources||[])ids.add(m.id);
   const messages=[];for(const id of ids){const cached=await read('message:'+id);if(cached.value.docs)messages.push(cached.value);}
   for(let retry=0;retry<5;retry++){const fresh=await readState();rebuildStoredEvidence(fresh.state,messages,stamp(),{trips});try{await writeState(fresh.state,fresh.revision);break;}catch(e){if(e.status!==409||retry===4)throw e;}}
   job.done+=batch.length;job.documents+=messages.reduce((n,m)=>n+m.docs.length,0);await updateOutcome(job);await progress();
  }
 }
 async function stop(){for(let retry=0;retry<5;retry++){const {value,revision}=await read('job');if(!['queued','running'].includes(value.status))return status();const next={...value,status:'stopped',phase:'Controle gestopt door beheerder. Opgeslagen resultaten blijven bewaard.',updatedAt:stamp(),finishedAt:stamp()};delete next.owner;delete next.lease;try{await write('job',next,revision);return status();}catch(e){if(e.status!==409||retry===4)throw e;}}}
 async function tick(){if(running)return;running=true;let owner,job;
  try{const stored=await read('job');job=stored.value;if(!['queued','running'].includes(job.status)||job.status==='running'&&job.lease>clock())return;owner=randomUUID();job.owner=owner;job.lease=clock()+300000;job.status='running';job.updatedAt=stamp();let revision=await write('job',job,stored.revision);const assertRunning=async()=>{const current=await read('job');if(current.value.id!==job.id||current.value.status==='stopped'||current.value.owner!==owner)throw Error('Controle gestopt.');};const reader=job.mode==='rules-only'?null:await google.reader();const get=reader?async(...args)=>{await assertRunning();return reader(...args);}:null;
   const progress=async()=>{await assertRunning();job.updatedAt=stamp();job.lease=clock()+300000;revision=await write('job',job,revision);};
   if(job.mode==='rules-only'){if(job.parserVersion!==INTERPRETATION_VERSION)job.done=0;job.parserVersion=INTERPRETATION_VERSION;await reassess(job,progress);}
   const initial=await readState();if(!['rules-only','attention','targeted'].includes(job.mode)&&initial.state.interpretationVersion!==INTERPRETATION_VERSION){
    const ids=new Set((initial.state.evidence||[]).map(e=>e.messageId).filter(Boolean));for(const c of Object.values(initial.state.emailChecks||{}))for(const t of c.stays||[])for(const m of t.sources||[])ids.add(m.id);
    const messages=[];let processed=0;for(const id of ids){const cached=await read('message:'+id);if(cached.value.docs)messages.push(cached.value);if(++processed%50===0){job.phase='Opgeslagen bronnen opnieuw beoordelen: '+processed+' van '+ids.size;job.updatedAt=stamp();job.lease=clock()+300000;revision=await write('job',job,revision);}}
    for(let retry=0;retry<5;retry++){const fresh=await readState();rebuildStoredEvidence(fresh.state,messages,stamp());try{await writeState(fresh.state,fresh.revision);break;}catch(e){if(e.status!==409||retry===4)throw e;}}
   }
   if(job.parserVersion!==INTERPRETATION_VERSION){const fresh=await readState();const alarms=new Set(fresh.state.findings.filter(f=>f.status==='alarm').map(f=>String(f.trip)));job.previousPass={version:job.parserVersion,done:job.done,messages:job.messages,documents:job.documents};job.queue=job.mode==='targeted'?controlOrder(fresh.state,job.requestedTrips||job.queue):mailPlan(fresh.state,job.pilot,stamp(),job.mode);job.done=0;job.parserVersion=INTERPRETATION_VERSION;job.phase='Bijgestelde regels: open alarmen eerst opnieuw controleren';revision=await write('job',job,revision);}
   if(!job.pilot&&!['attention','rules-only','targeted'].includes(job.mode)&&!job.unlinkedCancellationsChecked)await checkUnlinkedCancellations(get,job,progress);
   while(job.done<job.queue.length){const trip=job.queue[job.done];if(trip.startsWith('reference:')){job.phase='Geselecteerde reserveringsreferentie controleren';await progress();const original=(await readState()).state.evidence.find(e=>e.id===trip.slice(10));if(!original)throw Error('Bron van geselecteerde melding ontbreekt.');const verified=await verifyReferences([original],get);await assertRunning();for(let retry=0;retry<5;retry++){const fresh=await readState(),state=fresh.state,changed=new Set([original.trip||'onbekend']);for(const c of verified.cancellations)rememberCancellation(state,c);const proofs=verified.proofs.map(e=>{const linked=resolveEvidence(latestReservationState(state,e),currentBookings(state.bookings));changed.add(linked.trip||'onbekend');return {...linked,automaticEmail:true,importedAt:stamp()};});const ids=new Set(proofs.map(e=>e.id));state.evidence=state.evidence.filter(e=>e.id!==original.id&&!ids.has(e.id)).concat(proofs);Object.assign(state,evaluate(state,stamp(),{trips:changed}));state.audit.push({at:stamp(),user:'FloRA',action:'Geselecteerde referentie gecontroleerd',detail:original.provider+' · '+original.reference});try{await writeState(state,fresh.revision);break;}catch(e){if(e.status!==409||retry===4)throw e;}}job.done++;await updateOutcome(job);await progress();continue;}job.phase='Boeking '+trip+'A: berichten en tickets lezen';job.current=trip;job.updatedAt=stamp();job.lease=clock()+300000;revision=await write('job',job,revision);const {state}=await readState(),b=currentBookings(state.bookings).find(b=>String(b.index)===trip);if(!b)throw Error('Boeking niet meer aanwezig in Sanity-selectie.');const result=await processBooking(b,get,job,async({processed,total})=>{job.phase='Boeking '+trip+'A: bericht '+processed+' van '+total+' verwerken';job.updatedAt=stamp();job.lease=clock()+300000;revision=await write('job',job,revision);},state.evidence,currentBookings(state.bookings));result.scoped=job.mode==='targeted';await assertRunning();await save(result);job.done++;job.messages+=result.messages;job.documents+=result.documents;job.errors+=result.errors;job.lastIssues=result.checks.flatMap(c=>c.errors.map(e=>({trip,detail:e.detail}))).slice(0,5);await updateOutcome(job);console.info('[FloRA]',JSON.stringify({run:job.id,mode:job.mode,trip,done:job.done,total:job.queue.length,messages:result.messages,errors:result.errors,outcome:job.outcome}));job.updatedAt=stamp();revision=await write('job',job,revision);}
   if(!job.pilot&&!['attention','rules-only','targeted'].includes(job.mode))await discover(get,job,progress);
   await updateOutcome(job);
   job.status=job.errors?'partial':'completed';job.phase=job.mode==='rules-only'?'Opgeslagen bewijs opnieuw beoordeeld; geen nieuwe e-mails opgehaald.':job.errors?'Afgerond met onvolledige bronnen; bekijk de details.':'Zoekronde afgerond; bekijk de inhoudelijke resultaten per overnachting.';job.finishedAt=stamp();delete job.owner;delete job.lease;await write('job',job,revision);for(let retry=0;retry<4;retry++){const {state,revision:r}=await readState();state.audit.push({at:stamp(),user:'FloRA',action:job.mode==='targeted'?'Gerichte extra controle afgerond':job.mode==='rules-only'?'Aandachtspunten opnieuw beoordeeld':job.mode==='attention'?'E-mailcontrole aandachtspunten':'E-mailcontrole '+(job.pilot?'voorbeeldboekingen':'afgerond'),detail:JSON.stringify(job.outcome)+'. '+job.done+' boekingen, '+job.messages+' berichten, '+job.documents+' documenten, '+job.errors+' onvolledige bronnen. Zie Boekingen voor zoekopdrachten en bewijs.'});if(!job.errors&&!['attention','rules-only','targeted'].includes(job.mode))state.emailCheckpoint={at:job.startedAt,finishedAt:stamp(),pilot:job.pilot};try{await writeState(state,r);break;}catch(e){if(e.status!==409||retry===3)throw e;}}
   // Finish an in-flight older run first, then revisit its bookings with the corrected interpretation.
   if(job.parserVersion!==INTERPRETATION_VERSION)await start({pilot:job.pilot,mode:'parser-upgrade'});
  }catch(e){if(job?.id){try{const latest=await read('job');if(latest.value.owner===owner)await write('job',{...latest.value,status:'failed',phase:e.message,updatedAt:stamp()},latest.revision);}catch{}}}finally{running=false;}
 }
 return {status,start,stop,tick,processBooking,verifyReferences};
}
export const floraMail=createMailControl();
export function startFloraMail(){setTimeout(()=>void floraMail.tick(),20000).unref();setInterval(()=>void floraMail.tick(),30000).unref();}
