import {rebuildStoredEvidence,INTERPRETATION_VERSION} from './flora-reconcile.mjs';
import {randomUUID} from 'node:crypto';
import {floraGoogle} from './flora-google.mjs';
import {readMail,writeMail,readFlora,writeFlora} from './flora-store.mjs';
import {activeBooking,waitingBooking,reservationScope,currentBookings,normalize,stays,hash,evaluate} from './flora-engine.mjs';
import {planFollowup} from './flora-followup.mjs';
import {extractMessage} from './flora-mail-source.mjs';
import {bookingQuery,parseDocument,matchEvidence,cancellation,hotelReplyReview,resolveEvidence,receiptCancellations,latestNSTickets} from './flora-mail-parser.mjs';

const stamp=()=>new Date().toISOString();
const needsRead=m=>![4,5].includes(m.version)||m.version!==5&&/@(?:bernerhof-interlaken|hotel-federale)\.ch\b/i.test(m.from||'')||m.hasLinks||m.issues?.length;
export function rememberCancellation(state,c){const key=c.provider+'|'+c.reference,map=state.emailCancellations??={};if(!map[key]||map[key].at<c.at)map[key]=c;}
export function latestReservationState(state,e){const c=state.emailCancellations?.[e.provider+'|'+e.reference];return c&&(!e.observedAt||e.observedAt<=c.at)?{...e,status:'cancelled',source:c.source,observedAt:c.at}:e;}

export function mailPlan(state,pilot=false,now=stamp(),mode='manual'){const attention=new Set(state.findings.filter(f=>f.status==='attention').map(f=>String(f.trip)));if(mode==='rules-only')return [...attention];const selected=mode==='attention'?attention:planFollowup(state).trips;return currentBookings(state.bookings).filter(b=>pilot?[6685,6677,6667,6657,6656].includes(Number(b.index)):((activeBooking(b.status)||waitingBooking(b.status))||state.evidence.some(e=>e.trip===String(b.index)&&e.status==='confirmed'))&&reservationScope(b,state.evidence,now)&&(selected.has(String(b.index))||mode!=='attention'&&state.emailChecks?.[b.index]?.parserVersion!==INTERPRETATION_VERSION)).map(b=>String(b.index));}
export function createMailControl({read=readMail,write=writeMail,readState=readFlora,writeState=writeFlora,google=floraGoogle,extract=extractMessage,clock=()=>Date.now()}={}){
 let running=false;
 async function status(){const {value}=await read('job');const {queue,baseline,...publicJob}=value;return {...publicJob,total:queue?.length||0,stalled:value.status==='running'&&value.lease<clock()};}
 async function start({pilot=false,mode='manual'}={}){
  if(mode!=='rules-only'&&!(await google.status()).connected)throw Error('Koppel Gmail eerst.');
  const {value,revision}=await read('job');if(['running','queued'].includes(value.status))return {...await status(),alreadyRunning:true};
  if(value.status==='failed'&&value.parserVersion===INTERPRETATION_VERSION&&value.pilot===pilot&&value.mode===mode&&value.done<value.queue.length){value.status='queued';value.phase='Hervatten vanaf de laatste opgeslagen boeking';delete value.owner;delete value.lease;await write('job',value,revision);return status();}
  const {state}=await readState(),queue=mailPlan(state,pilot,stamp(),mode),selected=new Set(queue);
  const baseline=state.findings.filter(f=>selected.has(String(f.trip))).map(f=>({id:f.id,status:f.status,priority:f.priority}));
  await write('job',{id:randomUUID(),parserVersion:INTERPRETATION_VERSION,status:'queued',mode,pilot,queue,baseline,done:0,startedAt:stamp(),updatedAt:stamp(),phase:mode==='rules-only'?'Wacht op herbeoordeling opgeslagen bewijs':'Wacht op e-mailcontrole',messages:0,documents:0,errors:0,outcome:{selected:baseline.filter(f=>f.status==='attention').length,reviewed:0,resolved:0,remaining:baseline.filter(f=>f.status==='attention').length,reclassified:0}},revision);return status();
 }
 async function processBooking(b,get,job,onProgress=async()=>{},knownEvidence=[],allBookings=[b]){const query=bookingQuery(b),ids=[];
  const refs=[...new Set(knownEvidence.filter(e=>e.trip===String(b.index)).map(e=>String(e.reference||'').split('/')[0]).filter(r=>/^[A-Za-z0-9-]{5,40}$/.test(r)))];
  let cancellationLimited=false;
  for(let offset=0;offset<refs.length;offset+=20){let token='';let found=0;do{const result=await get('messages',{q:'{'+refs.slice(offset,offset+20).map(r=>'"'+r+'"').join(' ')+'} {subject:annuleringsbevestiging subject:cancellation subject:stornierung subject:refund} -in:spam -in:trash',maxResults:'100',...(token?{pageToken:token}:{})});ids.push(...(result.messages||[]).map(m=>m.id));found+=(result.messages||[]).length;token=result.nextPageToken||'';if(found>=200&&token){cancellationLimited=true;break;}}while(token);}
  let page='',limited=cancellationLimited;const deadline=clock()+120000;do{const result=await get('messages',{q:query,maxResults:'100',...(page?{pageToken:page}:{})});ids.push(...(result.messages||[]).map(m=>m.id));page=result.nextPageToken||'';if(ids.length>=200&&page){limited=true;break;}}while(page);
  const messages=[],errors=[],events=[];
  let processed=0;for(const id of [...new Set(ids)]){await onProgress({processed,total:new Set(ids).size});processed++;if(clock()>deadline){limited=true;break;}const cached=await read('message:'+id);let m=cached.value;
   try{if(needsRead(m)){m=await extract(await get('messages/'+id,{format:'full'}),get);m.version=5;await write('message:'+id,m,cached.revision);}messages.push(m);if(/cancel|annul|refund|storn/i.test(m.subject)&&!cancellation(m)&&!(/@teldartravel\.com\b/i.test(m.from)&&/days to cancel|without charge/i.test(m.subject)&&m.docs.some(d=>parseDocument(d,m)))&&m.docs.some(d=>d.text.includes(String(b.index)+'A')||stays(b).some(t=>t.reference&&d.text.includes(t.reference))))errors.push({message:id,detail:'Mogelijke annulering of wijziging: handmatige beoordeling nodig.'});for(const doc of m.docs){const e=parseDocument(doc,m);if(e)events.push(e);}errors.push(...m.issues.map(s=>({message:id,detail:s})));}catch(e){errors.push({message:id,detail:e.message});}
  }
   const byRef=new Map();for(const e of latestNSTickets(events,messages).sort((a,b)=>a.observedAt.localeCompare(b.observedAt))){const key=e.provider+'|'+e.reference,old=byRef.get(key);if(!old||!e.partialEvidence||old.partialEvidence||e.start!==old.start)byRef.set(key,e);}
   for(const m of messages){const provider=hotelReplyReview(m);if(provider&&!events.some(e=>e.messageId===m.id)&&!events.some(e=>e.provider===provider&&e.observedAt>=m.at))errors.push({message:m.id,detail:'Nieuw hotelantwoord over de reservering: bevestiging, wijziging of afwijzing handmatig beoordelen.'});}
  const retired=new Set(messages.flatMap(m=>m.retiredLinks||[]));for(const [key,e] of byRef)if(e.ticketLink&&retired.has(e.ticketLink))byRef.set(key,{...e,status:'cancelled'});
  const cancellations=[...messages.map(cancellation).filter(Boolean),...receiptCancellations(messages,events)];for(const c of cancellations){const key=c.provider+'|'+c.reference,old=byRef.get(key);if(old&&old.observedAt<=c.at)byRef.set(key,{...old,status:'cancelled',source:c.source,observedAt:c.at});}
  const linked=[];for(const e of byRef.values()){const match=e.tripHint&&e.tripHint!==String(b.index)?resolveEvidence(e,allBookings):matchEvidence(e,b);if(match?.trip===String(b.index)&&match.todoKey)linked.push(match);}
  for(const t of stays(b)){const group=linked.filter(e=>e.todoKey===t._key&&e.status==='confirmed'&&e.provider==='Premier Inn');if(group.length>1&&group.length===Number(t.quantity)&&group.every(e=>e.messageId===group[0].messageId&&e.start===group[0].start&&e.end===group[0].end)){for(const e of group){e.group=hash([String(b.index),t._key,e.messageId]);e.roomGroupVerified=true;}}}
  const checks=stays(b).map(t=>{const proof=linked.filter(e=>e.todoKey===t._key),words=normalize(t.title.split('|')[0]).split(' ').filter(w=>w.length>3&&!['hotel','double','tweepersoonskamer','standaard','personen','buitenhut','binnenhut','privé'].includes(w)),candidates=messages.filter(m=>{if(proof.some(e=>e.messageId===m.id))return true;const text=normalize(m.subject+' '+m.docs.map(d=>d.text).join(' '));if(t.reference)return text.replace(/ /g,'').includes(normalize(t.reference).replace(/ /g,''));if(t.type==='Hotel'&&/nsinternational|oebb/i.test(m.from))return false;if(t.type==='Nachttrein')return /nsinternational|oebb/i.test(m.from);return words.some(w=>text.includes(w));}),sourceErrors=errors.filter(e=>candidates.some(m=>m.id===e.message)||!messages.some(m=>m.id===e.message));return {todoKey:t._key,title:t.title,provider:t.provider,at:stamp(),query,state:limited||sourceErrors.length?'incomplete':proof.length?'found':candidates.length?'candidates':'not-found',explanation:limited?'Zoeklimiet of tijdslimiet bereikt; niet alles gecontroleerd.':sourceErrors.length?'Een of meer bronnen konden niet volledig worden gelezen.':proof.length?'Reserveringsgegevens uit bron gelezen; inhoudelijke uitkomst staat bij Meldingen.':candidates.length?'Mogelijke berichten gevonden, maar geen eenduidig uitleesbare bevestiging gekoppeld.':'Geen bericht gevonden met deze zoekopdracht; dit bewijst niet dat er geen reservering is.',references:proof.map(e=>e.reference),sources:candidates.map(m=>({id:m.id,subject:m.subject,url:m.url,at:m.at,documents:m.docs.map(d=>d.label),retiredTickets:(m.retiredLinks||[]).length,issues:m.issues})),fields:proof.map(e=>({reference:e.reference,provider:e.provider,start:e.start,end:e.end,name:e.name,capacity:e.capacity,occupants:e.occupants,product:e.product,document:e.document,source:e.source})),errors:sourceErrors};});
  return {checks,linked,messages:messages.length,documents:messages.reduce((n,m)=>n+m.docs.length,0),errors:errors.length+(limited?1:0),cancellations,retiredLinks:[...retired],fingerprint:hash(b),trip:String(b.index)};
 }
 async function save(result){for(let retry=0;retry<5;retry++){const {state,revision}=await readState(),b=currentBookings(state.bookings).find(b=>String(b.index)===result.trip);if(!b||hash(b)!==result.fingerprint)throw Error('Boeking is tijdens de controle gewijzigd; voer opnieuw uit.');for(const e of state.evidence)if(e.ticketLink&&result.retiredLinks.includes(e.ticketLink))e.status='cancelled';
  for(const c of result.cancellations){rememberCancellation(state,c);for(const e of state.evidence)if(e.provider===c.provider&&e.reference===c.reference&&(!e.observedAt||e.observedAt<=c.at)){e.status='cancelled';e.source=c.source;e.observedAt=c.at;}}
  (state.emailChecks??={})[result.trip]={at:stamp(),parserVersion:INTERPRETATION_VERSION,stays:result.checks};const ids=new Set(result.linked.map(e=>e.id)),refs=new Set(result.linked.map(e=>e.provider+'|'+e.reference));state.evidence=state.evidence.filter(e=>!ids.has(e.id)&&!(e.automaticEmail&&e.trip===result.trip&&refs.has(e.provider+'|'+e.reference))).concat(result.linked.map(e=>{const old=state.evidence.find(x=>x.id===e.id);return {...latestReservationState(state,e.partialEvidence&&old&&!old.partialEvidence&&old.start===e.start?old:e),importedAt:stamp(),automaticEmail:true};}));Object.assign(state,evaluate(state,stamp(),{trips:new Set([result.trip])}));try{await writeState(state,revision);return;}catch(e){if(e.status!==409||retry===4)throw e;}}}
 async function discover(get,job,progress){
  const watermark=await read('discovery');const from=job.discoveryFrom||(watermark.value.at?new Date(Date.parse(watermark.value.at)-7*86400000).toISOString().slice(0,10):new Date(clock()-90*86400000).toISOString().slice(0,10));
  job.discoveryFrom=from;job.discoveryErrors??=0;let page=job.discoveryPage||'';
  do{job.phase='Mailbox doorzoeken op niet-gekoppelde reserveringen (ondersteunde leveranciers)';await progress();const list=await get('messages',{q:'after:'+from+' {from:expediataap.nl from:nsinternational.nl from:oebb.at from:finnlines.com from:whitbread.com from:premierinn.com from:hotelabc.ch from:postchur.ch from:lhotel-montpellier.com from:teldartravel.com from:ratehawk.com from:bernerhof-interlaken.ch from:hotel-federale.ch} -in:spam -in:trash',maxResults:'20',...(page?{pageToken:page}:{})});
   for(const {id} of list.messages||[]){const cache=await read('message:'+id);let m=cache.value;try{if(needsRead(m)){m=await extract(await get('messages/'+id,{format:'full'}),get);m.version=5;await write('message:'+id,m,cache.revision);}const proofs=m.docs.map(d=>parseDocument(d,m)).filter(Boolean),cancel=cancellation(m);
    for(let retry=0;retry<4;retry++){const {state,revision}=await readState(),bookings=currentBookings(state.bookings);const changed=new Set();
     if(cancel)rememberCancellation(state,cancel);
     if(cancel)for(const e of state.evidence)if(e.provider===cancel.provider&&e.reference===cancel.reference&&(!e.observedAt||e.observedAt<=cancel.at)){e.status='cancelled';e.source=cancel.source;e.observedAt=cancel.at;changed.add(e.trip||'onbekend');}
     for(const proof of proofs){const e=latestReservationState(state,proof);if(e.end<stamp().slice(0,10))continue;const linked=resolveEvidence(e,bookings);const previous=state.evidence.find(x=>x.id===linked.id);if(previous&&!previous.partialEvidence&&linked.partialEvidence&&previous.start===linked.start||previous?.observedAt>=linked.observedAt&&!(previous.partialEvidence&&!linked.partialEvidence))continue;if(linked.trip&&state.emailChecks)delete state.emailChecks[linked.trip];state.evidence=state.evidence.filter(x=>x.id!==linked.id).concat({...linked,automaticEmail:true,importedAt:stamp()});changed.add(linked.trip||'onbekend');}
     if(changed.size)Object.assign(state,evaluate(state,stamp(),{trips:changed}));state.emailDiscovery={from,checkedAt:stamp(),coverage:'Expedia TAAP, NS International, ÖBB, Finnlines, Premier Inn, Hotel ABC, Post Chur, Best Western Montpellier, Teldar, RateHawk, Bernerhof en Federale. Andere afzenders alleen via boekingsgerichte zoekopdrachten.'};try{await writeState(state,revision);break;}catch(e){if(e.status!==409||retry===3)throw e;}}
    job.discoveryMessages=(job.discoveryMessages||0)+1;
   }catch{job.errors++;job.discoveryErrors++;}await progress();}
   page=list.nextPageToken||'';job.discoveryPage=page;await progress();
  }while(page);
  if(!job.discoveryErrors){const latest=await read('discovery');await write('discovery',{at:job.startedAt},latest.revision);}
 }
 async function checkUnlinkedCancellations(get,job,progress){
  const snapshot=await readState(),refs=[...new Set(snapshot.state.evidence.filter(e=>!e.trip&&e.status==='confirmed').map(e=>String(e.reference||'').split('/')[0]).filter(r=>/^[A-Za-z0-9-]{5,40}$/.test(r)))];
  for(let offset=0;offset<refs.length;offset+=20){let page='',count=0;do{
   job.phase='Annuleringen zoeken bij reserveringen zonder gekoppelde reis';await progress();
   const list=await get('messages',{q:'{'+refs.slice(offset,offset+20).map(r=>'"'+r+'"').join(' ')+'} {subject:annuleringsbevestiging subject:cancellation subject:stornierung subject:refund} -in:spam -in:trash',maxResults:'100',...(page?{pageToken:page}:{})});
   for(const {id} of list.messages||[]){const cached=await read('message:'+id);let m=cached.value;if(needsRead(m)){m=await extract(await get('messages/'+id,{format:'full'}),get);m.version=5;await write('message:'+id,m,cached.revision);}const c=cancellation(m);job.messages++;if(!c){job.errors++;continue;}for(let retry=0;retry<5;retry++){const {state,revision}=await readState();rememberCancellation(state,c);const changed=new Set();for(const e of state.evidence)if(e.provider===c.provider&&e.reference===c.reference&&(!e.observedAt||e.observedAt<=c.at)){e.status='cancelled';e.source=c.source;e.observedAt=c.at;changed.add(e.trip||'onbekend');}if(changed.size)Object.assign(state,evaluate(state,stamp(),{trips:changed}));try{await writeState(state,revision);break;}catch(e){if(e.status!==409||retry===4)throw e;}}await progress();}
   count+=(list.messages||[]).length;page=list.nextPageToken||'';if(count>=200&&page){job.errors++;break;}
  }while(page);}
  job.unlinkedCancellationsChecked=true;await progress();
 }
 async function updateOutcome(job){const {state}=await readState(),current=new Map(state.findings.map(f=>[f.id,f])),baseline=(job.baseline||[]).filter(f=>f.status==='attention');job.outcome={selected:baseline.length,reviewed:baseline.filter(f=>job.queue.slice(0,job.done).includes(f.id.split(':')[0])).length,resolved:baseline.filter(f=>!current.has(f.id)||current.get(f.id).status==='checked').length,remaining:baseline.filter(f=>current.get(f.id)?.status==='attention').length,reclassified:baseline.filter(f=>current.has(f.id)&&(current.get(f.id).priority!==f.priority||current.get(f.id).status!==f.status)).length,alarms:state.findings.filter(f=>job.queue.includes(f.trip)&&f.status==='alarm').length};}
 async function reassess(job,progress){
  while(job.done<job.queue.length){
   const batch=job.queue.slice(job.done,job.done+10),trips=new Set(batch);job.current=batch.join(', ');job.phase='Opgeslagen bewijs opnieuw beoordelen: '+batch.map(t=>t+'A').join(', ');await progress();
   const snapshot=await readState(),ids=new Set(snapshot.state.evidence.filter(e=>trips.has(e.trip||'onbekend')).map(e=>e.messageId).filter(Boolean));
   for(const trip of batch)for(const stay of snapshot.state.emailChecks?.[trip]?.stays||[])for(const m of stay.sources||[])ids.add(m.id);
   const messages=[];for(const id of ids){const cached=await read('message:'+id);if(cached.value.docs)messages.push(cached.value);}
   for(let retry=0;retry<5;retry++){const fresh=await readState();rebuildStoredEvidence(fresh.state,messages,stamp(),{trips});try{await writeState(fresh.state,fresh.revision);break;}catch(e){if(e.status!==409||retry===4)throw e;}}
   job.done+=batch.length;job.documents+=messages.reduce((n,m)=>n+m.docs.length,0);await updateOutcome(job);await progress();
  }
 }
 async function tick(){if(running)return;running=true;let owner,job;
  try{const stored=await read('job');job=stored.value;if(!['queued','running'].includes(job.status)||job.status==='running'&&job.lease>clock())return;owner=randomUUID();job.owner=owner;job.lease=clock()+300000;job.status='running';job.updatedAt=stamp();let revision=await write('job',job,stored.revision);const get=job.mode==='rules-only'?null:await google.reader();
   const progress=async()=>{job.updatedAt=stamp();job.lease=clock()+300000;revision=await write('job',job,revision);};
   if(job.mode==='rules-only'){if(job.parserVersion!==INTERPRETATION_VERSION)job.done=0;job.parserVersion=INTERPRETATION_VERSION;await reassess(job,progress);}
   const initial=await readState();if(job.mode!=='rules-only'&&job.mode!=='attention'&&initial.state.interpretationVersion!==INTERPRETATION_VERSION){
    const ids=new Set((initial.state.evidence||[]).map(e=>e.messageId).filter(Boolean));for(const c of Object.values(initial.state.emailChecks||{}))for(const t of c.stays||[])for(const m of t.sources||[])ids.add(m.id);
    const messages=[];let processed=0;for(const id of ids){const cached=await read('message:'+id);if(cached.value.docs)messages.push(cached.value);if(++processed%50===0){job.phase='Opgeslagen bronnen opnieuw beoordelen: '+processed+' van '+ids.size;job.updatedAt=stamp();job.lease=clock()+300000;revision=await write('job',job,revision);}}
    for(let retry=0;retry<5;retry++){const fresh=await readState();rebuildStoredEvidence(fresh.state,messages,stamp());try{await writeState(fresh.state,fresh.revision);break;}catch(e){if(e.status!==409||retry===4)throw e;}}
   }
   if(job.parserVersion!==INTERPRETATION_VERSION){const fresh=await readState();const alarms=new Set(fresh.state.findings.filter(f=>f.status==='alarm').map(f=>String(f.trip)));job.previousPass={version:job.parserVersion,done:job.done,messages:job.messages,documents:job.documents};job.queue=mailPlan(fresh.state,job.pilot,stamp(),job.mode).sort((a,b)=>Number(alarms.has(b))-Number(alarms.has(a)));job.done=0;job.parserVersion=INTERPRETATION_VERSION;job.phase='Bijgestelde regels: open alarmen eerst opnieuw controleren';revision=await write('job',job,revision);}
   if(!job.pilot&&!['attention','rules-only'].includes(job.mode)&&!job.unlinkedCancellationsChecked)await checkUnlinkedCancellations(get,job,progress);
   while(job.done<job.queue.length){const trip=job.queue[job.done];job.phase='Boeking '+trip+'A: berichten en tickets lezen';job.current=trip;job.updatedAt=stamp();job.lease=clock()+300000;revision=await write('job',job,revision);const {state}=await readState(),b=currentBookings(state.bookings).find(b=>String(b.index)===trip);if(!b)throw Error('Boeking niet meer aanwezig in Sanity-selectie.');const result=await processBooking(b,get,job,async({processed,total})=>{job.phase='Boeking '+trip+'A: bericht '+processed+' van '+total+' verwerken';job.updatedAt=stamp();job.lease=clock()+300000;revision=await write('job',job,revision);},state.evidence,currentBookings(state.bookings));await save(result);job.done++;job.messages+=result.messages;job.documents+=result.documents;job.errors+=result.errors;job.lastIssues=result.checks.flatMap(c=>c.errors.map(e=>({trip,detail:e.detail}))).slice(0,5);await updateOutcome(job);console.info('[FloRA]',JSON.stringify({run:job.id,mode:job.mode,trip,done:job.done,total:job.queue.length,messages:result.messages,errors:result.errors,outcome:job.outcome}));job.updatedAt=stamp();revision=await write('job',job,revision);}
   if(!job.pilot&&!['attention','rules-only'].includes(job.mode))await discover(get,job,progress);
   await updateOutcome(job);
   job.status=job.errors?'partial':'completed';job.phase=job.mode==='rules-only'?'Opgeslagen bewijs opnieuw beoordeeld; geen nieuwe e-mails opgehaald.':job.errors?'Afgerond met onvolledige bronnen; bekijk de details.':'Zoekronde afgerond; bekijk de inhoudelijke resultaten per overnachting.';job.finishedAt=stamp();delete job.owner;delete job.lease;await write('job',job,revision);for(let retry=0;retry<4;retry++){const {state,revision:r}=await readState();state.audit.push({at:stamp(),user:'FloRA',action:job.mode==='rules-only'?'Aandachtspunten opnieuw beoordeeld':job.mode==='attention'?'E-mailcontrole aandachtspunten':'E-mailcontrole '+(job.pilot?'voorbeeldboekingen':'afgerond'),detail:JSON.stringify(job.outcome)+'. '+job.done+' boekingen, '+job.messages+' berichten, '+job.documents+' documenten, '+job.errors+' onvolledige bronnen. Zie Boekingen voor zoekopdrachten en bewijs.'});if(!job.errors&&!['attention','rules-only'].includes(job.mode))state.emailCheckpoint={at:job.startedAt,finishedAt:stamp(),pilot:job.pilot};try{await writeState(state,r);break;}catch(e){if(e.status!==409||retry===3)throw e;}}
   // Finish an in-flight older run first, then revisit its bookings with the corrected interpretation.
   if(job.parserVersion!==INTERPRETATION_VERSION)await start({pilot:job.pilot,mode:'parser-upgrade'});
  }catch(e){if(job?.id){try{const latest=await read('job');if(latest.value.owner===owner)await write('job',{...latest.value,status:'failed',phase:e.message,updatedAt:stamp()},latest.revision);}catch{}}}finally{running=false;}
 }
 return {status,start,tick,processBooking};
}
export const floraMail=createMailControl();
export function startFloraMail(){setTimeout(()=>void floraMail.tick(),20000).unref();setInterval(()=>void floraMail.tick(),30000).unref();}
