import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createGoogle,GMAIL_SCOPE,decryptGoogle} from './flora-google.mjs';
import {initFlora,readFlora,readFloraGoogle,writeFloraGoogle} from './flora-store.mjs';
import {createFloraHandler} from './flora.mjs';
import {Readable} from 'node:stream';
function fixture(extra={}){let value={},revision=0,time=10000;const calls=[];const config={id:'client',secret:'secret',origin:'https://example.com'};const fetcher=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>url.includes('/token')?{access_token:'access',refresh_token:'refresh',scope:GMAIL_SCOPE}:{emailAddress:'reservations@treinrondreis.nl'}};};const deps={configuration:()=>config,read:async()=>({value:structuredClone(value),revision}),write:async(v,r)=>{assert.equal(r,revision);value=structuredClone(v);return ++revision;},fetcher,now:()=>time,...extra};return {google:createGoogle(deps),calls,config,deps,value:()=>value,expire:()=>{time+=600001;}};}
async function start(f){return new URL(await f.google.start('session')).searchParams;}
test('OAuth requests only read scope with PKCE, offline access and fixed redirect; token is encrypted',async()=>{const f=fixture(),p=await start(f);assert.equal(p.get('scope'),GMAIL_SCOPE);assert.equal(p.get('access_type'),'offline');assert.equal(p.get('code_challenge_method'),'S256');assert.equal(p.get('redirect_uri'),'https://example.com/seinhuis/flora/google/callback');assert.ok(p.get('state'));await f.google.callback(new URLSearchParams({state:p.get('state'),code:'code'}),'session');assert.equal((await f.google.status()).connected,true);assert.equal(JSON.stringify(f.value()).includes('refresh'),false);assert.equal(decryptGoogle(f.value().credentials,'secret').refresh,'refresh');assert.equal(f.value().pending,undefined);assert.equal(JSON.stringify(await f.google.status()).includes('credentials'),false);await createGoogle(f.deps).test();assert.equal(f.calls.filter(c=>c.url.includes('/token')).length,2);assert.equal(new URLSearchParams(f.calls.at(-2).options.body).get('grant_type'),'refresh_token');});
test('state rejects wrong session, expiry, missing state and replay before contacting Google',async()=>{for(const mode of ['session','expiry','missing']){const f=fixture(),p=await start(f);if(mode==='expiry')f.expire();await assert.rejects(f.google.callback(new URLSearchParams({state:mode==='missing'?'':p.get('state'),code:'code'}),mode==='session'?'other':'session'));assert.equal(f.calls.length,0);}const f=fixture(),p=await start(f),args=new URLSearchParams({state:p.get('state'),code:'code'});await f.google.callback(args,'session');await assert.rejects(f.google.callback(args,'session'));assert.equal(f.calls.length,2);});
test('wrong mailbox, write scope, missing refresh and denied consent never connect',async()=>{for(const mode of ['mailbox','scope','refresh','denied']){const f=fixture({fetcher:async url=>({ok:true,json:async()=>url.includes('/token')?{access_token:'access',scope:mode==='scope'?GMAIL_SCOPE+' https://www.googleapis.com/auth/gmail.modify':GMAIL_SCOPE,...(mode==='refresh'?{}:{refresh_token:'refresh'})}:{emailAddress:mode==='mailbox'?'wrong@example.com':'reservations@treinrondreis.nl'}})});const p=await start(f);await assert.rejects(f.google.callback(new URLSearchParams({state:p.get('state'),...(mode==='denied'?{error:'access_denied'}:{code:'code'})}),'session'));assert.equal((await f.google.status()).connected,false);}});
test('Google failure does not expose response tokens; disabled configuration does not need storage',async()=>{const f=fixture({fetcher:async()=>({ok:false,status:400,json:async()=>({secret:'secret'})})}),p=await start(f);await assert.rejects(f.google.callback(new URLSearchParams({state:p.get('state'),code:'code'}),'session'),e=>!e.message.includes('secret'));const disabled=createGoogle({configuration:()=>({}),read:()=>{throw Error('unexpected');}});assert.equal((await disabled.status()).configured,false);});
test('temporary Gmail quota errors are retried without writing messages',async()=>{let attempts=0;const waits=[];const f=fixture({pause:async ms=>waits.push(ms),fetcher:async url=>{if(url.includes('/token'))return {ok:true,json:async()=>({access_token:'a',refresh_token:'r',scope:GMAIL_SCOPE})};if(++attempts<3)return {ok:false,status:429,json:async()=>({error:{status:'RESOURCE_EXHAUSTED'}})};return {ok:true,json:async()=>({emailAddress:'reservations@treinrondreis.nl'})};}}),p=await start(f);await f.google.callback(new URLSearchParams({state:p.get('state'),code:'code'}),'session');assert.equal(attempts,3);assert.deepEqual(waits,[5000,10000]);});
test('private credentials persist independently of public state and reject stale writes',async()=>{const sqlite=new DatabaseSync(':memory:');await initFlora({sqlite});assert.equal((await readFloraGoogle()).revision,0);await writeFloraGoogle({credentials:'encrypted'},0);assert.equal((await readFloraGoogle()).value.credentials,'encrypted');assert.equal(JSON.stringify(await readFlora()).includes('encrypted'),false);await assert.rejects(writeFloraGoogle({},0));sqlite.close();});
test('Google endpoints require login and same-origin POST; callback binds only the admin session',async()=>{let authenticated=true,starts=0,session;const handler=createFloraHandler({authenticate:async()=>authenticated,google:{start:async s=>{starts++;session=s;return 'https://accounts.google.com/test';},callback:async(p,s)=>{session=s;}}});async function call(path,method='POST',headers={}){const req=Readable.from(['{}']);req.method=method;req.headers={origin:'https://treinbord.up.railway.app','x-flora':'1','content-type':'application/json',cookie:'other=one; tr_admin_session=abc',...headers};let status,body,location;const res={setHeader(){},writeHead(s,h){status=s;location=h?.Location;},end(b){body=b;}};await handler(req,res,new URL('https://treinbord.up.railway.app/seinhuis/flora/'+path));return {status,body,location};}authenticated=false;assert.equal((await call('api/google/start')).status,401);authenticated=true;assert.equal((await call('api/google/start','POST',{origin:'https://evil.test'})).status,403);assert.equal(starts,0);assert.equal((await call('api/google/start')).status,200);assert.equal(session,'tr_admin_session=abc');const result=await call('google/callback?state=test&code=private','GET',{cookie:'other=changed; tr_admin_session=abc'});assert.equal(session,'tr_admin_session=abc');assert.equal(result.status,303);assert.equal(result.location,'/seinhuis/flora/?gmail=connected');});

test('reader permits thread GETs while rejecting mutation and foreign paths',async()=>{const f=fixture(),p=await start(f);await f.google.callback(new URLSearchParams({state:p.get('state'),code:'code'}),'session');const get=await f.google.reader();await get('threads/abc123',{format:'minimal'});assert.match(f.calls.at(-1).url,/users\/me\/threads\/abc123\?format=minimal$/);assert.equal(f.calls.at(-1).options.method,undefined);for(const path of ['messages/send','threads/abc/modify','https://evil.test','../threads/abc']){if(path==='messages/send')continue;await assert.rejects(get(path),/Ongeldig Gmail/);}});
