const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,selected,importFile,preview,rulePreview;const filterKeys=['search','status','code','type','provider','country','priority','sort','followup'];
const repeats=f=>f.status==='alarm'||f.status==='attention'&&['missing','waiting'].includes(f.code);
const localTime=s=>new Date(s).toLocaleString('nl-NL',{timeZone:'Europe/Amsterdam'});
const labels={alarm:'ALARM',attention:'Aandachtspunt',checked:'✓ Gecontroleerd'};
async function api(path,body){const r=await fetch('/seinhuis/flora/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Flora':'1'},body:JSON.stringify({...body,revision:data.revision})}:{}),d=await r.json();if(!r.ok)throw Error(d.error||'Verzoek mislukt');return d;}
async function busy(fn){try{$('#notice').textContent='Bezig…';await fn();$('#notice').textContent='Opgeslagen.';$('#notice').className='';}catch(e){$('#notice').textContent=e.message;$('#notice').className='error';$('#dialogstatus').textContent=e.message;}}
async function load(){data=await api('state');const c=data.connection;$('#connection').innerHTML=`<span><b>Sanity</b> · ${c.sanityConfigured?'Token ingesteld':'Viewer-token nog instellen'}</span><span><b>Laatste synchronisatie</b> · ${esc(c.lastSync?new Date(c.lastSync).toLocaleString('nl-NL'):'Nog niet uitgevoerd')}</span><span><b>E-mail</b> · ${esc(c.email)}</span>${c.syncError?'<strong class="error">'+esc(c.syncError)+'</strong>':''}${c.lastSync&&data.schedule?.overdue?'<strong class="error">De geplande controle is nog niet voltooid.</strong>':''}`;$('#schedule').innerHTML=`<b>${esc(data.schedule.label)}</b> · ${c.sanityConfigured?'Volgende controle: '+esc(localTime(data.schedule.next)):'Wacht op Sanity-koppeling'}<br>Verder vanaf: ${esc(data.schedule.lastRun?localTime(data.schedule.lastRun):'de eerste controle')}. Nieuwe/gewijzigde boekingen en open hercontroles. Naamafwijkingen alleen bij wijziging.`;for(const k of ['code','type','provider','country','priority']){const v=$('#'+k).value;$('#'+k).innerHTML='<option value="">Alle</option>'+[...new Set(data.state.findings.map(f=>f[k==='code'?'category':k]))].sort().map(v=>`<option>${esc(v)}</option>`).join('');$('#'+k).value=v;}$('#namerule').value=data.state.rules.partialNames;render();renderBookings();$('#historylist').innerHTML=[...data.state.audit].reverse().map(a=>`<div class="historyitem"><b>${esc(a.action)}</b> · ${esc(a.detail)}<p class="muted">${esc(new Date(a.at).toLocaleString('nl-NL'))} · ${esc(a.user)}</p></div>`).join('')||'<p>Nog geen handelingen.</p>';$('#historylist').innerHTML+='<h3>Opgeloste meldingen</h3>'+(data.state.archived||[]).slice().reverse().map(f=>'<details><summary>'+esc(f.trip)+'A · '+esc(f.title)+' · '+esc(f.resolvedAt.slice(0,10))+'</summary><p>'+esc(f.detail)+'</p>'+f.history.map(h=>'<p>'+esc(h.user)+' · '+esc(h.reason)+'</p>').join('')+'</details>').join('');}
function render(){const all=data.state.findings;$('#metrics').innerHTML=`<div class="metric red">ALARM<strong>${all.filter(f=>f.status==='alarm').length}</strong></div><div class="metric amber">Aandachtspunten<strong>${all.filter(f=>f.status==='attention').length}</strong></div><div class="metric green">Volledig gecontroleerde boekingen<strong>${data.state.summary.filter(b=>b.checked).length}</strong></div>`;const q=$('#search').value.toLowerCase(),status=$('#status').value;const rows=all.filter(f=>(!$('#followup').value||($('#followup').value==='weekly'?repeats(f):!repeats(f)))&&(status==='open'?f.status!=='checked':!status||f.status===status)&&['code','type','provider','country','priority'].every(k=>!$('#'+k).value||f[k==='code'?'category':k]===$('#'+k).value)&&JSON.stringify(f).toLowerCase().includes(q));const sort=$('#sort').value;rows.sort((a,b)=>sort==='priority'?(['alarm','attention','checked'].indexOf(a.status)-['alarm','attention','checked'].indexOf(b.status))||a.departure.localeCompare(b.departure):String(a[sort]||'9999').localeCompare(String(b[sort]||'9999')));$('#count').textContent=rows.length+' meldingen';$('#results').innerHTML=rows.map(f=>`<article class="finding ${esc(f.status)}"><div><span class="badge ${esc(f.status)}">${labels[f.status]}</span><small>${esc(f.priority)} prioriteit</small><small>${repeats(f)?'Wekelijkse hercontrole':'Alleen bij wijziging'}</small></div><div><h3>${esc(f.title)}</h3><div class="meta">${esc(f.trip)}A · ${esc(f.name)} · ${esc(f.departure)}</div><p>${esc(f.stay)}</p><div class="meta">${esc(f.provider)} · ${esc(f.country)} · ${esc(f.reference)}</div></div><button data-detail="${esc(f.id)}">Bekijken →</button></article>`).join('')||`<div class="empty">${data.state.bookings.length?'Geen meldingen binnen deze filters.':'Lees eerst Sanity in. Er zijn nog geen boekingen gecontroleerd.'}</div>`;}
function renderBookings(){const q=$('#bookingsearch').value.toLowerCase();$('#bookinglist').innerHTML=data.state.summary.filter(b=>JSON.stringify(b).toLowerCase().includes(q)).map(b=>{const booking=data.state.bookings.find(x=>String(x.index)===b.trip&&x._id.startsWith('drafts.'))||data.state.bookings.find(x=>String(x.index)===b.trip);return `<details><summary><span class="badge ${b.checked?'checked':''}">${b.checked?'✓ Gecontroleerd':b.alarms?'ALARM':'Open'}</span> <b>${esc(b.trip)}A · ${esc(b.name)}</b> · ${esc(b.departure)} · ${b.overnights} overnachtingen</summary><p>Status: ${esc(b.status)}</p><p><b>Boekingsnotities:</b> ${esc(booking?.notes||'Geen')}</p><div class="scroll"><table><tr><th>Todo</th><th>Datums</th><th>Todo-sleutel voor import</th><th>Notitie</th></tr>${(booking?.todos||[]).filter(t=>t.tag==='hotel').map(t=>`<tr><td>${esc(t.title)}</td><td>${esc(t.startDate)} – ${esc(t.endDate)}</td><td>${esc(t._key)}</td><td>${esc(t.description)}</td></tr>`).join('')}</table></div></details>`;}).join('')||'<p>Nog geen boekingen.</p>';}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==tab.dataset.tab);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===tab));}const detail=e.target.closest('[data-detail]');if(detail){selected=data.state.findings.find(f=>f.id===detail.dataset.detail);$('#dialogstatus').textContent='';$('#reason').value='';$('#deferbox').hidden=selected.code!=='waiting';$('#detailbody').innerHTML=`<span class="badge ${esc(selected.status)}">${labels[selected.status]}</span><h2>${esc(selected.title)}</h2><p>${esc(selected.trip)}A · ${esc(selected.name)}</p><h3>${esc(selected.stay)}</h3><p>${esc(selected.detail)}</p><p class="muted">Automatisch: ${esc(labels[selected.automatic])} · Eerst gezien ${esc(selected.firstSeen.slice(0,10))} · Laatst gecontroleerd ${esc(localTime(selected.lastChecked))}${selected.nextCheck?' · Hercontrole '+esc(selected.nextCheck):''}</p><h3>Bewijs</h3>${selected.evidence.map(e=>`<p>${esc(e.source)} · ${esc(e.reference)}<br>${esc(e.start)} – ${esc(e.end)} · ${esc(e.name)}<br>${esc(e.capacity??'?')} slaapplaatsen · ${esc(e.occupants??'?')} personen · ${esc(e.status)}</p>`).join('')||'<p>Nog geen gekoppeld bewijs.</p>'}<h3>Beoordelingen</h3>${selected.history.map(h=>`<p>${esc(h.at)} · ${esc(h.user)} · ${esc(h.status)}<br>${esc(h.reason)}</p>`).join('')||'<p>Nog geen handmatige beoordeling.</p>'}`;$('#detail').showModal();}});
for(const k of filterKeys)$('#'+k).addEventListener(k==='search'?'input':'change',render);$('#bookingsearch').oninput=renderBookings;
$('#sync').onclick=()=>busy(async()=>{await api('sync',{});await load();});$('#check').onclick=()=>busy(async()=>{await api('check',{});await load();});
$('#review').onclick=()=>busy(async()=>{await api('review',{id:selected.id,status:$('#reviewstatus').value,reason:$('#reason').value});$('#detail').close();await load();});
$('#defer').onclick=()=>busy(async()=>{await api('defer',{trip:selected.trip,until:$('#until').value,reason:$('#reason').value});$('#detail').close();await load();});
$('#file').onchange=()=>busy(async()=>{const f=$('#file').files[0];preview=null;$('#commitimport').hidden=true;if(!f)return;if(f.size>3*1024*1024)throw Error('Maximaal 3 MB per bestand.');importFile={name:f.name,format:f.name.endsWith('.csv')?'csv':'json',content:await f.text()};preview=await api('import-preview',importFile);$('#importmessage').textContent=preview.message;$('#preview').innerHTML='<table><tr><th>Reis</th><th>Bron / referentie</th><th>Datums</th><th>Personen / plaatsen</th><th>Status</th></tr>'+preview.rows.map(r=>`<tr><td>${esc(r.trip)}A<br>${esc(r.todoKey)}</td><td>${esc(r.provider)}<br>${esc(r.reference)}</td><td>${esc(r.start)} – ${esc(r.end)}</td><td>${esc(r.occupants??'?')} / ${esc(r.capacity??'?')}</td><td>${esc(r.status)}</td></tr>`).join('')+'</table>';$('#commitimport').hidden=false;});
$('#commitimport').onclick=()=>busy(async()=>{await api('import',{...importFile,digest:preview.digest});$('#commitimport').hidden=true;$('#importmessage').textContent='Import opgeslagen en gecontroleerd.';await load();});
$('#template').onclick=()=>{const text='trip,todoKey,provider,reference,status,start,end,name,capacity,occupants,country,source,productMatch,group,direction,originCountry,roomMismatch\n';const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='flora-import.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#namerule').onchange=()=>{$('#saverules').hidden=true;rulePreview=null;};$('#testrules').onclick=()=>busy(async()=>{rulePreview=await api('rules-preview',{partialNames:$('#namerule').value});$('#ruletest').textContent=`Testresultaat: ${rulePreview.alarms} alarmen, ${rulePreview.attention} aandachtspunten.`;$('#saverules').hidden=false;});$('#saverules').onclick=()=>busy(async()=>{await api('rules',{partialNames:$('#namerule').value,digest:rulePreview.digest});$('#saverules').hidden=true;await load();});
let views=[];try{views=JSON.parse(localStorage.getItem('flora-views')||'[]');}catch{}function showViews(){$('#views').innerHTML='<option value="">Bewaarde filters</option>'+views.map((v,i)=>`<option value="${i}">${esc(v.name)}</option>`).join('');}showViews();$('#saveview').onclick=()=>{const name=prompt('Naam voor dit filter');if(!name)return;views.push({name,values:Object.fromEntries(filterKeys.map(k=>[k,$('#'+k).value]))});try{localStorage.setItem('flora-views',JSON.stringify(views));showViews();}catch{$('#notice').textContent='Filter kon niet op dit apparaat worden bewaard.';}};$('#views').onchange=()=>{const v=views[$('#views').value];if(v){for(const k of filterKeys)$('#'+k).value=v.values[k]||'';render();}};
load().catch(e=>{$('#notice').textContent=e.message;$('#notice').className='error';});
