import test from 'node:test';
import assert from 'node:assert/strict';
import {parseNSTrains,connectionCandidates} from './flora-trains-parser.mjs';
import {createTrains} from './flora-trains.mjs';
const message={id:'mail',from:'no-reply@confirmation.nsinternational.nl',subject:'Bevestiging, naam: 42A, boekingscode: ABCDEFG',at:'2026-10-01',url:'https://mail.google.com/mail/u/0/#all/mail',docs:[{label:'NS-ticket',year:'2027',text:'DNR: ABCDEFG ID:2 VERVOERBEWIJS + RESERVERING CIV 1184 NIGHTJET TEST 02 VOLWASSENEN 23.02 20:12 WIEN MEIDLING -> UTRECHT CENTRAAL 24.02 09:29 TREIN 40490 NJ RIJTUIG 433'}]};
test('NS ticket yields explicit train, trip, dates and evidence; options and wrong trips excluded',()=>{const [r]=parseNSTrains(message,'42');assert.equal(r.number,'40490');assert.equal(r.trip,'42');assert.equal(r.date,'2027-02-23');assert.equal(r.arrivalDate,'2027-02-24');assert.equal(r.from,'WIEN MEIDLING');assert.equal(r.to,'UTRECHT CENTRAAL');assert.equal(r.source,message.url);assert.deepEqual(parseNSTrains(message,'43'),[]);assert.deepEqual(parseNSTrains({...message,subject:'Optieboeking 42A'},'42'),[]);assert.deepEqual(parseNSTrains({...message,subject:'Annulering 42A'},'42'),[]);});
test('connections contain trip and both train numbers and require a backup choice',()=>{const rows=[{id:'a',trip:'42',number:'100',to:'Dresden Hbf',arrivalDate:'2027-02-23',arrival:'12:00'},{id:'b',trip:'42',number:'200',from:'Dresden Hbf',date:'2027-02-23',departure:'12:30'}];const [c]=connectionCandidates(rows);assert.equal(c.trip,'42');assert.equal(c.arrivalTrain,'100');assert.equal(c.departureTrain,'200');assert.equal(c.station,'Dresden Hbf');assert.equal(c.backup,null);assert.equal(c.minutes,30);assert.equal(connectionCandidates([rows[0],{...rows[1],trip:'43'}]).length,0);assert.equal(connectionCandidates([rows[0],{...rows[1],from:'Berlin Hbf'}]).length,0);});
test('small scan uses newest NS dossier message only and does not change overnight state',async()=>{const kv=new Map(),extracted=[];const c=createTrains({read:async k=>structuredClone(kv.get(k)||{value:{},revision:0}),write:async(k,value,r)=>{kv.set(k,{value,revision:r+1});return r+1;},bookings:async()=>({state:{bookings:[{index:42}]}}),google:{status:async()=>({connected:true}),reader:async()=>async path=>path==='messages'?{messages:[{id:'old'},{id:'new'}]}:{id:path.split('/')[1],internalDate:path.endsWith('new')?'200':'100',payload:{headers:[{name:'Subject',value:message.subject}]}}},extract:async m=>{extracted.push(m.id);return {...message,issues:[]};}});await c.start(['42A']);await c.tick();assert.deepEqual(extracted,['new']);assert.equal((await c.status()).status,'completed');const d=await c.data();assert.equal(d.rows.length,1);assert.equal(d.rows[0].status,'Te beoordelen');await c.review({type:'train',id:d.rows[0].id,confirmed:true,revision:d.revision});assert.equal((await c.data()).rows[0].status,'Bevestigd');assert.equal(kv.has('job'),false);});

test('NS email reservation summary saves explicit train even without times',()=>{const docs=[{label:'E-mail',text:'Reisgegevens Bekijk de actuele route- en vertrekinformatie . Utrecht Centraal - Muenchen Hbf Vertrek: wo 21 okt 2026 Aankomst: wo 21 okt 2026 Met: OSDM Reservation as issuer Treinnummer: 225 Reizigers: 2 x Volwassene met tarief Zitplaatsreservering 2e klas Delft - Muenchen Hbf Vertrek: wo 21 okt 2026 Reizigers: 2 x Volwassene'}];const rows=parseNSTrains({...message,docs},'42');assert.equal(rows.length,1);assert.equal(rows[0].number,'225');assert.equal(rows[0].from,'Utrecht Centraal');assert.equal(rows[0].to,'Muenchen Hbf');assert.equal(rows[0].date,'2026-10-21');assert.equal(rows[0].departure,'');});
