import test from 'node:test';
import assert from 'node:assert/strict';
import {parseDocument,matchEvidence,cancellation,bookingQuery,roomCapacity} from './flora-mail-parser.mjs';
import {extractMessage,safeTicketURL,pdfText,ticket} from './flora-mail-source.mjs';
import {createMailControl,mailPlan,rememberCancellation,latestReservationState} from './flora-mail.mjs';
import {emptyState} from './flora-store.mjs';
import {evaluate} from './flora-engine.mjs';
import {rebuildStoredEvidence} from './flora-reconcile.mjs';
import {resolveEvidence} from './flora-mail-parser.mjs';

test('a shared hotel chain in another city does not become a wrong-date match',()=>{const booking=b();booking.todos[0].supplierBookingNumber='111111111';booking.todos[0].title='IntercityHotel Berlin Hauptbahnhof';const e={...parseDocument(mail().docs[0],mail()),reference:'222222222',product:'IntercityHotel Duisburg Mercatorstrasse'};assert.equal(matchEvidence(e,booking),null);const linked=resolveEvidence(e,[booking]);assert.equal(linked.trip,'6685');assert.equal(linked.todoKey,'');assert.ok(linked.linkReview);});

test('all Expedia rooms and children count, without borrowing occupancy from the trip',()=>{
 const m=mail();m.docs[0].text='Je boeking is bevestigd Boekingsdatums 13 jan 2027 - 15 jan 2027 Reisplannummer 123456789 Hoteloverzicht Test Hotel 12 Kamer 1 Gasten Geboekt voor Test Reiziger 1 volwassene, 1 kind Kamer Standaard Twin kamer Inbegrepen voorzieningen Ontbijt Kamervoorkeuren Niet roken Kamer 2 Gasten Geboekt voor Test Reiziger 2 volwassenen Kamer Double room Kamervoorkeuren Niet roken';
 const e=parseDocument(m.docs[0],m);assert.equal(e.capacity,4);assert.equal(e.occupants,4);assert.equal(e.roomCount,2);assert.equal(e.name,'Test Reiziger');
});
test('Expedia explicit changed itinerary supersedes old dates and room layout',()=>{
 const m=mail();m.docs[0].text='Verblijf bij Test Hotel Naar aanleiding van je verzoek hebben we je boeking gewijzigd. 13 jan. 2027 - 16 jan. 2027 | Reisplannummer 123456789 , 1 kamer | 3 nachten Je reservering is geboekt. Kamer Studio Inclusief: ontbijt 1 kingsize bed, rookvrije kamer Geboekt voor Test Reiziger 2 volwassenen';
 const e=parseDocument(m.docs[0],m);assert.equal(e.end,'2027-01-16');assert.equal(e.capacity,2);assert.equal(e.name,'Test Reiziger');
});
test('Expedia alternative cancellation wording is authoritative, cancellation policy is not',()=>{
 const m=mail();m.subject='TAAP Annuleringsbevestiging hotel';m.docs[0].text='Je hotelkamer is geannuleerd. TAAP-reisplannummer: 123456789';assert.equal(cancellation(m).reference,'123456789');m.docs[0].text='Je hotelkamer kan worden geannuleerd. TAAP-reisplannummer: 123456789';assert.equal(cancellation(m),null);
});
test('empty and placeholder passengers cannot match other bookings; explicit different trip remains blocked',()=>{
 const e=parseDocument(mail().docs[0],mail());e.reference='different';for(const p of [{firstName:null,lastName:null},{firstName:'a',lastName:'a'},{firstName:'nnb',lastName:'nnb'}]){const booking=b();booking.passengers=[p];assert.equal(matchEvidence({...e,name:'Other nnb'},booking),null);}
 const booking=b();assert.equal(matchEvidence({...e,tripHint:'6685',name:'Other Person'},booking),null);
});
test('NS BEDPLAATS counts actual berths',()=>{
 const e=parseDocument({label:'ticket.pdf',year:'2027',text:'DNR: ABCDEFG ID:0 VERVOERBEWIJS + RESERVERING NIGHTJET REIZIGER, TEST 02 VOLWASSENEN 13.01 18:00 UTRECHT CENTRAAL -> WIEN HBF 14.01 09:00 RIJTUIG 432 BEDPLAATS 61 62 DO 02 RIT'},mail());assert.equal(e.capacity,2);
});
test('cached source rebuild removes stale wrong links, retains cancellations and preserves prior evidence',()=>{
 const m=mail(),e={...matchEvidence(parseDocument(m.docs[0],m),b()),automaticEmail:true,capacity:1};const s={...emptyState(),bookings:[b()],evidence:[e]};rebuildStoredEvidence(s,[m],'2026-10-04T01:00:00Z');assert.equal(s.evidence[0].capacity,2);assert.equal(s.evidenceRevisions[0].evidence[0].capacity,1);
 const cancelled={...m,id:'cancel',at:'2026-10-04T00:00:00Z',subject:'TAAP Annuleringsbevestiging',docs:[{label:'E-mail',text:'Je hotelkamer is geannuleerd TAAP-reisplannummer: 123456789'}]};rebuildStoredEvidence(s,[m,cancelled]);assert.equal(s.evidence[0].status,'cancelled');
});
const b=()=>({_id:'x',index:6685,status:'te verwerken',dateDeparture:'2027-01-13',dateReturn:'2027-01-15',passengers:[{firstName:'Test',lastName:'Reiziger'}],todos:[{_key:'hotel',tag:'hotel',title:'Thon Hotel Bristol | Double',startDate:'2027-01-13',endDate:'2027-01-15',supplierBookingNumber:'123456789',done:true}]});
const mail=()=>({id:'abc',at:'2026-10-03T10:00:00Z',subject:'Reisbevestiging',from:'noreply@expediataap.nl',url:'https://mail.google.com/mail/u/0/#all/abc',issues:[],docs:[{label:'E-mail',text:'Itinerary: Thon Hotel Bristol Bedankt! Je boeking is bevestigd. Hoteloverzicht Thon Hotel Bristol Torgalmenningen 11 Boekingsdatums 13 jan 2027 - 15 jan 2027 Reisplannummer 123456789 Geboekt voor Test Reiziger 1 volwassenen Kamer Standaard tweepersoonskamer Kamervoorkeuren Niet roken Gratis annulering tot 13 jan 2027'}]});

test('old reservation references get a dedicated cancellation search before the general search',async()=>{const queries=[],cancel={...mail(),id:'old-cancel',subject:'TAAP Annuleringsbevestiging hotel',docs:[{label:'E-mail',text:'Je hotelkamer is geannuleerd. TAAP-reisplannummer: 987654321'}]};const control=createMailControl({read:async()=>({value:{},revision:0}),write:async()=>1,extract:async()=>cancel});const result=await control.processBooking(b(),async(path,args)=>{if(path==='messages'){queries.push(args.q);return {messages:args.q.includes('subject:annuleringsbevestiging')?[{id:'old-cancel'}]:[]};}return {};},{},async()=>{},[{trip:'6685',reference:'987654321'}]);assert.match(queries[0],/987654321/);assert.equal(result.cancellations[0].reference,'987654321');assert.equal(queries[1],bookingQuery(b()));});

test('an older in-flight scan replans alarm trips before continuing mailbox discovery',async()=>{const kv=new Map([['job',{value:{id:'old',parserVersion:5,status:'queued',queue:[],done:0,messages:0,documents:0,errors:0,pilot:true},revision:1}]]);let state={...emptyState(),interpretationVersion:6,bookings:[b(),{...b(),_id:'other',index:6677}],findings:[{trip:'6677',status:'alarm'}]};const order=[];const c=createMailControl({read:async k=>structuredClone(kv.get(k)||{value:{},revision:0}),write:async(k,value,r)=>{kv.set(k,{value:structuredClone(value),revision:r+1});return r+1;},readState:async()=>({state:structuredClone(state),revision:0}),writeState:async s=>{state=s;},google:{reader:async()=>async(path,args)=>{if(path==='messages')order.push(args.q);return {messages:[]};}}});await c.tick();assert.match(order[0],/6677/);assert.equal((await c.status()).done,2);assert.equal((await c.status()).parserVersion,6);});
test('beds count people, including alternative single beds',()=>{for(const text of ['Comfort kamer, 1 twee- of 2 eenpersoonsbedden','1 tweepersoonsbed','2 eenpersoonsbedden','Double room'])assert.equal(roomCapacity(text),2,text);assert.equal(roomCapacity('1 eenpersoonsbed'),1);assert.equal(roomCapacity('1 double bed and 1 single bed'),3);assert.equal(roomCapacity('single or double'),1);});
test('cancellation remembered before confirmation prevents resurrection but allows later rebooking',()=>{const state={},c={provider:'Expedia',reference:'123',at:'2026-10-02T10:00:00Z',source:'cancel'};rememberCancellation(state,c);rememberCancellation(state,{...c,at:'2026-10-01T10:00:00Z'});assert.equal(latestReservationState(state,{provider:'Expedia',reference:'123',status:'confirmed',observedAt:'2026-10-01T10:00:00Z'}).status,'cancelled');assert.equal(latestReservationState(state,{provider:'Expedia',reference:'123',status:'confirmed',observedAt:'2026-10-03T10:00:00Z'}).status,'confirmed');assert.equal(latestReservationState(state,{provider:'Expedia',reference:'456',status:'confirmed',observedAt:'2026-10-01T10:00:00Z'}).status,'confirmed');});
test('explicit supplier cancellations use booking reference, not cancellation number or policy',()=>{const m={...mail(),subject:'TAAP Annuleringsbevestiging hotel',docs:[{label:'E-mail',text:'Je hebt geannuleerd met een volledige restitutie. TAAP-reisplannummer: 123456789'}]};assert.equal(cancellation(m).reference,'123456789');m.docs[0].text='Gratis annulering tot morgen';assert.equal(cancellation(m),null);m.from='donotreply@picomms.premierinn.com';m.subject='Premier Inn Stornierung';m.docs[0].text='Buchung storniert Stornierungsnummer XYZ123 Buchungsnummer WAA123456 Check-in 28. Dezember 2026 - ab 15 Uhr Check-out 2. Januar 2027 - bis 12 Uhr';assert.equal(cancellation(m).reference,'WAA123456');assert.equal(parseDocument(m.docs[0],m).status,'cancelled');assert.equal(parseDocument(m.docs[0],m).end,'2027-01-02');});
test('direct hotel confirmation can adopt one quoted request, never an offer or quoted confirmation',()=>{const request=' Arrival date: 05 Dec 2026 Departure date: 06 Dec 2026 Customer name: Test Reiziger Rooms: 1 x Double room Persons: Test Reiziger (01 Jan 1980) Other Reiziger (02 Jan 1980) Our reference: 6685A';const m={...mail(),from:'info@bernerhof-interlaken.ch',subject:'AW: New reservation request nr 6685A',docs:[{label:'E-mail',text:'Good morning, We confirm double room standard for this one. HCN: 12345 Best regards Hotel Bernerhof Von: Reservations'+request}]};const e=parseDocument(m.docs[0],m);assert.equal(e.reference,'12345');assert.equal(e.capacity,2);assert.equal(e.occupants,2);assert.equal(e.start,'2026-12-05');for(const head of ['We cannot confirm this booking.','We can confirm, shall we book?','Thank you.','We confirm a different date.']){m.docs[0].text=head+' Best regards Hotel Bernerhof Von: We confirm this booking.'+request;assert.equal(parseDocument(m.docs[0],m),null,head);}m.from='reservations@treinrondreis.nl';m.docs[0].text='We confirm this booking.'+request;assert.equal(parseDocument(m.docs[0],m),null);m.from='info@hotel-federale.ch';m.docs[0].text='Reservation No. 6685A has been confirmed. Best regards Hotel Federale Da: Reservations'+request;assert.equal(parseDocument(m.docs[0],m).provider,'Hotel Federale');});
test('a later cancellation removes only its reservation from active evidence',async()=>{const messages=[mail(),{...mail(),id:'cancel',at:'2026-10-04T10:00:00Z',subject:'TAAP Annuleringsbevestiging hotel',docs:[{label:'E-mail',text:'Je hebt geannuleerd. TAAP-reisplannummer: 123456789'}]}];const cache=new Map(),control=createMailControl({read:async k=>({value:cache.get(k)||{},revision:0}),write:async(k,v)=>{cache.set(k,v);return 1;},extract:async m=>messages.find(x=>x.id===m.id)});const result=await control.processBooking(b(),async path=>path==='messages'?{messages:messages.map(m=>({id:m.id}))}:{id:path.split('/')[1]},{});assert.equal(result.linked[0].status,'cancelled');assert.equal(result.errors,0);assert.equal(result.linked[0].observedAt,messages[1].at);});
test('supplier fields are extracted without borrowing dates or occupants from todo; cancellation terms do not cancel',()=>{const m=mail(),e=parseDocument(m.docs[0],m);assert.equal(e.start,'2027-01-13');assert.equal(e.end,'2027-01-15');assert.equal(e.occupants,1);assert.equal(e.capacity,2);assert.equal(e.status,'confirmed');assert.equal(matchEvidence(e,b()).productMatch,true);const changed=b();changed.todos[0].startDate='2027-01-12';const state={...emptyState(),bookings:[changed],evidence:[matchEvidence(e,changed)]};assert.ok(evaluate(state).findings.some(f=>f.code.startsWith('dates-')&&f.status==='alarm'));assert.equal(cancellation(m),null);});
test('free-form request and unrecognised PDF cannot become a confirmation',()=>{const m=mail();m.from='reservations@treinrondreis.nl';assert.equal(parseDocument(m.docs[0],m),null);assert.equal(parseDocument({label:'invoice.pdf',text:'Arrival date: 13 jan 2027 Departure date: 15 jan 2027 Rooms: 1 double'},m),null);});
test('different guest at same hotel is not silently linked without a matching reservation reference',()=>{const m=mail(),e=parseDocument(m.docs[0],m);e.name='Someone Else';e.reference='other';assert.equal(matchEvidence(e,b()),null);});
test('NS tickets use printed year, count berths, allow Meidling and preserve distinct ticket IDs',()=>{const m=mail(),text='DNR: ABCDEFG ID:2 VERVOERBEWIJS + RESERVERING CIV 1184 NIGHTJET REIZIGER, TEST 04 VOLWASSENEN 23.02 20:12 WIEN MEIDLING -> UTRECHT CENTRAAL 24.02 09:29 TREIN 40490 NJ RIJTUIG 433 LIGPLAATS 91 -94 AFD. MET VIER LIGPL.COMFORT';const e=parseDocument({label:'ticket.pdf',text,year:'2027'},m);assert.equal(e.reference,'ABCDEFG/2');assert.equal(e.capacity,4);assert.equal(e.direction,'inbound');assert.equal(e.start,'2027-02-23');assert.equal(parseDocument({label:'ticket.pdf',text},m),null);});
test('verified ÖBB refund invalidates only its explicit reference',()=>{const m={...mail(),from:'noreply@oebb.at',subject:'ÖBB refund',docs:[{label:'E-mail',text:'Booking code: 1234 5678 9012 3456 Customer number: xx refund for your order has been processed successfully. Refunded tickets become invalid.'}]};assert.equal(cancellation(m).reference,'1234567890123456');m.docs[0].text='Your cancellation policy allows refunds';assert.equal(cancellation(m),null);});
test('only explicit read-only NS PDF URLs are fetched; external links and unreadable documents stay incomplete',async()=>{assert.ok(safeTicketURL('https://www.bene-system.com/hp/pdfservice?pdf=abc'));for(const u of ['http://www.bene-system.com/hp/pdfservice?pdf=x','https://evil.test/hp/pdfservice?pdf=x','https://www.bene-system.com/cancel?pdf=x','https://www.bene-system.com@127.0.0.1/hp/pdfservice?pdf=x'])assert.equal(safeTicketURL(u),null);assert.throws(()=>pdfText(Buffer.from('cancelled')));const html='<a href="https://www.bene-system.com/hp/pdfservice?pdf=x">Print</a><a href="https://evil.test/delete">Delete</a>';let fetched=0;const result=await extractMessage({id:'abc',internalDate:Date.now(),payload:{headers:[],parts:[{mimeType:'text/html',body:{data:Buffer.from(html).toString('base64url')}}]}},()=>{}, {readTicket:async()=>{fetched++;return {cancelled:true};}});assert.equal(fetched,1);assert.equal(result.retiredLinks.length,1);assert.equal(result.issues.length,0);});
test('durable job stores query, sources and progress; cached emails are not reinterpreted; errors never produce green',async()=>{const kv=new Map();let state={...emptyState(),bookings:[b()]},revision=0,reads=0;const read=async k=>structuredClone(kv.get(k)||{value:{},revision:0}),write=async(k,value,r)=>{assert.equal((kv.get(k)?.revision||0),r);kv.set(k,{value:structuredClone(value),revision:r+1});return r+1;};const control=createMailControl({read,write,readState:async()=>({state:structuredClone(state),revision}),writeState:async(s,r)=>{assert.equal(r,revision);state=s;return ++revision;},google:{status:async()=>({connected:true}),reader:async()=>async path=>{if(path==='messages')return {messages:[{id:'abc'}]};reads++;return {};}},extract:async()=>mail()});await control.start({pilot:true});await control.tick();assert.equal((await control.status()).status,'completed');assert.equal(state.summary[0].checked,true);assert.equal(state.emailChecks[6685].stays[0].query,bookingQuery(b()));await control.start({pilot:true});await control.tick();assert.equal(reads,1);state.emailChecks[6685].stays[0].state='incomplete';state.emailChecks[6685].stays[0].explanation='PDF ontbreekt';assert.equal(evaluate(state).summary[0].checked,false);});
test('cancelled trips with a live supplier reservation stay in the recheck plan',()=>{const s={...emptyState(),bookings:[{...b(),status:'geannuleerd'}],evidence:[{trip:'6685',status:'confirmed'}]};assert.ok(mailPlan(s).includes('6685'));});
test('newly active statuses and actual waiting status enter the mail plan',()=>{for(const status of ['afgerond','afgehandeld','verwerkt','tickets versturen','wacht op betaling','interrail leveren','wacht klant'])assert.ok(mailPlan({...emptyState(),bookings:[{...b(),status}]}).includes('6685'),status);assert.equal(mailPlan({...emptyState(),bookings:[{...b(),status:'geannuleerd'}]}).length,0);});
test('daily mail selection skips historical completed trips unless future evidence needs review',()=>{const s={...emptyState(),bookings:[{...b(),status:'afgehandeld',dateDeparture:'2025-01-13',dateReturn:'2025-01-15',todos:b().todos.map(t=>({...t,startDate:'2025-01-13',endDate:'2025-01-15'}))}]};assert.equal(mailPlan(s,false,'2026-10-03T12:00:00Z').length,0);s.evidence=[{trip:'6685',status:'confirmed',end:'2027-01-15'}];assert.ok(mailPlan(s,false,'2026-10-03T12:00:00Z').includes('6685'));s.evidence=[];s.findings=[{trip:'6685',status:'alarm'}];assert.equal(mailPlan(s,false,'2026-10-03T12:00:00Z').length,0);});
test('name search combines first and last name; an explicit other trip never links',()=>{assert.ok(bookingQuery(b()).includes('("Test" "Reiziger")'));const m=mail(),e=parseDocument(m.docs[0],m);e.tripHint='9999';assert.equal(matchEvidence(e,b()),null);});
test('an unrelated failed train link cannot block a proven hotel',async()=>{const cache=new Map(),control=createMailControl({read:async k=>({value:cache.get(k)||{},revision:0}),write:async(k,v)=>{cache.set(k,v);return 1;},extract:async m=>m.id==='hotel'?mail():{...mail(),id:'train',from:'no-reply@nsinternational.nl',subject:'Other train',docs:[{label:'E-mail',text:'Different trip'}],issues:['Ticket not available']}});const result=await control.processBooking(b(),async path=>path==='messages'?{messages:[{id:'hotel'},{id:'train'}]}:{id:path.split('/')[1]},{});assert.equal(result.checks[0].state,'found');assert.equal(result.checks[0].errors.length,0);assert.equal(result.errors,1);});

test('NS replacement ticket redirects stay within the exact trusted PDF service',async()=>{let calls=0;const result=await ticket('https://www.bene-system.com/hp/pdfservice?pdf=old',{fetchImpl:async url=>{calls++;return calls===1?new Response(null,{status:302,headers:{location:'/hp/pdfservice?pdf=new&suppresswarning=N'}}):new Response('Dit ticket is reeds geannuleerd');}});assert.equal(calls,2);assert.equal(result.cancelled,true);for(const location of ['https://evil.test/file','http://www.bene-system.com/hp/pdfservice?pdf=x','https://www.bene-system.com/cancel?pdf=x']){calls=0;await assert.rejects(ticket('https://www.bene-system.com/hp/pdfservice?pdf=old',{fetchImpl:async()=>{calls++;return new Response(null,{status:302,headers:{location}});}}),/niet ondersteund/);assert.equal(calls,1);}});
