import test from 'node:test';
import assert from 'node:assert/strict';
import {parseNSTrains,connectionCandidates} from './flora-trains-parser.mjs';
import {createTrains} from './flora-trains.mjs';
const message={id:'mail',from:'no-reply@confirmation.nsinternational.nl',subject:'Bevestiging, naam: 42A, boekingscode: ABCDEFG',at:'2026-10-01',url:'https://mail.google.com/mail/u/0/#all/mail',docs:[{label:'NS-ticket',year:'2027',text:'DNR: ABCDEFG ID:2 VERVOERBEWIJS + RESERVERING CIV 1184 NIGHTJET TEST 02 VOLWASSENEN 23.02 20:12 WIEN MEIDLING -> UTRECHT CENTRAAL 24.02 09:29 TREIN 40490 NJ RIJTUIG 433'}]};
test('all ticket pages use subject year when absent, including November and ignoring passage pages',()=>{
 const m={...message,subject:message.subject+', vertrekdatum: 26/10/2026',docs:[{label:'page 1',text:'26.10 19:08 ARNHEM -> WIEN HBF 27.10 09:48 TREIN 40421'},{label:'page 2',text:'02.11 18:36 WIEN HBF -> ARNHEM 03.11 08:43 TREIN 40490'},{label:'page 3',text:'Geldig:26.10.2026 Dit passageticket voor het openen van poortjes'},{label:'page 4',text:'VERVOERBEWIJS Geldig:26.10.2026 A -> B'}]};
 const rows=parseNSTrains(m,'42');assert.deepEqual(rows.map(r=>[r.date,r.arrivalDate]),[['2026-10-26','2026-10-27'],['2026-11-02','2026-11-03']]);
 assert.equal(parseNSTrains({...m,subject:message.subject},'42').length,0);
 assert.equal(parseNSTrains({...m,subject:message.subject+', vertrekdatum: 31/12/2026',docs:[{label:'ticket',text:'01.01 10:00 A -> B 01.01 12:00 TREIN 100'}]},'42')[0].date,'2027-01-01');
});
test('integrated itinerary extracts every leg without treating seats as train numbers',()=>{
 const docs=[{label:'ticket',text:'Geldig:18.10.2026 Uw reisschema en geboekte reservering(en) 18/10/2026 07:20 ZWOLLE -> 08:19 ARNHEM CENTRAAL IC3621 * * 18/10/2026 08:34 ARNHEM CENTRAAL -> 12:01 HANNOVER HBF ICE143 24 91 92 Ref.nr:12345 Overzicht: EUR 20'}];
 const rows=parseNSTrains({...message,docs},'42');assert.deepEqual(rows.map(r=>r.number),['3621','143']);assert.equal(rows[1].to,'HANNOVER HBF');
});
test('VIA train binding supplements reservations without duplicate trains or invented arrival times',()=>{
 const docs=[{label:'ticket',text:'Geldig:17.10.2026 KLASSE * * START -> WIEN ***** VIA <1184>(17.10.2026)NV* Arnhem Centraal 9:34 ICE225/M-Hbf 17:12 RJX261 SPARPREIS EUROPA'},{label:'reservation',year:2026,text:'17.10 09:34 Arnhem Centraal -> MUENCHEN HBF 17.10 15:40 TREIN 225'}];
 const rows=parseNSTrains({...message,docs},'42');assert.equal(rows.length,2);assert.equal(rows.find(r=>r.number==='225').arrival,'15:40');assert.equal(rows.find(r=>r.number==='261').arrival,'');assert.equal(rows.find(r=>r.number==='261').to,'WIEN');
});
test('cancelled ticket links cannot revive old email itineraries',()=>{
 const docs=[{label:'E-mail',text:'Utrecht - Wien Vertrek: wo 21 okt 2026 Treinnummer: 225 Reizigers: 2'}];assert.deepEqual(parseNSTrains({...message,docs,retiredLinks:['cancelled']},'42'),[]);
});
test('NS ticket yields explicit train, trip, dates and evidence; options and wrong trips excluded',()=>{const [r]=parseNSTrains(message,'42');assert.equal(r.number,'40490');assert.equal(r.trip,'42');assert.equal(r.date,'2027-02-23');assert.equal(r.arrivalDate,'2027-02-24');assert.equal(r.from,'WIEN MEIDLING');assert.equal(r.to,'UTRECHT CENTRAAL');assert.equal(r.source,message.url);assert.deepEqual(parseNSTrains(message,'43'),[]);assert.deepEqual(parseNSTrains({...message,subject:'Optieboeking 42A'},'42'),[]);assert.deepEqual(parseNSTrains({...message,subject:'Annulering 42A'},'42'),[]);});
test('connections contain trip and both train numbers and require a backup choice',()=>{const rows=[{id:'a',trip:'42',number:'100',to:'Dresden Hbf',arrivalDate:'2027-02-23',arrival:'12:00'},{id:'b',trip:'42',number:'200',from:'Dresden Hbf',date:'2027-02-23',departure:'12:30'}];const [c]=connectionCandidates(rows);assert.equal(c.trip,'42');assert.equal(c.arrivalTrain,'100');assert.equal(c.departureTrain,'200');assert.equal(c.station,'Dresden Hbf');assert.equal(c.backup,null);assert.equal(c.minutes,30);assert.equal(connectionCandidates([rows[0],{...rows[1],trip:'43'}]).length,0);assert.equal(connectionCandidates([rows[0],{...rows[1],from:'Berlin Hbf'}]).length,0);});
test('small scan uses newest NS dossier message only and does not change overnight state',async()=>{const kv=new Map(),extracted=[];const c=createTrains({read:async k=>structuredClone(kv.get(k)||{value:{},revision:0}),write:async(k,value,r)=>{kv.set(k,{value,revision:r+1});return r+1;},bookings:async()=>({state:{bookings:[{index:42}]}}),google:{status:async()=>({connected:true}),reader:async()=>async path=>path==='messages'?{messages:[{id:'old'},{id:'new'}]}:{id:path.split('/')[1],internalDate:path.endsWith('new')?'200':'100',payload:{headers:[{name:'Subject',value:message.subject}]}}},extract:async m=>{extracted.push(m.id);return {...message,issues:[]};}});await c.start(['42A']);await c.tick();assert.deepEqual(extracted,['new']);assert.equal((await c.status()).status,'completed');const d=await c.data();assert.equal(d.rows.length,1);assert.equal(d.rows[0].status,'Te beoordelen');await c.review({type:'train',id:d.rows[0].id,confirmed:true,revision:d.revision});assert.equal((await c.data()).rows[0].status,'Bevestigd');assert.equal(kv.has('job'),false);});

test('NS email reservation summary saves explicit train even without times',()=>{const docs=[{label:'E-mail',text:'Reisgegevens Bekijk de actuele route- en vertrekinformatie . Utrecht Centraal - Muenchen Hbf Vertrek: wo 21 okt 2026 Aankomst: wo 21 okt 2026 Met: OSDM Reservation as issuer Treinnummer: 225 Reizigers: 2 x Volwassene met tarief Zitplaatsreservering 2e klas Delft - Muenchen Hbf Vertrek: wo 21 okt 2026 Reizigers: 2 x Volwassene'}];const rows=parseNSTrains({...message,docs},'42');assert.equal(rows.length,1);assert.equal(rows[0].number,'225');assert.equal(rows[0].from,'Utrecht Centraal');assert.equal(rows[0].to,'Muenchen Hbf');assert.equal(rows[0].date,'2026-10-21');assert.equal(rows[0].departure,'');});
