import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {evaluate,stays,validateEvidence,currentBookings,twoMonthsBefore,DEFAULT_RULES} from './flora-engine.mjs';
import {emptyState,initFlora,readFlora,writeFlora} from './flora-store.mjs';
import {fetchBookings} from './flora-sanity.mjs';
import {createFloraHandler,parseCSV} from './flora.mjs';
const booking=()=>({_id:'private.x',index:42,status:'te verwerken',dateDeparture:'2027-02-19',firstName:'Eva',lastName:'Visser',passengers:[{firstName:'Eva',lastName:'Visser'},{firstName:'Steven',lastName:'Visser'}],todos:[{_key:'hotel',title:'Hotel Test | Double',tag:'hotel',startDate:'2027-02-19',endDate:'2027-02-20',done:true}]});
const proof=(extra={})=>validateEvidence([{trip:'42A',todoKey:'hotel',provider:'Hotel',reference:'123',source:'Bevestiging.pdf',status:'confirmed',start:'2027-02-19',end:'2027-02-20',name:'Steven Visser',capacity:2,occupants:2,productMatch:true,...extra}])[0];
const state=(b=booking(),e=[proof()])=>({...emptyState(),bookings:[b],evidence:e});

test('correct staff exception migrates stored rules and keeps reservations as attention',()=>{for(const name of ['Marc van der Lee','Marc van der Lee SH30830654']){const s=state(booking(),[proof({trip:'unknown',name})]);s.rules={...s.rules,exceptionVersion:1,exceptions:['Marc van der Meer','Other Person']};const r=evaluate(s,'2026-10-04T02:00:00Z',{trips:new Set()});assert.equal(r.findings.find(f=>f.code.startsWith('unmatched-')).status,'attention');assert.deepEqual(r.rules.exceptions,['Marc van der Lee','Other Person']);}for(const name of ['Marc van der Meer','Marc van der Leeuwen']){const r=evaluate(state(booking(),[proof({trip:'unknown',name})]));assert.equal(r.findings.find(f=>f.code.startsWith('unmatched-')).status,'alarm');}const r=evaluate(state(booking(),[proof({name:'Marc van der Lee',capacity:1})]));assert.equal(r.findings.find(f=>f.code==='capacity').status,'alarm');});

test('Premier room groups remain verified after cached source rebuild without ephemeral group fields',()=>{const b=booking();b.todos[0].quantity=2;const e=[{...proof({provider:'Premier Inn',reference:'11111',occupants:1}),messageId:'same'},{...proof({provider:'Premier Inn',reference:'22222',occupants:1}),messageId:'same'}];assert.equal(evaluate(state(b,e)).findings.some(f=>f.code==='duplicate'),false);e[1].messageId='different';assert.ok(evaluate(state(b,e)).findings.some(f=>f.code==='duplicate'));e[1].messageId='same';b.todos[0].quantity=1;assert.ok(evaluate(state(b,e)).findings.some(f=>f.code==='duplicate'));});

test('same-DNR passenger tickets total to the travel party; excess reservations still alarm',()=>{const b=booking();b.todos[0].title='NJ RITAD';const e=[proof({provider:'NS International',reference:'ABCDEFG/0',capacity:1,occupants:1}),proof({provider:'NS International',reference:'ABCDEFG/2',capacity:1,occupants:1})];assert.equal(evaluate(state(b,e)).findings.some(f=>f.code==='duplicate'),false);e[1].occupants=2;assert.ok(evaluate(state(b,e)).findings.some(f=>f.code==='duplicate'));});
test('Finnlines continuation prefixed by supplier is informational',()=>{const b=booking();b.todos[0].title='Finnlines Buitenhut';b.todos.push({...b.todos[0],_key:'continuation',title:'Finnlines mail | Zelfde hut als vertrekdatum (gisteren)',startDate:'2027-02-20',endDate:'2027-02-21'});assert.equal(stays(b).length,1);assert.equal(evaluate(state(b,[proof({start:'2027-02-20',end:'2027-02-21'})])).findings.some(f=>f.code.startsWith('dates-')),false);});
test('cancelled backup stops payment alarm but remains a todo cleanup attention',()=>{const b=booking();b.floraPaymentLinkCreated=true;b.todos[0].title='KAMER ANNULEREN';b.todos[0].description='WAA1234567, is geboekt als backup';b.todos[0].done=false;assert.equal(stays(b)[0].reference,'WAA1234567');const f=evaluate(state(b,[proof({status:'cancelled'})])).findings;assert.ok(f.some(f=>f.code==='cancelled-todo'));assert.equal(f.some(f=>f.code==='payment'),false);});
test('conflicting active booking numbers require review and cannot become green',()=>{const b=booking(),s=state();s.bookings.push({...b,_id:'private.other',firstName:'Other'});const result=evaluate(s);assert.equal(result.findings.filter(f=>f.code==='booking-number').length,1);assert.ok(result.summary.every(b=>!b.checked));});
test('explicit two hotel references and correct total occupancy support two rooms',()=>{const b=booking();b.todos[0].supplierBookingNumber='12345 en 67890';b.todos[0].quantity=2;const e=[proof({reference:'12345',capacity:1,occupants:1}),proof({reference:'67890',capacity:1,occupants:1})];assert.equal(evaluate(state(b,e)).findings.some(f=>f.code==='duplicate'),false);b.todos[0].quantity=1;assert.equal(evaluate(state(b,e)).findings.some(f=>f.code==='duplicate'),false);e[1].occupants=2;assert.ok(evaluate(state(b,e)).findings.some(f=>f.code==='duplicate'));});
test('past unlinked reservations do not create new alarms',()=>{const e=proof({trip:'unknown',start:'2025-01-01',end:'2025-01-02'});assert.equal(evaluate(state(booking(),[e]),'2026-10-04T01:00:00Z').findings.some(f=>f.code.startsWith('unmatched-')),false);});
test('completed, payment-pending and Interrail delivery are active; cancelled is not',()=>{for(const status of ['afgerond','boeking afgerond','afgehandeld','wacht op betaling','verwerkt','interrail leveren','tickets versturen']){const b=booking();b.status=status;assert.equal(evaluate(state(b)).summary[0].checked,true,status);assert.equal(evaluate(state(b)).findings.some(f=>f.code.startsWith('inactive-')),false,status);}const b=booking();b.status='geannuleerd';assert.ok(evaluate(state(b)).findings.some(f=>f.code.startsWith('inactive-')&&f.status==='alarm'));});
test('historical active trips do not acquire missing-proof alerts, but future evidence is still checked',()=>{const b=booking();b.status='afgehandeld';b.dateDeparture='2026-02-19';b.dateReturn='2026-02-20';b.todos[0].startDate='2026-02-19';b.todos[0].endDate='2026-02-20';assert.equal(evaluate(state(b,[]),'2026-10-03T12:00:00Z').findings.length,0);assert.ok(evaluate(state(b),'2026-10-03T12:00:00Z').findings.some(f=>f.title==='Vermoedelijk verkeerd jaar in todo'));});
test('past todo year with same confirmed dates next year is attention; other date mistakes remain alarms',()=>{const b=booking();b.todos[0].startDate='2026-02-19';b.todos[0].endDate='2026-02-20';let findings=evaluate(state(b),'2026-10-03T12:00:00Z').findings;assert.equal(findings.find(f=>f.code.startsWith('dates-')).status,'attention');assert.match(findings.find(f=>f.code.startsWith('dates-')).title,/jaar in todo/);assert.equal(evaluate(state(b),'2026-01-01T12:00:00Z').findings.find(f=>f.code.startsWith('dates-')).status,'alarm');assert.equal(evaluate(state(b,[proof({start:'2027-02-18'})]),'2026-10-03T12:00:00Z').findings.find(f=>f.code.startsWith('dates-')).status,'alarm');});
test('additional formal first names are a low-priority name variation',()=>{const s=state(booking(),[proof({name:'Steven Johannes Visser'})]);const f=evaluate(s).findings.find(f=>f.code.startsWith('name-'));assert.equal(f.priority,'laag');});
test('green requires evidence for every stay; second traveller accepted',()=>{assert.equal(evaluate(state()).summary[0].checked,true);assert.equal(evaluate(state(booking(),[])).summary[0].checked,false);});
test('created payment link requires hotel confirmation in either representation',()=>{const b=booking();b.floraPaymentLinkCreated=true;b.todos[0].done=false;b.todos[0].status='doing';assert.ok(evaluate(state(b)).findings.some(f=>f.code==='payment'&&f.status==='alarm'));b.todos[0].status='done';assert.equal(evaluate(state(b)).summary[0].checked,true);b.todos[0].status='pending';b.todos[0].done=true;assert.equal(evaluate(state(b)).summary[0].checked,true);});
test('both completion fields and informational Meidling todo',()=>{const b=booking();b.todos.push({...b.todos[0],_key:'note',title:'Booked from Wien Meidlin'});b.todos[0].done=false;b.todos[0].status='done';assert.equal(stays(b).length,1);assert.equal(stays(b)[0].confirmed,true);b.todos[0].done=true;b.todos[0].status='doing';assert.equal(stays(b)[0].confirmed,true);});
test('wrong dates and undersized room are alarms, occupancy mismatch is attention',()=>{assert.equal(evaluate(state(booking(),[proof({start:'2027-02-18'})])).findings[0].automatic,'alarm');assert.ok(evaluate(state(booking(),[proof({capacity:1})])).findings.some(f=>f.code==='capacity'&&f.status==='alarm'));assert.ok(evaluate(state(booking(),[proof({occupants:1})])).findings.some(f=>f.code==='occupancy'&&f.status==='attention'));});
test('single for one traveller is no capacity alarm, room deviation retained',()=>{const b=booking();b.passengers=[b.passengers[1]];const r=evaluate(state(b,[proof({capacity:1,occupants:1,roomMismatch:true})]));assert.equal(r.findings.some(f=>f.status==='alarm'),false);assert.ok(r.findings.some(f=>f.code.startsWith('room')));});
test('Finnlines shifts departure and joins same-cabin continuation',()=>{const b=booking();b.todos[0].title='Finnlines Buitenhut';b.todos[0].endDate='2027-02-21';const e=proof({start:'2027-02-20',end:'2027-02-21'});assert.equal(evaluate(state(b,[e])).summary[0].checked,true);b.todos[0].endDate='2027-02-20';b.todos.push({...b.todos[0],_key:'cont',title:'Zelfde hut als gisteren',startDate:'2027-02-20',endDate:'2027-02-21'});assert.equal(evaluate(state(b,[e])).summary[0].checked,true);});
test('duplicate warning survives notes, cancellation resolves it, grouped rooms are allowed',()=>{const b=booking();b.notes='VEEL GEBOEKT, zie RITAM';const e=[proof(),proof({reference:'456'})];assert.ok(evaluate(state(b,e)).findings.some(f=>f.code==='duplicate'));e[1].status='cancelled';assert.equal(evaluate(state(b,e)).summary[0].checked,true);const rooms=[proof({reference:'1',capacity:1,occupants:1,group:'rooms'}),proof({reference:'2',capacity:1,occupants:1,group:'rooms'})];assert.equal(evaluate(state(b,rooms)).summary[0].checked,true);});
test('drafts override published regardless of order',()=>{const b=booking(),d={...b,_id:'drafts.private.x',status:'wacht op reactie klant'};assert.equal(currentBookings([d,b])[0].status,d.status);assert.equal(currentBookings([b,d])[0].status,d.status);});
test('a first name alone stays uncertain even with an old permissive rule',()=>{const s=state(booking(),[proof({name:'Steven'})]);assert.equal(evaluate(s).findings[0].priority,'laag');s.rules={...DEFAULT_RULES,partialNames:'accept'};assert.equal(evaluate(s).summary[0].checked,false);s.evidence=[proof({name:'Andere Persoon'})];assert.equal(evaluate(s).summary[0].checked,false);});
test('waiting clock persists and expires after seven days; deferral bounded',()=>{const b=booking();b.status='wacht op reactie klant';const s=state(b);Object.assign(s,evaluate(s,'2026-10-01T12:00:00Z'));assert.equal(s.findings[0].status,'attention');assert.equal(evaluate(s,'2026-10-08T12:00:00Z').findings[0].status,'alarm');s.deferrals={'42':{until:'2026-11-01',reason:'Vertrek in februari'}};assert.equal(evaluate(s,'2026-10-08T12:00:00Z').findings[0].status,'attention');s.deferrals['42'].until='2027-02-01';assert.equal(evaluate(s,'2026-10-08T12:00:00Z').findings[0].status,'alarm');assert.equal(twoMonthsBefore('2027-04-30'),'2027-02-28');});
test('manual review persists until underlying evidence changes',()=>{const s=state(booking(),[proof({capacity:1})]);Object.assign(s,evaluate(s));s.findings[0].override={status:'checked',reason:'Gecontroleerd'};assert.equal(evaluate(s).findings[0].status,'checked');s.evidence[0].capacity=null;assert.ok(evaluate(s).findings.some(f=>f.status!=='checked'));});
test('unmatched email exception and unlinked todo remain visible',()=>{const s=state(booking(),[proof({trip:'999',name:'Hildebrand van Kuijeren'})]);assert.equal(evaluate(s).findings.find(f=>f.code.startsWith('unmatched')).status,'attention');s.evidence=[proof({todoKey:'wrong'})];assert.ok(evaluate(s).findings.some(f=>f.code.startsWith('unlinked')));});
test('CSV escaped fields and input validation',()=>{assert.equal(parseCSV('provider,source\nHotel,"file, with comma.pdf"')[0].source,'file, with comma.pdf');assert.throws(()=>proof({start:'2027-02-30'}));assert.throws(()=>proof({capacity:-1}));assert.throws(()=>parseCSV('x,x\n1,2'));});
test('persistent SQLite state rejects concurrent edits',async()=>{const sqlite=new DatabaseSync(':memory:');await initFlora({sqlite});const a=await readFlora();assert.equal(a.revision,0);await writeFlora(state(),0);await assert.rejects(writeFlora(state(),0));assert.equal((await readFlora()).state.bookings[0].index,42);sqlite.close();});
test('Sanity adapter uses GET only and draft-aware raw pagination',async()=>{let n=0;const docs=Array.from({length:100},(_,i)=>({_id:String(i).padStart(3,'0')}));const all=await fetchBookings({config:{project:'test',dataset:'production',token:'test'},fetcher:async(url,options)=>{assert.equal(options.method,'GET');assert.equal(url.searchParams.get('perspective'),'raw');n++;return {ok:true,json:async()=>({result:n===1?docs:[]})};}});assert.equal(n,2);assert.equal(all.length,100);});
test('handler authenticates before reading data and rejects cross-site writes',async()=>{const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},writeHead(s){this.status=s;},end(b){this.body=b;}});const url=new URL('https://example.test/seinhuis/flora/api/state');let read=false;const h=createFloraHandler({authenticate:async()=>false,read:async()=>{read=true;}}),r=res();await h({method:'GET'},r,url);assert.equal(r.status,401);assert.equal(read,false);const r2=res();await createFloraHandler({authenticate:async()=>true})({method:'POST',headers:{origin:'https://evil.test'}},r2,url);assert.equal(r2.status,403);});

test('waiting customer does not require unbooked stays but keeps confirmed reservation controls',()=>{
 for(const status of ['wacht klant','wacht op reactie klant']){const b={...booking(),status};const s=state(b,[]);const result=evaluate(s);assert.equal(result.findings.length,0);assert.equal(result.summary[0].checked,false);
 const confirmed=evaluate(state(b,[proof({capacity:1})]));assert.ok(confirmed.findings.some(f=>f.code==='capacity'));assert.ok(confirmed.findings.some(f=>f.code==='waiting'));
 const active=evaluate(state({...b,status:'te verwerken'},[]));assert.ok(active.findings.some(f=>f.code==='missing'));
 }
});
