import {DEFAULT_RULES} from './flora-engine.mjs';
let db;
export async function initFlora(database){db=database;const sql='CREATE TABLE IF NOT EXISTS flora_state (id INTEGER PRIMARY KEY, revision INTEGER NOT NULL, payload TEXT NOT NULL)';if(db.pool)await db.pool.query(sql);else db.sqlite.exec(sql);const google='CREATE TABLE IF NOT EXISTS flora_google (id INTEGER PRIMARY KEY, revision INTEGER NOT NULL, payload TEXT NOT NULL)';if(db.pool)await db.pool.query(google);else db.sqlite.exec(google);const mail='CREATE TABLE IF NOT EXISTS flora_mail (key TEXT PRIMARY KEY, revision INTEGER NOT NULL, payload TEXT NOT NULL)';if(db.pool)await db.pool.query(mail);else db.sqlite.exec(mail);}
export const emptyState=()=>({bookings:[],evidence:[],findings:[],summary:[],imports:[],audit:[],rules:{...DEFAULT_RULES},ruleHistory:[],deferrals:{},lastSync:null});
export async function readFlora(){if(!db)throw Error('FloRA-opslag is nog niet gereed.');const r=db.pool?(await db.pool.query('SELECT revision,payload FROM flora_state WHERE id=1')).rows[0]:db.sqlite.prepare('SELECT revision,payload FROM flora_state WHERE id=1').get();return r?{revision:Number(r.revision),state:JSON.parse(r.payload)}:{revision:0,state:emptyState()};}
export async function writeFlora(state,revision){const sql='INSERT INTO flora_state(id,revision,payload) VALUES(1,1,$1) ON CONFLICT(id) DO UPDATE SET revision=flora_state.revision+1,payload=excluded.payload WHERE flora_state.revision=$2 RETURNING revision',args=[JSON.stringify(state),revision],r=db.pool?(await db.pool.query(sql,args)).rows[0]:db.sqlite.prepare(sql.replace(/\$\d/g,'?')).get(...args);if(!r){const e=Error('Een andere beheerder heeft iets gewijzigd. Herlaad FloRA.');e.status=409;throw e;}return Number(r.revision);}

export async function readFloraGoogle(){if(!db)throw Error('FloRA-opslag is nog niet gereed.');const r=db.pool?(await db.pool.query('SELECT revision,payload FROM flora_google WHERE id=1')).rows[0]:db.sqlite.prepare('SELECT revision,payload FROM flora_google WHERE id=1').get();return r?{revision:Number(r.revision),value:JSON.parse(r.payload)}:{revision:0,value:{}};}
export async function writeFloraGoogle(value,revision){const sql='INSERT INTO flora_google(id,revision,payload) VALUES(1,1,$1) ON CONFLICT(id) DO UPDATE SET revision=flora_google.revision+1,payload=excluded.payload WHERE flora_google.revision=$2 RETURNING revision',args=[JSON.stringify(value),revision],r=db.pool?(await db.pool.query(sql,args)).rows[0]:db.sqlite.prepare(sql.replace(/\$\d/g,'?')).get(...args);if(!r)throw Error('De Gmail-koppeling is ondertussen gewijzigd. Probeer opnieuw.');return Number(r.revision);}

export async function readMail(key){const r=db.pool?(await db.pool.query('SELECT revision,payload FROM flora_mail WHERE key=$1',[key])).rows[0]:db.sqlite.prepare('SELECT revision,payload FROM flora_mail WHERE key=?').get(key);return r?{revision:Number(r.revision),value:JSON.parse(r.payload)}:{revision:0,value:{}};}
export async function writeMail(key,value,revision){const sql='INSERT INTO flora_mail(key,revision,payload) VALUES($1,1,$2) ON CONFLICT(key) DO UPDATE SET revision=flora_mail.revision+1,payload=excluded.payload WHERE flora_mail.revision=$3 RETURNING revision',args=[key,JSON.stringify(value),revision],r=db.pool?(await db.pool.query(sql,args)).rows[0]:db.sqlite.prepare(sql.replace(/\$\d/g,'?')).get(...args);if(!r){const e=Error('Gelijktijdige e-mailcontrole; probeer opnieuw.');e.status=409;throw e;}return Number(r.revision);}
