import {randomUUID} from 'node:crypto';
import {floraGoogle} from './flora-google.mjs';
import {readMail,writeMail,readFlora,writeFlora} from './flora-store.mjs';
import {currentBookings,normalize,stays,hash,evaluate} from './flora-engine.mjs';
import {planFollowup} from './flora-followup.mjs';
import {extractMessage} from './flora-mail-source.mjs';
import {bookingQuery,parseDocument,matchEvidence,cancellation,hotelReplyReview} from './flora-mail-parser.mjs';

const stamp=()=>new Date().toISOString();
const needsRead=m=>![4,5].includes(m.version)||m.version!==5&&/@(?:bernerhof-interlaken|hotel-federale)\.ch\b/i.test(m.from||'')||m.hasLinks||m.issues?.length;
export function rememberCancellation(state,c){const key=c.provider+'|'+c.reference,map=state.emailCancellations??={};if(!map[key]||map[key].at<c.at)map[key]=c;}
export function latestReservationState(state,e){const c=state.emailCancellations?.[e.provider+'|'+e.reference];return c&&(!e.observedAt||e.observedAt<=c.at)?{...e,status:'cancelled',source:c.source,observedAt:c.at}:e;}

export function mailPlan(state,pilot=false){const selected=planFollowup(state).trips;return currentBookings(state.bookings).filter(b=>pilot?[6685,6677,6667,6657,6656].includes(Number(b.index)):(['te verwerken','wacht op reactie klant'].includes(normalize(b.status))||state.evidence.some(e=>e.trip===String(b.index)&&e.status==='confirmed'))&&(selected.has(String(b.index))||state.emailChecks?.[b.index]?.parserVersion!==5)).map(b=>String(b.index));}
export function createMailControl({read=readMail,write=writeMail,readState=readFlora,writeState=writeFlora,google=floraGoogle,extract=extractMessage,clock=()=>Date.now()}={}){
 let running=false;
 async function status(){const {value}=await read('job');const {queue,...publicJob}=value;return {...publicJob,total:queue?.length||0,stalled:value.status==='running'&&value.lease<clock()};}
 async function start({pilot=false,mode='manual'}={}){if(!(await google.status()).connected)throw Error('Koppel Gmail eerst.');const {value,revision}=await read('job');if(['running','queued'].includes(value.status))return status();if(value.status==='failed'&&value.parserVersion===5&&value.pilot===pilot&&value.done<value.queue.length){value.status='queued';value.phase='Hervatten vanaf de laatste opgeslagen boeking';delete value.owner;delete value.lease;await write('job',value,revision);return status();}const {state}=await readState();const queue=mailPlan(state,pilot);await write('job',{id:randomUUID(),parserVersion:5,status:'queued',mode,pilot,queue,done:0,startedAt:stamp(),updatedAt:stamp(),phase:'Wacht op e-mailcontrole',messages:0,documents:0,errors:0},revision);return status();}
 async function processBooking(b,get,job,onProgress=async()=>{}){const query=bookingQuery(b),ids=[];let page='',limited=false;const deadline=clock()+120000;do{const result=await get('messages',{q:query,maxResults:'100',...(page?{pageToken:page}:{})});ids.push(...(result.messages||[]).map(m=>m.id));page=result.nextPageToken||'';if(ids.length>=200&&page){limited=true;break;}}while(page);
  const messages=[],errors=[],events=[];
  let processed=0;for(const id of [...new Set(ids)]){await onProgress({processed,total:new Set(ids).size});processed++;if(clock()>deadline){limited=true;break;}const cached=await read('message:'+id);let m=cached.value;
   try{if(needsRead(m)){m=await extract(await get('messages/'+id,{format:'full'}),get);m.version=5;await write('message:'+id,m,cached.revision);}messages.push(m);if(/cancel|annul|refund|storn/i.test(m.subject)&&!cancellation(m)&&m.docs.some(d=>d.text.includes(String(b.index)+'A')||stays(b).some(t=>t.reference&&d.text.includes(t.reference))))errors.push({message:id,detail:'Mogelijke annulering of wijziging: handmatige beoordeling nodig.'});for(const doc of m.docs){const e=parseDocument(doc,m);if(e)events.push(e);}errors.push(...m.issues.map(s=>({message:id,detail:s})));}catch(e){errors.push({message:id,detail:e.message});}
  }
   const byRef=new Map();for(const e of events.sort((a,b)=>a.observedAt.localeCompare(b.observedAt))){const key=e.provider+'|'+e.reference;byRef.set(key,e);}
   for(const m of messages){const provider=hotelReplyReview(m);if(provider&&!events.some(e=>e.messageId===m.id)&&!events.some(e=>e.provider===provider&&e.observedAt>=m.at))errors.push({message:m.id,detail:'Nieuw hotelantwoord over de reservering: bevestiging, wijziging of afwijzing handmatig beoordelen.'});}
  const retired=new Set(messages.flatMap(m=>m.retiredLinks||[]));for(const [key,e] of byRef)if(e.ticketLink&&retired.has(e.ticketLink))byRef.set(key,{...e,status:'cancelled'});
  const cancellations=messages.map(cancellation).filter(Boolean);for(const c of cancellations){const key=c.provider+'|'+c.reference,old=byRef.get(key);if(old&&old.observedAt<=c.at)byRef.set(key,{...old,status:'cancelled',source:c.source,observedAt:c.at});}
  const linked=[];for(const e of byRef.values()){const match=matchEvidence(e,b);if(match)linked.push(match);}
  for(const t of stays(b)){const group=linked.filter(e=>e.todoKey===t._key&&e.status==='confirmed'&&e.provider==='Premier Inn');if(group.length>1&&group.length===Number(t.quantity)&&group.every(e=>e.messageId===group[0].messageId&&e.start===group[0].start&&e.end===group[0].end)){for(const e of group){e.group=hash([String(b.index),t._key,e.messageId]);e.roomGroupVerified=true;}}}
  const checks=stays(b).map(t=>{const proof=linked.filter(e=>e.todoKey===t._key),words=normalize(t.title.split('|')[0]).split(' ').filter(w=>w.length>3&&!['hotel','double','tweepersoonskamer','standaard','personen','buitenhut','binnenhut','privé'].includes(w)),candidates=messages.filter(m=>{if(proof.some(e=>e.messageId===m.id))return true;const text=normalize(m.subject+' '+m.docs.map(d=>d.text).join(' '));if(t.reference)return text.replace(/ /g,'').includes(normalize(t.reference).replace(/ /g,''));if(t.type==='Hotel'&&/nsinternational|oebb/i.test(m.from))return false;if(t.type==='Nachttrein')return /nsinternational|oebb/i.test(m.from);return words.some(w=>text.includes(w));}),sourceErrors=errors.filter(e=>candidates.some(m=>m.id===e.message)||!messages.some(m=>m.id===e.message));return {todoKey:t._key,title:t.title,provider:t.provider,at:stamp(),query,state:limited||sourceErrors.length?'incomplete':proof.length?'found':candidates.length?'candidates':'not-found',explanation:limited?'Zoeklimiet of tijdslimiet bereikt; niet alles gecontroleerd.':sourceErrors.length?'Een of meer bronnen konden niet volledig worden gelezen.':proof.length?'Reserveringsgegevens uit bron gelezen; inhoudelijke uitkomst staat bij Meldingen.':candidates.length?'Mogelijke berichten gevonden, maar geen eenduidig uitleesbare bevestiging gekoppeld.':'Geen bericht gevonden met deze zoekopdracht; dit bewijst niet dat er geen reservering is.',references:proof.map(e=>e.reference),sources:candidates.map(m=>({id:m.id,subject:m.subject,url:m.url,at:m.at,documents:m.docs.map(d=>d.label),retiredTickets:(m.retiredLinks||[]).length,issues:m.issues})),fields:proof.map(e=>({reference:e.reference,provider:e.provider,start:e.start,end:e.end,name:e.name,capacity:e.capacity,occupants:e.occupants,product:e.product,document:e.document,source:e.source})),errors:sourceErrors};});
  return {checks,linked,messages:messages.length,documents:messages.reduce((n,m)=>n+m.docs.length,0),errors:errors.length+(limited?1:0),cancellations,retiredLinks:[...retired],fingerprint:hash(b),trip:String(b.index)};
 }
 async function save(result){for(let retry=0;retry<5;retry++){const {state,revision}=await readState(),b=currentBookings(state.bookings).find(b=>String(b.index)===result.trip);if(!b||hash(b)!==result.fingerprint)throw Error('Boeking is tijdens de controle gewijzigd; voer opnieuw uit.');for(const e of state.evidence)if(e.ticketLink&&result.retiredLinks.includes(e.ticketLink))e.status='cancelled';
  for(const c of result.cancellations){rememberCancellation(state,c);for(const e of state.evidence)if(e.provider===c.provider&&e.reference===c.reference&&(!e.observedAt||e.observedAt<=c.at)){e.status='cancelled';e.source=c.source;e.observedAt=c.at;}}
  (state.emailChecks??={})[result.trip]={at:stamp(),parserVersion:5,stays:result.checks};const ids=new Set(result.linked.map(e=>e.id));state.evidence=state.evidence.filter(e=>!ids.has(e.id)).concat(result.linked.map(e=>({...latestReservationState(state,e),importedAt:stamp(),automaticEmail:true})));Object.assign(state,evaluate(state,stamp(),{trips:new Set([result.trip])}));try{await writeState(state,revision);return;}catch(e){if(e.status!==409||retry===4)throw e;}}}
 async function discover(get,job,progress){
  const watermark=await read('discovery');const from=watermark.value.at?new Date(Date.parse(watermark.value.at)-7*86400000).toISOString().slice(0,10):new Date(clock()-90*86400000).toISOString().slice(0,10);
  job.discoveryFrom=from;let page=job.discoveryPage||'';
  do{job.phase='Mailbox doorzoeken op niet-gekoppelde reserveringen (ondersteunde leveranciers)';await progress();const list=await get('messages',{q:'after:'+from+' {from:expediataap.nl from:nsinternational.nl from:oebb.at from:finnlines.com from:whitbread.com from:premierinn.com from:hotelabc.ch from:bernerhof-interlaken.ch from:hotel-federale.ch} -in:spam -in:trash',maxResults:'20',...(page?{pageToken:page}:{})});
   for(const {id} of list.messages||[]){const cache=await read('message:'+id);let m=cache.value;try{if(needsRead(m)){m=await extract(await get('messages/'+id,{format:'full'}),get);m.version=5;await write('message:'+id,m,cache.revision);}const proofs=m.docs.map(d=>parseDocument(d,m)).filter(Boolean),cancel=cancellation(m);
    for(let retry=0;retry<4;retry++){const {state,revision}=await readState(),bookings=currentBookings(state.bookings);const changed=new Set();
     if(cancel)rememberCancellation(state,cancel);
     if(cancel)for(const e of state.evidence)if(e.provider===cancel.provider&&e.reference===cancel.reference&&(!e.observedAt||e.observedAt<=cancel.at)){e.status='cancelled';e.source=cancel.source;e.observedAt=cancel.at;changed.add(e.trip||'onbekend');}
     for(const proof of proofs){const e=latestReservationState(state,proof);if(e.end<stamp().slice(0,10))continue;const matches=bookings.map(b=>matchEvidence(e,b)).filter(Boolean);let linked=matches.length===1?matches[0]:null;if(!linked){const known=bookings.some(b=>(b.passengers||[]).some(p=>normalize(e.name).includes(normalize(p.lastName))));if(known)continue;linked={...e,trip:'',todoKey:'',id:hash([e.provider,e.reference,'',''])};}const previous=state.evidence.find(x=>x.id===linked.id);if(previous?.observedAt>=linked.observedAt)continue;if(linked.trip&&state.emailChecks)delete state.emailChecks[linked.trip];state.evidence=state.evidence.filter(x=>x.id!==linked.id).concat({...linked,automaticEmail:true,importedAt:stamp()});changed.add(linked.trip||'onbekend');}
     if(changed.size)Object.assign(state,evaluate(state,stamp(),{trips:changed}));state.emailDiscovery={from,checkedAt:stamp(),coverage:'Expedia TAAP, NS International, ÖBB, Finnlines, Premier Inn, Hotel ABC, Bernerhof en Federale. Andere afzenders alleen via boekingsgerichte zoekopdrachten.'};try{await writeState(state,revision);break;}catch(e){if(e.status!==409||retry===3)throw e;}}
    job.discoveryMessages=(job.discoveryMessages||0)+1;
   }catch{job.errors++;}await progress();}
   page=list.nextPageToken||'';job.discoveryPage=page;await progress();
  }while(page);
  if(!job.errors){const latest=await read('discovery');await write('discovery',{at:job.startedAt},latest.revision);}
 }
 async function tick(){if(running)return;running=true;let owner,job;
  try{const stored=await read('job');job=stored.value;if(!['queued','running'].includes(job.status)||job.status==='running'&&job.lease>clock())return;owner=randomUUID();job.owner=owner;job.lease=clock()+300000;job.status='running';job.updatedAt=stamp();let revision=await write('job',job,stored.revision);const get=await google.reader();
   while(job.done<job.queue.length){const trip=job.queue[job.done];job.phase='Boeking '+trip+'A: berichten en tickets lezen';job.current=trip;job.updatedAt=stamp();job.lease=clock()+300000;revision=await write('job',job,revision);const {state}=await readState(),b=currentBookings(state.bookings).find(b=>String(b.index)===trip);if(!b)throw Error('Boeking niet meer aanwezig in Sanity-selectie.');const result=await processBooking(b,get,job,async({processed,total})=>{job.phase='Boeking '+trip+'A: bericht '+processed+' van '+total+' verwerken';job.updatedAt=stamp();job.lease=clock()+300000;revision=await write('job',job,revision);});await save(result);job.done++;job.messages+=result.messages;job.documents+=result.documents;job.errors+=result.errors;job.updatedAt=stamp();revision=await write('job',job,revision);}
   if(!job.pilot)await discover(get,job,async()=>{job.updatedAt=stamp();job.lease=clock()+300000;revision=await write('job',job,revision);});
   job.status=job.errors?'partial':'completed';job.phase=job.errors?'Afgerond met onvolledige bronnen; bekijk de details.':'Zoekronde afgerond; bekijk de inhoudelijke resultaten per overnachting.';job.finishedAt=stamp();delete job.owner;delete job.lease;await write('job',job,revision);for(let retry=0;retry<4;retry++){const {state,revision:r}=await readState();state.audit.push({at:stamp(),user:'FloRA',action:'E-mailcontrole '+(job.pilot?'voorbeeldboekingen':'afgerond'),detail:job.done+' boekingen, '+job.messages+' berichten, '+job.documents+' documenten, '+job.errors+' onvolledige bronnen. Zie Boekingen voor zoekopdrachten en bewijs.'});if(!job.errors)state.emailCheckpoint={at:job.startedAt,finishedAt:stamp(),pilot:job.pilot};try{await writeState(state,r);break;}catch(e){if(e.status!==409||retry===3)throw e;}}
   // Finish an in-flight older run first, then revisit its bookings with the corrected interpretation.
   if(job.parserVersion!==5)await start({pilot:job.pilot,mode:'parser-upgrade'});
  }catch(e){if(job?.id){try{const latest=await read('job');if(latest.value.owner===owner)await write('job',{...latest.value,status:'failed',phase:e.message,updatedAt:stamp()},latest.revision);}catch{}}}finally{running=false;}
 }
 return {status,start,tick,processBooking};
}
export const floraMail=createMailControl();
export function startFloraMail(){setTimeout(()=>void floraMail.tick(),20000).unref();setInterval(()=>void floraMail.tick(),30000).unref();}
