import test from 'node:test';
import assert from 'node:assert/strict';
import {createMailControl} from './flora-mail.mjs';
import {conversationCancellations} from './flora-mail-parser.mjs';
import {emptyState} from './flora-store.mjs';
test('discovery applies cancellation list and recovers old broken scan',async()=>{let state={...emptyState(),interpretationVersion:10,evidence:[{id:'e',provider:'Expedia',reference:'123456789',status:'confirmed',observedAt:'2026-01-01',trip:'',end:'2027-01-01'}]};const kv=new Map([['job',{value:{id:'test',status:'queued',parserVersion:10,queue:[],done:0,messages:0,documents:0,errors:3,discoveryErrors:3,discoveryPage:'bad-page',lastIssues:[{detail:'cancel is not defined'}],unlinkedCancellationsChecked:true},revision:1}]]);const c=createMailControl({read:async k=>structuredClone(kv.get(k)||{value:{},revision:0}),write:async(k,value,r)=>{kv.set(k,{value:structuredClone(value),revision:r+1});return r+1;},readState:async()=>({state:structuredClone(state),revision:1}),writeState:async s=>{state=s;return 2;},google:{reader:async()=>async(path,args)=>{if(path==='messages'){assert.equal(args.pageToken,undefined);return {messages:[{id:'cancel'}]};}return {}; }},extract:async()=>({id:'cancel',subject:'TAAP Annuleringsbevestiging',from:'noreply@expediataap.nl',at:'2026-10-04',url:'mail',issues:[],docs:[{label:'E-mail',text:'Je hotelkamer is geannuleerd. TAAP-reisplannummer: 123456789'}]})});await c.tick();assert.equal((await c.status()).status,'completed');assert.equal(state.evidence[0].status,'cancelled');assert.equal((await c.status()).errors,0);assert.ok(kv.has('discovery'));});
test('hotel reply cancellation requires explicit unambiguous confirmation',()=>{const source={id:'original',threadId:'thread'},e={provider:'Hotel Federale',reference:'ABC123',messageId:'original',observedAt:'2026-01-01'},reply=text=>({id:'reply',threadId:'thread',from:'hotel@hotel-federale.ch',at:'2026-10-04',url:'mail',docs:[{label:'E-mail',text}]});for(const text of ['We have cancelled your reservation.','De annulering is verwerkt.','Cancellation confirmed.'])assert.equal(conversationCancellations([source,reply(text)],[e]).length,1);for(const text of ['Please cancel this reservation.','Akkoord','Not cancelled.','Thank you. From: customer We have cancelled your reservation.'])assert.equal(conversationCancellations([source,reply(text)],[e]).length,0);assert.equal(conversationCancellations([source,reply('Cancellation confirmed')],[e,{...e,reference:'OTHER'}]).length,0);});

test('stop persists and prevents a queued scan from reading Gmail',async()=>{const kv=new Map([['job',{value:{id:'stop-test',status:'queued',queue:['42']},revision:1}]]);let reads=0;const c=createMailControl({read:async k=>structuredClone(kv.get(k)||{value:{},revision:0}),write:async(k,value,r)=>{kv.set(k,{value,revision:r+1});return r+1;},google:{reader:async()=>{reads++;}}});assert.equal((await c.stop()).status,'stopped');await c.tick();assert.equal(reads,0);assert.equal((await c.status()).status,'stopped');});
