import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluate} from './flora-engine.mjs';
import {emptyState} from './flora-store.mjs';
import {applyBulkReview,findingComparison,cityFrom} from './flora-review.mjs';
function fixture(){const s=emptyState();s.bookings=[{_id:'b',index:1,status:'te verwerken',passengers:[{firstName:'Eva',lastName:'Test'}],todos:[{_key:'t',tag:'hotel',title:'Hotel Wien | Double',startDate:'2027-01-01',endDate:'2027-01-02',done:true}]}];s.evidence=[{id:'e',trip:'1',todoKey:'t',provider:'Expedia',reference:'R',status:'confirmed',start:'2027-01-01',end:'2027-01-02',name:'Eva Test',product:'Different Hotel Vienna',room:'Double',capacity:2,occupants:1,productMatch:false}];Object.assign(s,evaluate(s));return s;}
const items=s=>s.findings.map(f=>({id:f.id,fingerprint:f.fingerprint}));
test('comparison distinguishes same city from unknown city and exact dates',()=>{const s=fixture(),c=findingComparison(s,s.findings[0]);assert.equal(c.booked[0].cityMatch,'same');assert.equal(c.booked[0].dateMatch,'same');assert.equal(c.booked[0].product,'Different Hotel Vienna');s.evidence[0].product='Hotel Unknown';s.evidence[0].end='2027-01-03';const d=findingComparison(s,s.findings[0]);assert.equal(d.booked[0].cityMatch,'unknown');assert.equal(d.booked[0].dateMatch,'different');assert.equal(cityFrom('Wien → Arnhem'),'');s.evidence[0].sourceText='Hoteloverzicht Different Hotel 12 Example Street, Vienna, Austria Hotel bekijken Kaart';assert.equal(findingComparison(s,s.findings[0]).booked[0].cityMatch,'same');});
test('accepting without control closes findings without green approval; survives repeat; real change reopens',()=>{const s=fixture();applyBulkReview(s,{items:items(s),status:'accepted',reason:'Bewust geaccepteerd'},'Beheerder');assert.equal(s.findings[0].status,'accepted');assert.equal(s.summary[0].checked,false);Object.assign(s,evaluate(s));assert.equal(s.findings[0].status,'accepted');s.evidence[0].product='Other hotel';Object.assign(s,evaluate(s));assert.equal(s.findings[0].status,'attention');assert.equal(s.findings[0].history[0].status,'accepted');});
test('checked selection records author and permits verified booking; stale selection applies nothing',()=>{const s=fixture(),selection=items(s);assert.throws(()=>applyBulkReview(s,{items:[...selection,{id:'absent',fingerprint:'x'}],status:'checked',reason:'Bewijs gezien'},'Beheerder'),/gewijzigd/);assert.equal(s.findings[0].override,null);applyBulkReview(s,{items:selection,status:'checked',reason:'Bewijs gezien'},'Beheerder');assert.equal(s.summary[0].checked,true);assert.equal(s.findings[0].history[0].user,'Beheerder');assert.equal(s.audit.at(-1).ids.length,1);});

test('archive explanation is optional for both dispositions and retains audit',()=>{
 for(const status of ['checked','accepted'])for(const reason of [undefined,'','ok']){const s=fixture();applyBulkReview(s,{items:items(s),status,reason},'Beheerder');assert.equal(s.findings[0].status,status);assert.equal(s.findings[0].history[0].user,'Beheerder');assert.equal(s.findings[0].history[0].reason,reason||'');assert.equal(s.audit.at(-1).ids.length,1);}
});
