import test from 'node:test';
import assert from 'node:assert/strict';
import {hotelIdentity,cityFrom,trainRoom,trainStations} from './flora-identity.mjs';
import {roomCapacity,matchEvidence} from './flora-mail-parser.mjs';
const cases=[['Hotel Don Jaime Zaragoza','Hotel Don','Zaragoza'],['Hotel Continentale Arezzo','Hotel Continentale Piazza Guido Monaco','Arezzo'],['IC Hotel Budapest (email/Expedia/Teldar) | Twin','IntercityHotel Budapest Baross','Budapest'],['Leonardo Wien Hbf | Comfort Double','Leonardo Hotel Vienna Hauptbahnhof Gerhard-Bronner-Straße','Wenen'],['Art & Business Hotel Neurenberg','Art Business Hotel Nürnberg Gleiayba','Neurenberg']];
for(const [title,product,city] of cases)test('accept abbreviated hotel '+title,()=>assert.equal(hotelIdentity({title},{product,provider:'Expedia',sourceText:'Hoteloverzicht '+product+' '+city+' Hotel bekijken'},{}),true));
test('alternative needs supporting note or visible invoice in the same city',()=>{const t={title:'Agumar Hotel Madrid'},e={product:'Hotel PAX Atocha Calle',provider:'Expedia',sourceText:'Hoteloverzicht Hotel PAX Atocha Madrid Hotel bekijken'};assert.equal(hotelIdentity(t,e,{}),false);assert.equal(hotelIdentity(t,e,{lines:[{title:'Madrid: Hotel PAX Atocha',visible:true}]}),true);assert.equal(hotelIdentity(t,e,{lines:[{title:'Madrid: Hotel PAX Atocha',visible:false}]}),false);assert.equal(hotelIdentity({...t,title:'Agumar Hotel Barcelona'}, {...e,product:'PAX Atocha Madrid'},{}),false);});
test('Cadiz explicit exception is limited to the approved dates',()=>{const t={title:'Hotel de Francia y París Cádiz',start:'2026-10-03',end:'2026-10-04'},e={product:'Hotel Cádiz Bahía by Q Hotels'};assert.equal(cityFrom(t.title),'Cádiz');assert.equal(hotelIdentity(t,e,{}),true);assert.equal(hotelIdentity({...t,start:'2027-10-03'},e,{}),false);});
test('same chain in different known city stays unmatched',()=>assert.equal(hotelIdentity({title:'Leonardo Wien Hbf'},{product:'Leonardo Hotel Budapest'},{notes:'Leonardo Hotel Budapest'}),false));
test('train codes distinguish private compartment from minicabins',()=>{for(const code of ['PA1AD','PA1AM','RITAD'])assert.equal(roomCapacity(code),2);assert.equal(trainRoom('PA1AD'),'private');assert.equal(trainRoom('RITAD'),'private');assert.equal(trainRoom('PA1AM'),'mini');assert.equal(trainStations('CHAJD / ATALA / ATWIH'),'Zürich / Innsbruck / Wien');});

test('alternative invoice matches the correct todo without matching reference',()=>{const b={index:42,passengers:[{firstName:'Test',lastName:'Reiziger'}],dateDeparture:'2027-01-01',dateReturn:'2027-01-02',lines:[{title:'Madrid: Hotel PAX Atocha',visible:true}],todos:[{_key:'h',tag:'hotel',title:'Agumar Hotel Madrid',startDate:'2027-01-01',endDate:'2027-01-02'}]},e={provider:'Expedia',reference:'123456789',name:'Test Reiziger',product:'Hotel PAX Atocha Calle',sourceText:'Hoteloverzicht Hotel PAX Atocha Madrid Hotel bekijken',start:'2027-01-01',end:'2027-01-02',room:'Double',status:'confirmed'};const result=matchEvidence(e,b);assert.equal(result.todoKey,'h');assert.equal(result.productMatch,true);assert.equal(matchEvidence(e,{...b,lines:[]}),null);});
