(()=>{
const el=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),date=s=>String(s||'').replace(/^(\d{4})-(\d{2})-(\d{2})$/,'$3-$2-$1');let state={rows:[],connections:[],checks:{}},timer;
async function request(path,body){const r=await fetch('/seinhuis/flora/api/trains'+path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Flora':'1'},body:JSON.stringify(body)}:{}),d=await r.json();if(!r.ok)throw Error(d.error||'Verzoek mislukt');return d;}
const table=(heads,rows)=>'<table><thead><tr>'+heads.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table>';
function render(){const q=el('trainsearch').value.toLowerCase(),cq=el('connectionsearch').value.toLowerCase();el('traintable').innerHTML=table(['Boeking','Datum','Trein','Van → naar','Vertrek / aankomst','Bewijs','Status'],state.rows.filter(r=>[r.trip,r.number,r.from,r.to].join(' ').toLowerCase().includes(q)).map(r=>'<tr><td>'+escape(r.trip?r.trip+'A':'Niet gekoppeld')+'</td><td>'+date(r.date)+'</td><td>'+escape(r.number||'Niet uitgelezen')+'</td><td>'+escape(r.from)+' → '+escape(r.to)+'</td><td>'+escape(r.departure||'Niet vermeld')+' / '+escape(r.arrival||'Niet vermeld')+'<br>'+date(r.arrivalDate)+'</td><td><a target="_blank" rel="noopener noreferrer" href="'+escape(r.source)+'">'+escape(r.reference)+'</a><br>'+escape(r.kind)+'</td><td>'+escape(r.status)+' '+(r.number?'<button data-train-confirm="'+r.id+'">'+(r.status==='Bevestigd'?'Terug naar beoordeling':'Bevestigen')+'</button>':'')+'</td></tr>'))+(state.rows.length?'':'<p>Nog geen treinen ingelezen. Begin met één boekingsnummer.</p>');
el('connectiontable').innerHTML=table(['Boeking','Datum','Aansluitstation','Aankomende trein','Vertrekkende trein','Overstaptijd','Back-up','Status'],state.connections.filter(c=>[c.trip,c.station,c.arrivalTrain,c.departureTrain].join(' ').toLowerCase().includes(cq)).map(c=>'<tr><td>'+escape(c.trip)+'A</td><td>'+date(c.date)+'</td><td>'+escape(c.station)+'</td><td>'+escape(c.arrivalTrain)+' · '+escape(c.arrival)+'</td><td>'+escape(c.departureTrain)+' · '+escape(c.departure)+'</td><td>'+c.minutes+' minuten</td><td><select data-connection="'+c.id+'"><option value="">Kies</option><option value="no" '+(c.backup===false?'selected':'')+'>Nee</option><option value="yes" '+(c.backup===true?'selected':'')+'>Ja</option></select></td><td>'+escape(c.status)+'</td></tr>'))+(state.connections.length?'':'<p>Nog geen eenvoudige aansluitingen gevonden.</p>');el('trainissues').innerHTML=Object.entries(state.checks).map(([trip,c])=>'<details><summary>'+escape(trip)+(trip.startsWith('NS ')?'':'A')+' · '+c.messages+' berichten · '+c.dossiers+' NS-dossiers</summary>'+c.issues.map(s=>'<p>'+escape(s)+'</p>').join('')+(c.notes||[]).map(s=>'<p>'+escape(s)+'</p>').join('')+'</details>').join('');}
async function load(){try{state=await request('');render();const active=['queued','running'].includes(state.job?.status);el('trainprogress').textContent=(state.job?.phase||'Nog geen treincontrole gestart.')+(state.job?.at?' Laatste voortgang: '+new Date(state.job.at).toLocaleString('nl-NL',{timeZone:'Europe/Amsterdam'})+'.':'')+(state.job?.issues?.length?' '+state.job.issues.length+' opmerkingen; bekijk de dossierdetails.':'');el('trainscan').disabled=active;el('trainimport').disabled=active;el('trainschedule').textContent=state.schedule?.enabled?state.schedule.label+' · Laatste afgeronde import: '+(state.schedule.lastCompletedAt?new Date(state.schedule.lastCompletedAt).toLocaleString('nl-NL',{timeZone:'Europe/Amsterdam'}):'nog bezig')+(state.schedule.error?' · '+state.schedule.error:''):'Dagelijkse NS-import nog niet geactiveerd.';el('trainoctober').disabled=active;el('trainretry').disabled=active;clearTimeout(timer);if(active)timer=setTimeout(load,3000);}catch(e){el('trainprogress').textContent=e.message;}}
el('trainimport').onclick=async()=>{try{el('trainimport').disabled=true;await request('/import',{});await load();}catch(e){el('trainprogress').textContent=e.message;el('trainimport').disabled=false;}};
el('trainscan').onclick=async()=>{try{el('trainscan').disabled=true;await request('/start',{trips:el('traintrips').value.split(/[,;\s]+/).filter(Boolean)});await load();}catch(e){el('trainprogress').textContent=e.message;el('trainscan').disabled=false;}};
el('trainoctober').onclick=async()=>{try{el('trainoctober').disabled=true;el('trainprogress').textContent='Oktoberscan wordt gestart…';await request('/october',{});await load();}catch(e){el('trainprogress').textContent=e.message;el('trainoctober').disabled=false;}};
el('trainretry').onclick=async()=>{try{el('trainretry').disabled=true;el('trainprogress').textContent='Hercontrole wordt gestart…';await request('/october',{retry:true});await load();}catch(e){el('trainprogress').textContent=e.message;el('trainretry').disabled=false;}};
el('trainsearch').oninput=render;el('connectionsearch').oninput=render;
document.addEventListener('click',async e=>{if(['trains','connections'].includes(e.target.dataset.tab))await load();const id=e.target.dataset.trainConfirm;if(!id)return;try{await request('/review',{revision:state.revision,type:'train',id,confirmed:state.rows.find(r=>r.id===id).status!=='Bevestigd'});await load();}catch(e){el('trainprogress').textContent=e.message;}});
document.addEventListener('change',async e=>{const id=e.target.dataset.connection;if(!id||!e.target.value)return;try{await request('/review',{revision:state.revision,type:'connection',id,backup:e.target.value==='yes'});await load();}catch(err){alert(err.message);}});
})();
