import {randomBytes,createHash,createCipheriv,createDecipheriv} from 'node:crypto';
import {readFloraGoogle,writeFloraGoogle} from './flora-store.mjs';

export const GMAIL_SCOPE='https://www.googleapis.com/auth/gmail.readonly';
const mailbox='reservations@treinrondreis.nl';
const digest=s=>createHash('sha256').update(s).digest('base64url');
export function googleConfig(){return {id:process.env.FLORA_GOOGLE_CLIENT_ID||'',secret:process.env.FLORA_GOOGLE_CLIENT_SECRET||'',origin:process.env.FLORA_PUBLIC_ORIGIN||'https://treinbord.up.railway.app'};}
// Credentials live outside the public FloRA state, encrypted with a server-only key.
export function encryptGoogle(value,secret){const iv=randomBytes(12),key=createHash('sha256').update('flora-google-v1:'+secret).digest(),c=createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,c.update(JSON.stringify(value)),c.final(),c.getAuthTag()]).toString('base64url');}
export function decryptGoogle(value,secret){const b=Buffer.from(value,'base64url'),key=createHash('sha256').update('flora-google-v1:'+secret).digest(),c=createDecipheriv('aes-256-gcm',key,b.subarray(0,12));c.setAuthTag(b.subarray(-16));return JSON.parse(Buffer.concat([c.update(b.subarray(12,-16)),c.final()]).toString());}
export function createGoogle({configuration=googleConfig,read=readFloraGoogle,write=writeFloraGoogle,fetcher=fetch,now=()=>Date.now(),pause=ms=>new Promise(resolve=>setTimeout(resolve,ms))}={}){
 const config=()=>{const c=configuration();if(!c.id||!c.secret)throw Error('Stel eerst de Google-clientgegevens in Railway in.');return c;};
 const request=async(url,options)=>{for(let attempt=0;attempt<4;attempt++){let r;try{r=await fetcher(url,{...options,signal:AbortSignal.timeout(20000),redirect:'error'});}catch{if(attempt<3){await pause(1000*2**attempt);continue;}throw Error('Google is tijdelijk niet bereikbaar. Probeer opnieuw.');}if(r.ok)return r.json();let reason='';try{const body=await r.json();reason=body.error?.errors?.[0]?.reason||body.error?.status||'';}catch{}const temporary=[429,500,502,503,504].includes(r.status)||r.status===403&&/rateLimit|RESOURCE_EXHAUSTED|backendError/i.test(reason);if(temporary&&attempt<3){await pause(5000*2**attempt);continue;}if(temporary)throw Error('Google is tijdelijk overbelast of heeft de leeslimiet bereikt (HTTP '+r.status+'). Start de controle over enkele minuten opnieuw.');throw Error(r.status===401||r.status===400?'Google-toegang of zoekopdracht geweigerd (HTTP '+r.status+'). Probeer opnieuw; koppel Gmail opnieuw als dit aanhoudt.':'Google kon de aanvraag niet uitvoeren (HTTP '+r.status+'). Controleer de Gmail API-toegang.');}};
 const token=(c,body)=>request('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.id,client_secret:c.secret,...body}).toString()});
 const profile=access=>request('https://gmail.googleapis.com/gmail/v1/users/me/profile',{headers:{Authorization:'Bearer '+access}});
 const verify=p=>{if(p.emailAddress?.toLowerCase()!==mailbox)throw Error('Kies het Google-account '+mailbox+'. Deze mailbox komt niet overeen.');};
 const checkScope=t=>{if(!t.access_token||!t.scope||t.scope.split(' ').some(s=>s!==GMAIL_SCOPE)||!t.scope.split(' ').includes(GMAIL_SCOPE))throw Error('Google moet uitsluitend Gmail-leesrechten verlenen. Koppel opnieuw met alleen deze toestemming.');};
 return {
  async reader(){const c=config(),{value}=await read();if(!value.credentials)throw Error('Koppel Gmail eerst.');let access='',until=0;return async(path,query={})=>{if(!/^messages(?:\/[a-zA-Z0-9_-]+(?:\/attachments\/[a-zA-Z0-9_-]+)?)?$/.test(path))throw Error('Ongeldig Gmail-leesverzoek.');if(now()>=until){const t=await token(c,{grant_type:'refresh_token',refresh_token:decryptGoogle(value.credentials,c.secret).refresh});checkScope(t);access=t.access_token;until=now()+Math.max(0,(Number(t.expires_in)||3600)-120)*1000;}return request('https://gmail.googleapis.com/gmail/v1/users/me/'+path+'?'+new URLSearchParams(query),{headers:{Authorization:'Bearer '+access}});};},
  async status(){const c=configuration();if(!c.id||!c.secret)return {configured:false,connected:false,email:'Nog niet gekoppeld'};const {value}=await read();return {configured:true,connected:!!value.credentials,email:value.credentials?mailbox+' · alleen lezen':'Nog niet gekoppeld',lastTest:value.lastTest||null};},
  async start(session){const c=config(),{value,revision}=await read(),state=randomBytes(32).toString('base64url'),verifier=randomBytes(48).toString('base64url');value.pending={hash:digest(state),session:digest(session),expires:now()+600000,verifier:encryptGoogle(verifier,c.secret)};await write(value,revision);const u=new URL('https://accounts.google.com/o/oauth2/v2/auth');u.search=new URLSearchParams({client_id:c.id,redirect_uri:c.origin+'/seinhuis/flora/google/callback',response_type:'code',scope:GMAIL_SCOPE,access_type:'offline',prompt:'consent',login_hint:mailbox,state,code_challenge:digest(verifier),code_challenge_method:'S256'}).toString();return u.href;},
  async callback(params,session){const c=config(),{value,revision}=await read(),p=value.pending;if(!p||p.expires<now()||p.hash!==digest(params.get('state')||'')||p.session!==digest(session))throw Error('De koppelaanvraag is verlopen. Start Gmail koppelen opnieuw vanuit FloRA.');delete value.pending;const next=await write(value,revision);if(params.has('error'))throw Error('Geen toestemming ontvangen. Je kunt Gmail opnieuw koppelen.');const code=params.get('code');if(!code)throw Error('Google heeft geen autorisatiecode teruggegeven.');const t=await token(c,{grant_type:'authorization_code',code,redirect_uri:c.origin+'/seinhuis/flora/google/callback',code_verifier:decryptGoogle(p.verifier,c.secret)});checkScope(t);const account=await profile(t.access_token);verify(account);if(!t.refresh_token)throw Error('Google heeft geen blijvende toegang verleend. Koppel Gmail opnieuw.');value.credentials=encryptGoogle({refresh:t.refresh_token},c.secret);value.lastTest=new Date(now()).toISOString();await write(value,next);},
  async test(){const c=config(),{value,revision}=await read();if(!value.credentials)throw Error('Koppel Gmail eerst.');let credentials;try{credentials=decryptGoogle(value.credentials,c.secret);}catch{throw Error('De Google-clientgegevens zijn gewijzigd. Koppel Gmail opnieuw.');}const t=await token(c,{grant_type:'refresh_token',refresh_token:credentials.refresh});checkScope(t);verify(await profile(t.access_token));value.lastTest=new Date(now()).toISOString();await write(value,revision);return {ok:true};}
 };
}
export const floraGoogle=createGoogle();
