import {startOctober,runOctober} from './flora-trains-october.mjs';
import {readMail,writeMail,readFlora} from './flora-store.mjs';
import {floraGoogle} from './flora-google.mjs';
import {extractMessage} from './flora-mail-source.mjs';
import {parseNSTrains,connectionCandidates} from './flora-trains-parser.mjs';
export function createTrains({read=readMail,write=writeMail,google=floraGoogle,extract=extractMessage,bookings=readFlora}={}){
 let running=false;
 const data=async()=>{const {value,revision}=await read('trains-data');return {revision,rows:value.rows||[],connections:value.connections||[],checks:value.checks||{}};};
 async function status(){return (await read('trains-job')).value;}
 async function start(trips){if(!Array.isArray(trips)||trips.length<1||trips.length>3||trips.some(t=>!/^\d+A?$/i.test(String(t))))throw Error('Kies 1 tot 3 boekingsnummers.');trips=[...new Set(trips.map(t=>String(t).replace(/A$/i,'')))];const s=await bookings();if(trips.some(t=>!s.state.bookings.some(b=>String(b.index)===t)))throw Error('Boeking niet in FloRA gevonden. Lees Sanity eerst in.');if(!(await google.status()).connected)throw Error('Koppel Gmail eerst.');const old=await read('trains-job');if(['queued','running'].includes(old.value.status))throw Error('Er loopt al een treincontrole.');await write('trains-job',{status:'queued',trips,done:0,phase:'Kleine treincontrole klaar om te starten',at:new Date().toISOString()},old.revision);return status();}
 async function tick(){if(running)return;running=true;try{let job=await status();if(!['queued','running'].includes(job.status))return;if(job.mode==='october'){await runOctober({read,write,google,extract});return;}const put=async()=>{const fresh=await read('trains-job');await write('trains-job',{...job,at:new Date().toISOString()},fresh.revision);};const get=await google.reader();job.status='running';await put();for(const trip of job.trips.slice(job.done)){job.phase=trip+'A: NS-bevestigingen zoeken';await put();const raw=[],issues=[];let page='';do{const list=await get('messages',{q:'from:no-reply@confirmation.nsinternational.nl "'+trip+'A" -in:trash -in:spam',maxResults:'100',...(page?{pageToken:page}:{})});for(const {id} of list.messages||[]){const message=await get('messages/'+id,{format:'full'});const h=message.payload.headers||[],subject=h.find(x=>x.name.toLowerCase()==='subject')?.value||'';if(new RegExp('\\b'+trip+'A\\b','i').test(subject))raw.push(message);}page=list.nextPageToken||'';if(raw.length>=100&&page)throw Error('Meer dan 100 NS-berichten; beperk de controle handmatig.');}while(page);
 const latest=new Map();for(const m of raw){const sub=m.payload.headers.find(h=>h.name.toLowerCase()==='subject')?.value||'',ref=sub.match(/boekingscode\s*:?\s*([A-Z0-9]+)/i)?.[1];if(!ref){issues.push('NS-bericht zonder herkenbare boekingscode.');continue;}const old=latest.get(ref);if(!old||Number(old.internalDate)<Number(m.internalDate))latest.set(ref,m);}
 let rows=[];for(const m of latest.values()){job.phase=trip+'A: nieuwste bevestiging en tickets lezen';await put();const decoded=await extract(m,get);const parsed=parseNSTrains(decoded,trip);rows.push(...parsed);issues.push(...decoded.issues);if(!parsed.length)issues.push(decoded.subject+': geen actieve trein met uitleesbaar traject.');}
 const stored=await read('trains-data'),old=stored.value;rows=[...new Map(rows.map(r=>[r.id,r])).values()];const own=new Map((old.rows||[]).filter(r=>r.trip===trip).map(r=>[r.id,r]));rows=rows.map(r=>({...r,...(!issues.length&&own.get(r.id)?.status==='Bevestigd'?{status:'Bevestigd'}:{})}));const all=(old.rows||[]).filter(r=>r.trip!==trip).concat(rows),candidates=connectionCandidates(rows),prior=new Map((old.connections||[]).map(c=>[c.id,c]));const connections=(old.connections||[]).filter(c=>c.trip!==trip).concat(candidates.map(c=>({...c,...(prior.get(c.id)?{backup:prior.get(c.id).backup,status:prior.get(c.id).status}:{})})));
 await write('trains-data',{rows:all,connections,checks:{...(old.checks||{}),[trip]:{at:new Date().toISOString(),messages:raw.length,dossiers:latest.size,issues}}},stored.revision);job.done++;await put();}
 job.status='completed';job.phase='Kleine treincontrole afgerond. Controleer de gevonden treinen en aansluitingen.';await put();}catch(e){const old=await read('trains-job');await write('trains-job',{...old.value,status:'failed',phase:e.message,at:new Date().toISOString()},old.revision);}finally{running=false;}}
 async function review(input){const {value,revision}=await read('trains-data');if(input.revision!==revision)throw Error('Gegevens gewijzigd; vernieuw eerst.');if(input.type==='train'){const row=value.rows?.find(r=>r.id===input.id);if(!row)throw Error('Trein niet gevonden.');if(!row.number)throw Error('Treinnummer ontbreekt; deze bron moet eerst worden aangevuld.');row.status=input.confirmed?'Bevestigd':'Te beoordelen';}else{const row=value.connections?.find(r=>r.id===input.id);if(!row||typeof input.backup!=='boolean')throw Error('Kies een aansluiting en back-up ja of nee.');row.backup=input.backup;row.status='Bevestigd';}await write('trains-data',value,revision);return data();}
 return {data,status,start,tick,review,startOctober:()=>startOctober({read,write,google})};
}
export const floraTrains=createTrains();
