window.kkClaims=function(area,api,participant){const section=document.createElement('section');section.dataset.page='eindclaim';area.append(section);const make=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
section.innerHTML='<h1>Eindclaim indienen</h1><p>Voeg je scorekaart en de daadwerkelijk gemaakte reisplanning toe. Een screenshot mag ook. Extra bewijs is optioneel.</p><div class="claim-current" role="status"></div><form><p class="start"></p><label>Telefoonnummer voor nadere vragen<input name="phone" type="tel" required maxlength="40" autocomplete="tel"></label><label>Geclaimde kilometers<input name="km" type="number" min="0" max="10000" step="0.1" required></label><label>Eindstation<input name="endStation" list="claim-stations" required maxlength="200"></label><datalist id="claim-stations"></datalist><div class="row"><div><label>Einddatum<input name="endDate" type="date" required></label></div><div><label>Eindtijd<input name="endTime" type="time" required></label></div></div><aside class="claim-scorecard"><p><a class="secondary" href="/kilometerkampioen/scorekaart.xlsx" download="Hilta-scorekaart-2026.xlsx">Lege Hilta-scorekaart downloaden (.xlsx)</a></p><p>Vul je trajecten in en controleer de kilometers. Geef in het bestand aan of het volledig of deels door Hilta, of zelfstandig is ingevuld. Upload daarna je ingevulde scorekaart hieronder.</p><details><summary>Gebruiken in Google Spreadsheets</summary><p>Download de scorekaart, upload deze in Google Drive en kies Openen met Google Spreadsheets. Download na het invullen als Microsoft Excel (.xlsx) en voeg dat bestand hier toe.</p></details></aside><div class="claim-files"></div><label>Toelichting (optioneel)<textarea name="notes" maxlength="3000" rows="3"></textarea></label><label class="check"><input type="checkbox" name="reviewed" required>Ik heb mijn claim en bijlagen gecontroleerd.</label><small>Alleen jij en het bevoegde beheer kunnen deze eindclaim zien.</small><progress hidden max="100"></progress><p class="status" role="status"></p><button>Eindclaim indienen</button></form>';
const form=section.querySelector('form'),status=form.querySelector('.status'),progress=form.querySelector('progress'),current=section.querySelector('.claim-current');const draftKey='kk-claim-draft-'+participant.id,state=window.kkReliable.draft(draftKey);form.querySelector('.start').textContent='Start: '+(participant.startDate||'2026-09-19')+' · '+(participant.startTime||'nog niet ingevuld')+' · '+(participant.station||'startstation nog invullen bij Mijn deelname');
window.kkScorecardUI(section.querySelector('.claim-scorecard'),api);
const accept='.jpg,.jpeg,.png,.webp,.heic,.heif,.avif,.pdf,.doc,.docx,.csv,.xls,.xlsx,.txt,.ods,.odt';for(const [name,label] of [['scorecard','Scorekaart'],['planning','Gerealiseerde reisplanning'],['extra','Extra bewijs (optioneel)']]){const l=make('label',label),input=document.createElement('input');input.type='file';input.name=name;input.multiple=true;input.accept=accept;input.required=name!=='extra';l.append(input,make('small','Maximaal 8 bestanden. Foto: 15 MB. Document: 20 MB.'));form.querySelector('.claim-files').append(l);}
for(const name of ['phone','km','endStation','endDate','endTime','notes'])form.elements[name].value=state.value[name]||'';
function saveDraft(){for(const name of ['phone','km','endStation','endDate','endTime','notes'])state.value[name]=form.elements[name].value;state.save();}form.oninput=saveDraft;
if(!state.persistent)status.textContent='Je browser kan dit concept niet bewaren. Laat deze pagina open tot je ontvangstbevestiging ziet.';

fetch('/app/api/stations').then(r=>r.json()).then(d=>{for(const s of d.stations.filter(s=>s.country==='NL')){const o=document.createElement('option');o.value=s.name;section.querySelector('datalist').append(o);}}).catch(()=>{});
function showClaim(claim){current.replaceChildren(make('h2','Eindclaim ontvangen'),make('p',window.kkDate(claim.receivedAt)+' · '+claim.km+' km geclaimd · '+claim.endStation));for(const [name,label] of [['scorecard','Scorekaart'],['planning','Gerealiseerde planning'],['extra','Extra bewijs']]){for(const file of claim.attachments[name]){const b=make('button',label+': '+file.name);b.className='secondary';b.onclick=async()=>{b.disabled=true;try{const r=await api('claim-file?claim='+encodeURIComponent(claim.id)+'&file='+encodeURIComponent(file.id));const a=make('a','Download '+file.name);a.href=r.url;a.rel='noopener';a.target='_blank';b.after(a);a.click();}catch(e){current.append(make('p',e.message));}finally{b.disabled=false;}};current.append(b);}}const edit=make('button','Vervangende eindclaim indienen');edit.onclick=()=>{if(state.value.pending){recovery.refresh();return;}state.clear();form.hidden=false;status.textContent='De nieuwe eindclaim vervangt je vorige claim. Voeg alle bijlagen opnieuw toe.';};current.append(edit);form.hidden=true;}
function complete(result){state.clear();form.reset();showClaim(result.claim);current.scrollIntoView({block:'start'});}
const recovery=window.kkReliable.recovery(section,form,state,'claim-save',complete);
let loaded=false;async function load(){if(location.hash!=='#eindclaim'||loaded||!section.isConnected)return;loaded=true;try{const r=await api('claim');if(r.claim){if(state.value.pending?.submissionKey===r.claim.submissionKey){complete({claim:r.claim});recovery.refresh();form.hidden=true;}else if(!state.value.pending)showClaim(r.claim);}}catch(e){current.textContent=e.message;}}window.addEventListener('hashchange',load);load();
form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.reviewed=form.elements.reviewed.checked;data.submissionKey=state.value.id;for(const name of ['scorecard','planning','extra'])if(form.elements[name].files.length>8){status.textContent='Maximaal 8 bestanden per onderdeel.';return;}const controls=[...form.querySelectorAll('input,textarea,button')];controls.forEach(e=>e.disabled=true);try{for(const name of ['scorecard','planning','extra']){data[name]=[];for(const file of form.elements[name].files){data[name].push((await claimUpload(file,progress,status,state)).id);}}state.value.pending=data;saveDraft();const result=await window.kkReliable.send('claim-save',data,status);complete(result);}catch(e){if([400,413,415,422].includes(e.status)){delete state.value.pending;state.save();}saveDraft();recovery.refresh();if(state.value.pending)recovery.report(e);else window.kkReliable.showError(status,e,'Eindclaim',false);}finally{controls.forEach(e=>e.disabled=false);progress.hidden=true;}};
};
function claimUpload(file,progress,status,state){const ext=file.name.split('.').pop().toLowerCase(),types={pdf:'application/pdf',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',csv:'text/csv',xls:'application/vnd.ms-excel',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',txt:'text/plain',ods:'application/vnd.oasis.opendocument.spreadsheet',odt:'application/vnd.oasis.opendocument.text',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',heic:'image/heic',heif:'image/heif',avif:'image/avif'},type=types[ext];if(!type)return Promise.reject(Error('Dit bestandstype wordt niet ondersteund.'));if(file.size>(type.startsWith('image/')?15000000:20000000))return Promise.reject(Error(file.name+' is te groot.'));return window.kkReliable.upload(file,type,true,state,progress,status);}
