window.kkForms=function(content,api,participant){
 const area=document.createElement('div');content.append(area);window.kkClaims(area,api,participant);window.kkCommunity(area,api);
 if(participant.approval!=='approved'&&(participant.manualRegistration||participant.approval)){const note=document.createElement('p');note.textContent='Je kunt updates bekijken en delen. Privébewijs komt beschikbaar zodra de organisatie je aanmelding heeft goedgekeurd. Vernieuw deze pagina om je status bij te werken.';note.dataset.page='bewijs';area.append(note);}
 for(const kind of (participant.approval!=='approved'&&(participant.manualRegistration||participant.approval)?['update']:['proof','update'])){
  const section=document.createElement('section');section.dataset.page=kind==='proof'?'bewijs':'delen';area.append(section);
  section.innerHTML=`<a class="quiet-link" href="#insturen">← Terug</a><h1>${kind==='proof'?'Bewijs insturen':'Update delen'}</h1><form>${kind==='update'?'<label>Titel (optioneel)<input name="title" maxlength="120"></label>':''}<label>${kind==='proof'?'Locatie foto / station':'Hoe gaat je reis?'}<textarea rows="${kind==='proof'?1:4}" maxlength="${kind==='proof'?200:10000}" ${kind==='update'?'required':''}></textarea></label><label>Foto’s of video<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/heic,image/heif,image/avif,video/mp4,video/quicktime,video/webm"></label><small>Maximaal vier foto’s (15 MB per foto) en één video (100 MB, 60 seconden). ${kind==='update'?'Foto of video is optioneel.':'Minimaal één foto verplicht. Bewijs is alleen zichtbaar voor jou en het beheer.'}</small>${kind==='proof'?'<button type="button" class="secondary location">Locatie toevoegen</button>':''}<p class="locationNote"></p><progress max="100" value="0" hidden aria-label="Uploadvoortgang"></progress><p role="status" class="status"></p><button type="submit">${kind==='proof'?'Bewijs insturen':'Update insturen'}</button></form>`;
  const form=section.querySelector('form'),status=section.querySelector('.status'),progress=section.querySelector('progress'),files=form.querySelector('input[type=file]'),textarea=form.querySelector('textarea');
  const draftKey='kk-draft-'+participant.id+'-'+kind;try{const draft=JSON.parse(localStorage.getItem(draftKey)||'null');if(draft){textarea.value=draft.text||'';if(form.elements.title)form.elements.title.value=draft.title||'';status.textContent='Je concept is hersteld. Kies eventuele foto’s of video opnieuw.';}}catch{}
  form.addEventListener('input',()=>{try{localStorage.setItem(draftKey,JSON.stringify({text:textarea.value,title:form.elements.title?.value||''}));}catch{}});
  const previews=document.createElement('div');previews.className='upload-previews';files.after(previews);let chosen=[],objectUrls=[];
  function showChosen(){for(const url of objectUrls)URL.revokeObjectURL(url);objectUrls=[];previews.replaceChildren();chosen.forEach((file,index)=>{const card=document.createElement('div'),url=URL.createObjectURL(file),media=document.createElement(file.type.startsWith('video/')?'video':'img');objectUrls.push(url);media.src=url;if(media.tagName==='VIDEO')media.controls=true;else media.alt=file.name;const remove=document.createElement('button');remove.type='button';remove.textContent='Verwijderen';remove.onclick=()=>{chosen.splice(index,1);showChosen();};card.append(media,document.createTextNode(file.name),remove);previews.append(card);});}
  files.onchange=()=>{chosen=[...files.files];showChosen();};
  let stations=[];
  if(kind==='proof'){
   const label=textarea.parentElement,input=document.createElement('input'),choices=document.createElement('datalist'),note=document.createElement('small');input.type='text';input.value=textarea.value;input.required=true;input.maxLength=200;input.setAttribute('list','proof-stations');choices.id='proof-stations';note.textContent='Kies een station uit de suggesties of vul een andere locatie in.';textarea.hidden=true;label.append(input,choices,note);
   fetch('/app/api/stations').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{stations=data.stations.filter(s=>s.country==='NL');for(const station of stations){const option=document.createElement('option');option.value=station.name;choices.append(option);}}).catch(()=>{note.textContent='Stationslijst niet beschikbaar. Je kunt de locatie zelf invullen.';});
   input.oninput=()=>{textarea.value=input.value;};
  }
  let location=null,id=crypto.randomUUID();const uploaded=new Map();
  const locate=section.querySelector('.location');if(locate)locate.onclick=()=>{
   if(!navigator.geolocation){status.textContent='Locatie delen wordt niet ondersteund. Je kunt wel bewijs insturen.';return;}
   locate.disabled=true;navigator.geolocation.getCurrentPosition(p=>{location={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:p.timestamp};section.querySelector('.locationNote').textContent=`Locatie vastgelegd om ${new Date(p.timestamp).toLocaleTimeString('nl-NL')} (nauwkeurigheid ${Math.round(p.coords.accuracy)} meter).`;locate.disabled=false;},()=>{status.textContent='Locatie niet beschikbaar. Controleer je toestemming of stuur bewijs zonder locatie.';locate.disabled=false;},{enableHighAccuracy:true,timeout:15000,maximumAge:0});
  };
  form.onsubmit=async e=>{
   e.preventDefault();const selected=[...chosen];let images=0,videos=0;
   for(const f of selected){const video=f.type.startsWith('video/');video?videos++:images++;if(f.size>(video?100000000:15000000)){status.textContent='Een bestand is te groot. Foto maximaal 15 MB; video maximaal 100 MB.';return;}}
   if(images>4||videos>1){status.textContent='Kies maximaal vier foto’s en één video.';return;}
   if(kind==='proof'&&!images){status.textContent='Voeg minimaal één foto toe aan je bewijs.';return;}
   const controls=[...form.querySelectorAll('input,textarea,button')];controls.forEach(el=>el.disabled=true);status.textContent='Bezig met versturen…';
   try{
    const media=[];for(const f of selected){if(!uploaded.has(f)){progress.hidden=false;uploaded.set(f,(await uploadFile(f,progress,status)).id);}media.push(uploaded.get(f));}
    const station=kind==='proof'?stations.find(s=>s.name===textarea.value):null;const saved=await api('submit',{id,kind,title:form.elements.title?.value||'',text:textarea.value,station:kind==='proof'?textarea.value:'',stationId:station?.id||'',location,media});form.reset();chosen=[];showChosen();try{localStorage.removeItem(draftKey);}catch{}uploaded.clear();location=null;id=crypto.randomUUID();section.querySelector('.locationNote').textContent='';status.textContent='Je inzending is opgeslagen.';const thanks=area.querySelector('[data-page="bedankt"]');thanks.replaceChildren();const title=document.createElement('h1'),note=document.createElement('p');title.textContent=kind==='proof'?'✓ Bewijs ontvangen':'✓ Update ontvangen';note.textContent='Je inzending is opgeslagen op '+window.kkDate(saved.submission.receivedAt||saved.submission.createdAt)+'.';thanks.append(title,note);if(kind==='proof'){const hilta=document.createElement('section');thanks.append(hilta);window.kkHilta(hilta,api,saved.submission.id);}for(const [label,target] of (kind==='proof'?[['Nieuw bewijs insturen','bewijs'],['Mijn reis en bewijs bekijken','mijn-reis']]:[['Nieuwe update insturen','delen'],['Alle updates bekijken','updates'],['Mijn updates bekijken','mijn-updates']])){const link=document.createElement('a');link.className='button';link.textContent=label;link.href='#'+target;link.onclick=()=>{history.dataset.kind=kind;};thanks.append(link);}locationHash('bedankt');
   }catch(error){status.textContent=error.message+' Je tekst en bestandskeuze zijn behouden. Je kunt opnieuw verzenden.';}
   finally{progress.hidden=true;controls.forEach(el=>el.disabled=false);}
  };
 }
 const thanks=document.createElement('section');thanks.dataset.page='bedankt';area.append(thanks);
 const history=document.createElement('section');history.dataset.page='inzendingen';area.append(history);history.innerHTML='<h2>Mijn inzendingen</h2><button class="secondary">Inzendingen bekijken</button><div></div>';
 history.querySelector('button').textContent='Vernieuwen';history.querySelector('button').onclick=async()=>{const list=history.querySelector('div');list.className='kk-timeline';list.textContent='Laden…';try{const data=await api('submissions');list.replaceChildren();for(const item of data.submissions.filter(x=>!history.dataset.kind||x.kind===history.dataset.kind)){const card=window.kkCard(item,api);list.append(card);if(item.kind==='proof'){const route=document.createElement('button');route.textContent='Trajecten nakijken met Hilta';route.onclick=()=>{const box=document.createElement('section');card.append(box);route.disabled=true;window.kkHilta(box,api,item.id);};card.append(route);}}if(!list.children.length)list.textContent='Je hebt hier nog geen inzendingen.';}catch(e){list.textContent=e.message;}};
};
function uploadFile(file,progress,status){return new Promise((resolve,reject)=>{
 const xhr=new XMLHttpRequest();xhr.open('POST','/kilometerkampioen/api/upload');xhr.setRequestHeader('Content-Type',file.type||({jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',avif:'image/avif',heic:'image/heic',heif:'image/heif',mp4:'video/mp4',mov:'video/quicktime',webm:'video/webm'}[file.name.split('.').pop().toLowerCase()]||'application/octet-stream'));xhr.timeout=180000;
 xhr.upload.onprogress=e=>{if(e.lengthComputable){progress.value=Math.round(e.loaded/e.total*100);status.textContent=file.name+' · '+(progress.value===100?'Bestand controleren en opslaan…':`Uploaden: ${progress.value}%`);}};
 xhr.onload=()=>{let v;try{v=JSON.parse(xhr.responseText);}catch{reject(Error('Upload is niet bevestigd.'));return;}xhr.status>=200&&xhr.status<300?resolve(v):reject(Error(v.error||'Upload mislukt.'));};xhr.onerror=xhr.ontimeout=()=>reject(Error('Verbinding onderbroken.'));xhr.send(file);
});}

function locationHash(value){window.location.hash=value;}
