window.kkHilta=async function(box,api,proofId){
 const make=(tag,text)=>{const n=document.createElement(tag);n.textContent=text||'';return n;};box.append(make('h2','Trajecten nakijken met Hilta'));const status=make('p','Vorige bewijs en scorekaart laden…');status.setAttribute('role','status');box.append(status);
 try{
 const context=await api('hilta?proofId='+encodeURIComponent(proofId));status.textContent='Je bewijs is opgeslagen. De route is pas door jou bevestigd nadat je die hieronder hebt nagekeken.';
 const notice=make('p',context.notice);notice.className='hilta-notice';box.append(notice);
 const info=make('p',context.previousProofId?'Vanaf het vorige ontvangen bewijs: '+context.from+' ('+new Date(context.previousReceivedAt).toLocaleString('nl-NL')+').':'Vanaf je startstation. Controleer of dit het begin van je reis is.');box.append(info,make('p','Naar: '+context.to));
 box.append(make('small','Hilta gebruikt de volgorde van ontvangen bewijs. Later ingestuurd bewijs kan van een eerdere reis zijn. Bevestig alleen als deze volgorde klopt. Bij een onjuiste volgorde: laat de organisatie dit controleren.'));
 const choices=make('datalist');choices.id='hilta-stations-'+proofId;for(const name of context.stations){const o=document.createElement('option');o.value=name;choices.append(o);}box.append(choices);
 const startLabel=make('label','Startstation'),start=make('input');start.value=context.from;start.setAttribute('list',choices.id);startLabel.append(start);if(!context.previousProofId)box.append(startLabel);
 const form=make('form'),viaLabel=make('label','Via-stations, in reisvolgorde'),viaList=make('div'),add=make('button','Via-station toevoegen'),calculate=make('button','Route berekenen');add.type='button';calculate.type='submit';form.append(viaLabel,viaList,add,calculate);box.append(form);
 function addVia(value=''){const row=make('div');row.className='row';const input=make('input');input.value=value;input.maxLength=200;input.setAttribute('list',choices.id);input.setAttribute('aria-label','Via-station');const remove=make('button','Verwijderen');remove.type='button';remove.onclick=()=>{row.remove();result.replaceChildren();status.textContent='Route gewijzigd. Bereken opnieuw voordat je bevestigt.';};row.append(input,remove);viaList.append(row);}
 add.onclick=()=>{if(viaList.children.length<20)addVia();result.replaceChildren();};
 const result=make('div');box.append(result);let proposal=null;form.oninput=()=>{result.replaceChildren();status.textContent='Route gewijzigd. Bereken opnieuw voordat je bevestigt.';};start.oninput=form.oninput;
 function show(p){proposal=p;result.replaceChildren();if(p.status==='participant-confirmed')result.append(make('p','Door jou nagekeken en bevestigd op '+new Date(p.confirmedAt).toLocaleString('nl-NL')+'. Nog geen definitieve wedstrijdscore.'));
 result.append(make('h3',p.km.toLocaleString('nl-NL')+' km — inschatting van Hilta'),make('p','Kortste scorekaartverbinding via de opgegeven stations. Controleer ook eventuele omwegen, heen-en-terugritten en de HSL.'));
 const list=make('ol');for(const edge of p.segments)list.append(make('li',edge.from+' → '+edge.to+(edge.label.includes('via HSL')?' (via HSL)':'')+' · '+edge.km.toLocaleString('nl-NL')+' km'));result.append(list);if(!p.segments.length)result.append(make('p','Het begin- en eindstation zijn hetzelfde: 0 km. Heb je tussendoor gereisd? Voeg de via-stations toe.'));
 if(p.status==='participant-confirmed')return;
 const label=make('label'),check=make('input');check.type='checkbox';label.className='check';label.append(check,document.createTextNode('Ik heb alle trajecten, kilometers en de volgorde van mijn bewijs nagekeken. Dit is de route die ik heb afgelegd.'));
 const confirm=make('button','Deze route klopt — bevestigen');confirm.type='button';confirm.disabled=true;check.onchange=()=>confirm.disabled=!check.checked;
 confirm.onclick=async()=>{confirm.disabled=true;try{const r=await api('hilta-confirm',{proposalId:proposal.id,reviewed:check.checked});show(r.confirmation);status.textContent='Je routebevestiging is opgeslagen. Het beheer kan deze controleren.';}catch(e){status.textContent=e.message;confirm.disabled=!check.checked;}};result.append(label,confirm);
 }
 form.onsubmit=async e=>{e.preventDefault();calculate.disabled=true;result.replaceChildren();status.textContent='Hilta berekent een nieuw voorstel…';try{const r=await api('hilta-propose',{proofId,startStation:start.value,via:[...viaList.querySelectorAll('input')].map(n=>n.value.trim()).filter(Boolean)});show(r.proposal);status.textContent='Controleer het voorstel. Bij een andere route voeg je via-stations toe en bereken je opnieuw.';}catch(e){status.textContent=e.message+' Je bewijs blijft opgeslagen. Er is geen route bevestigd.';}finally{calculate.disabled=false;}};
 if(context.current){for(const v of context.current.via)addVia(v);if(!context.previousProofId)start.value=context.current.from;show(context.current);}else if(context.from&&context.to)form.requestSubmit();else status.textContent='Vul je startstation in om een voorstel te maken. Je bewijs is al opgeslagen.';
 }catch(e){status.textContent='Je bewijs blijft opgeslagen. Hilta kon niet laden: '+e.message;}
};
