import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Worker} from 'node:worker_threads';
import {DatabaseSync} from 'node:sqlite';
import {parseFrenchPlan,decodeFrenchLive,frenchRows,frenchStations,restoreFrance,frenchPayload} from './france.mjs';
import {initBoardCache,saveBoardCache} from './board-cache.mjs';
import {initBoardAdmin,defaultBoardSettings,duplicateBoard,duplicatePayload,applyBoardSettings} from './board-admin.mjs';
const bytes=fs.readFileSync(new URL('../france/plan.zip',import.meta.url)),feed=decodeFrenchLive(fs.readFileSync(new URL('../france/live.pb',import.meta.url))),now=feed.header.timestamp*1000;
const plan=parseFrenchPlan(bytes,now),rows=frenchRows(plan,feed,now);
assert.equal(new Set(plan.rows.map(r=>r.page)).size,21);assert(rows.some(r=>r.hasRealtime));assert(rows.some(r=>!r.hasRealtime));assert(rows.every(r=>r.transportMode==='rail'));
const p=plan.rows.find(r=>r.plannedTimestamp>now&&r.plannedTimestamp<now+86400000);
const mk=(relationship,stop)=>({header:{timestamp:now/1000},entity:[{tripUpdate:{trip:{tripId:p.tripId,startDate:p.date,scheduleRelationship:relationship},stopTimeUpdate:stop?[{stopId:p.stopId,...stop}]:[]}}]});
const row=f=>frenchRows(plan,f,now).find(r=>r.sourceTripId===p.tripId&&r.plannedTimestamp===p.plannedTimestamp&&r.page===p.page);
assert.equal(row(mk(0,{departure:{delay:300}})).delay,5);
assert(row(mk(3)).cancelled);assert(row(mk(0,{scheduleRelationship:1})).cancelled);
assert(!row(mk(0,{scheduleRelationship:2,departure:{delay:600}})).hasRealtime);
const wrong=mk(0,{departure:{delay:600}});wrong.entity[0].tripUpdate.trip.startDate='19990101';assert(!row(wrong).hasRealtime);
const stale=mk(0,{departure:{delay:600}});stale.header.timestamp-=301;assert(!row(stale).hasRealtime);
const workerPlan=await new Promise((resolve,reject)=>{const w=new Worker(new URL('./france.mjs',import.meta.url),{workerData:{franceBytes:bytes,now}});w.once('message',resolve);w.once('error',reject);});assert.equal(workerPlan.rows.length,plan.rows.length);
await initBoardCache({backend:'sqlite',sqlite:new DatabaseSync(':memory:')});await saveBoardCache('SNCF:plan',{plan,planDay:'20260910'});await saveBoardCache('SNCF:live',feed);await restoreFrance();
for(const page of Object.keys(frenchStations))assert(frenchPayload(page,now).departures.all.length>0);
await initBoardAdmin({config:{},swissStations:{},norwegianStations:{},belgianStations:{},frenchStations,getPayload:p=>frenchPayload(p,now),matchDirection:(row,d)=>row.futureRoute.some(s=>d.futureStops.includes(s))});
const copy=await duplicateBoard('paris-nord',defaultBoardSettings('paris-nord'));assert.equal(copy.id,'paris-nord-1');assert(duplicatePayload(copy.id).departures.all.length>0);
const settings=defaultBoardSettings('lyon'),target=frenchPayload('lyon',now).departures.all[0].futureRoute[0];settings.directions=[{id:'test',enabled:true,label:target,futureStops:[target],limit:8}];assert(applyBoardSettings('lyon',frenchPayload('lyon',now),settings).quick[0].trains.length>0);
console.log('PASS: 21 stations, '+plan.rows.length+' planned departures, '+rows.filter(r=>r.hasRealtime).length+' realtime matches; worker, cache restore, cancellations, missing/stale/wrong-date updates, filters and duplicate');
