const $=s=>document.querySelector(s),view=$('#view'),editor=$('#editor'),key='treinreiziger-stations-v1';
const styles=['trr','db','it','uk','sncf','rustig','compact'];
let favorites=[],catalog=[],cache=new Map(),editing=null,timer,renderId=0,installPrompt;
function defaultStation(){return {id:'voorbeeld-utrecht',station:'nl-ut',name:'Utrecht Centraal',country:'NL',style:'trr',filters:[
 {label:'Eerste trein richting Amsterdam C',direction:'Amsterdam C'},
 {label:'Eerste trein richting Rotterdam (via Gouda)',direction:'Rotterdam Centraal',via:'Gouda'},
 {label:'Eerste trein richting Eindhoven',direction:'Eindhoven'},
 {label:'Eerste trein richting Amersfoort',direction:'Amersfoort'},
 {label:'Eerste trein richting Schiphol',direction:'Amsterdam Zuid'},
 {label:'Eerste intercity richting Arnhem',direction:'Arnhem',types:'IC'},
 {label:'Eerste ICE richting Duitsland',direction:'Köln; Dusseldorf; Frankfurt',types:'ICE'}
]};}
try{const stored=localStorage.getItem(key);favorites=stored===null?[defaultStation()]:JSON.parse(stored);if(!Array.isArray(favorites))favorites=[];if(stored===null)localStorage.setItem(key,JSON.stringify(favorites));}catch{favorites=[defaultStation()];}

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function save(){try{localStorage.setItem(key,JSON.stringify(favorites));}catch{toast('Opslaan is geblokkeerd. Je instellingen blijven alleen deze sessie beschikbaar.');}}
async function api(path,options){const r=await fetch('/app/api/'+path,{...options,signal:AbortSignal.timeout(75000)});const j=await r.json();if(!r.ok)throw Error(j.error||'Ophalen mislukt');return j;}
function header(k,title,description){return `<div class="eyebrow">${esc(k)}</div><h1>${esc(title)}</h1><p class="intro">${esc(description)}</p>`;}
function status(r){return r.cancelled?'<span class="status cancel" title="Geannuleerd">Uitval</span>':!r.hasRealtime?'<span class="status" title="Alleen dienstregeling, geen actuele meting" aria-label="Alleen dienstregeling">◷</span>':r.delay>0?`<span class="status ${r.delay>=5?'late':''}" aria-label="${esc(r.delay)} minuten vertraging">+${esc(r.delay)}</span>`:'<span class="status ok" aria-label="Actueel: op tijd" title="Actueel: op tijd">✓</span>';}
function matches(r,filters){return !filters?.length||filters.some(f=>{const route=[...(r.route||[]).map(s=>typeof s==='string'?s:s.name||s.station||''),r.to].map(norm);const has=t=>String(t).split(';').map(x=>norm(x.trim())).filter(Boolean).some(t=>route.some(s=>s.includes(t)));const types=(f.types||'').split(/[,;]/).map(x=>x.trim().toUpperCase()).filter(Boolean);return (!f.direction||has(f.direction))&&(!f.via||has(f.via))&&(!f.exclude||!has(f.exclude))&&(!types.length||types.some(t=>String(r.category||'').toUpperCase()===t));});}
function rowsFor(f,p){return(p.departures||[]).filter(r=>matches(r,f.filters));}
async function board(f){const c=cache.get(f.station);if(c&&Date.now()-c.at<30000)return c.data;const data=await api('board/'+encodeURIComponent(f.station));cache.set(f.station,{at:Date.now(),data});return data;}
function photo(src, title, eager=false){return src?`<img class="content-photo" src="${esc(src)}" alt="" loading="${eager?'eager':'lazy'}" decoding="async">`:'';}
function newsCards(items){return items.map((n,i)=>`<article class="news-item ${n.image?'has-photo':''}"><a href="${esc(n.url)}" target="_blank" rel="noopener">${photo(n.image,n.title,i<2)}<div class="news-copy"><h2>${esc(n.title)}</h2><time>${Number.isFinite(Date.parse(n.date))?esc(new Date(n.date).toLocaleDateString('nl-NL',{day:'numeric',month:'long'})):''}</time><p>${esc(n.summary)}</p><span class="read">Lees verder ↗</span></div></a></article>`).join('');}
const countryNames=new Intl.DisplayNames(['nl'],{type:'region'});
const countryName=code=>code?countryNames.of(code):'Overige bestemmingen';
function tripCards(items){return items.map(t=>`<article class="trip-card"><a href="${esc(t.url)}" target="_blank" rel="noopener">${photo(t.image,t.title)}<div class="trip-copy"><div class="trip-meta">${esc(countryName(t.country))}${t.duration?' · '+esc(t.duration)+' '+esc(t.durationType):''}</div><h3>${esc(t.title)}</h3><p>${esc(t.summary)}</p><div class="trip-bottom">${t.price?`<span>Vanaf <strong>${esc(new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',minimumFractionDigits:0,maximumFractionDigits:2}).format(t.price))}</strong> <small>${esc(t.priceType)}</small></span>`:'<span>Bekijk de reis</span>'}<span aria-label="Opent op Treinrondreis.nl">↗</span></div></div></a></article>`).join('');}
function sectionHeading(title,href,label){return `<div class="section-heading"><h2>${esc(title)}</h2>${href?`<a href="${esc(href)}">${esc(label)} →</a>`:''}</div>`;}
function nextRows(rows){return rows.slice(0,2).map(r=>`<div class="mini-departure"><strong class="time">${esc(r.time)}</strong><div class="mini-destination">${esc(r.to)}<small>${esc(r.category)} ${esc(r.number)}</small></div><span class="mini-track"><small>spoor</small>${esc(r.track||'—')}</span>${status(r)}</div>`).join('');}
async function renderInternational(hash,token){
 const part=hash.split('/')[1]||'', country=hash.split('/')[2]||'';
 const back='<a class="back-link" href="#internationaal">← Internationaal</a>';
 if(part==='tickets'||part==='treinen'){
  view.innerHTML=back+header('',part==='tickets'?'Tickets & Treinpassen':'Treinen','')+(part==='tickets'?'<section class="card external"><p>Bekijk het actuele aanbod treintickets bij Treinreiziger. Informatie over Interrail en andere treinpassen volgt.</p><a class="button primary" href="https://tickets.treinreiziger.nl/" target="_blank" rel="noopener">Bekijk treintickets ↗</a></section>':'<section class="card external"><p>Hier vind je straks informatie over internationale treinen en nachttreinen.</p><a href="#internationaal/nieuws">Lees alvast het internationale nieuws →</a></section>');return;
 }
 if(part==='nieuws'){
  view.innerHTML=back+header('','Internationaal nieuws','')+'<div id="international-news" class="news-list"><p role="status">Nieuws laden…</p></div>';
  try { const j=await api('news');if(token!==renderId)return;const items=j.items.filter(n=>n.categories?.some(c=>norm(c)==='internationaal'));$('#international-news').innerHTML=(j.stale?'<p>Dit is het laatst opgehaalde nieuws.</p>':'')+(items.length?newsCards(items):'<p>Er staan momenteel geen internationale berichten in de nieuwsfeed.</p>'); }catch(e){if(token===renderId)$('#international-news').textContent=e.message;}return;
 }
 const overview=!part;
 view.innerHTML=(overview?'':back)+header('',overview?'Ontdek Europa per trein':part==='bestemmingen'?'Bestemmingen':'Rondreizen','')+(overview?`<div class="topic-menu" aria-label="Ontdek internationaal">${[['rondreizen','Rondreizen','◎'],['tickets','Tickets & Treinpassen','▱'],['nieuws','Internationaal Nieuws','▤'],['bestemmingen','Bestemmingen','⌖'],['treinen','Treinen','⇄']].map(([path,title,icon])=>`<a href="#internationaal/${path}"><span class="topic-icon" aria-hidden="true">${icon}</span><span>${title}</span><span aria-hidden="true">›</span></a>`).join('')}</div>`:'')+'<div id="trip-content"><p role="status">Rondreizen laden…</p></div>';
 try {
  const j=await api('trips');if(token!==renderId)return;
  const countries=[...new Set(j.items.map(t=>t.country).filter(Boolean))].sort((a,b)=>countryName(a).localeCompare(countryName(b),'nl'));
  const stale=j.stale?'<p class="source">Dit is het laatst opgehaalde aanbod. Controleer de actuele prijs bij de aanbieder.</p>':'';
  if(part==='bestemmingen'){$('#trip-content').innerHTML=stale+'<div class="countries">'+countries.map(c=>`<a href="#internationaal/rondreizen/${c}">${esc(countryName(c))}<span>→</span></a>`).join('')+'</div>';return;}
  const items=overview?j.items.filter(t=>t.image&&t.price).slice(0,6):j.items.filter(t=>!country||t.country===country);
  $('#trip-content').innerHTML=stale+(overview?sectionHeading('Rondreizen','#internationaal/rondreizen','Alle rondreizen'):`<label class="country-filter">Filter op land<select id="trip-country"><option value="">Alle landen</option>${countries.map(c=>`<option value="${c}" ${c===country?'selected':''}>${esc(countryName(c))}</option>`).join('')}</select></label><p class="result-count">${items.length} reizen</p>`)+`<div class="trip-grid">${items.length?tripCards(items):'<p>Geen rondreizen gevonden voor dit land.</p>'}</div><p class="source">Reisaanbod van Treinrondreis.nl. Prijzen zijn vanafprijzen; beschikbaarheid en definitieve prijs staan bij de aanbieder.</p>`;
  if(overview){$('#trip-content').insertAdjacentHTML('beforeend',sectionHeading('Internationaal nieuws','#internationaal/nieuws','Meer nieuws')+'<div id="international-news" class="news-list"></div>');try{const n=await api('news');if(token!==renderId)return;const items=n.items.filter(n=>n.categories?.some(c=>norm(c)==='internationaal')).slice(0,3);$('#international-news').innerHTML=items.length?newsCards(items):'<p>Er staan momenteel geen internationale berichten in de nieuwsfeed.</p>';}catch{if(token===renderId)$('#international-news').textContent='Het nieuws is tijdelijk niet bereikbaar.';}}
 }catch(e){if(token===renderId)$('#trip-content').innerHTML=`<div class="empty"><p>${esc(e.message)}</p><button id="retry">Probeer opnieuw</button></div>`;}
}
document.addEventListener('change',e=>{if(e.target.id==='trip-country')location.hash='internationaal/rondreizen'+(e.target.value?'/'+e.target.value:'');});
document.addEventListener('error',e=>{if(e.target.matches?.('.content-photo')){e.target.hidden=true;e.target.closest('.news-item')?.classList.remove('has-photo');}},true);

async function render(){const token=++renderId,hash=location.hash.slice(1)||'nieuws';document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#'+(hash.startsWith('station/')?'tijden':hash.startsWith('internationaal')?'internationaal':hash))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});

 if(await window.cmsRender?.(hash,view,token,t=>t===renderId))return;
 if(hash==='internationaal'||hash.startsWith('internationaal/')){await renderInternational(hash,token);return;}
 if(hash==='nieuws'){view.innerHTML='<div id="news-list" class="news-list"><p role="status">Nieuws laden…</p></div>';try{const j=await api('news');if(token!==renderId)return;$('#news-list').innerHTML=(j.stale?'<p>De verbinding is tijdelijk onderbroken. Dit is het laatst opgehaalde nieuws.</p>':'')+newsCards(j.items);}catch(e){if(token===renderId)$('#news-list').innerHTML='<div class="empty"><p>'+esc(e.message)+'</p><button id="retry">Probeer opnieuw</button></div>';}return;}
 if(hash==='tijden'){
  view.innerHTML='<div class="station-toolbar"><p>Jouw stations, jouw vertrekfilters</p><button id="add-station" class="primary">+ Station</button></div>'+(favorites.length?'<div class="station-grid">'+favorites.map(f=>'<article class="card station-card '+esc(f.style)+'"><button class="edit" data-edit="'+esc(f.id)+'" aria-label="Bewerk '+esc(f.name)+'">Bewerk</button><a class="station-link" href="#station/'+encodeURIComponent(f.id)+'"><h2>'+esc(f.name)+'</h2><p class="filter-description">'+esc((f.filters||[]).length>2?f.filters.length+' vertrekfilters':(f.filters||[]).map(x=>x.label||x.direction||x.types||'Filter').join(' · ')||'Alle vertrekken')+'</p><div data-next="'+esc(f.id)+'"><p class="muted">Vertrekken laden…</p></div><span class="check-board">Check vertrekbord '+esc(f.name)+' →</span></a><a class="button all-departures" href="#station/'+encodeURIComponent(f.id)+'?all=1">Alle vertrektijden →</a></article>').join('')+'</div>':'<div class="empty"><h2>Waar begint jouw reis?</h2><p>Voeg een station toe en bekijk je eerstvolgende vertrekken.</p><button id="empty-add" class="primary">Kies je eerste station</button></div>');
  await Promise.all(favorites.map(async f=>{try{const p=await board(f);if(token!==renderId)return;const el=[...document.querySelectorAll('[data-next]')].find(x=>x.dataset.next===f.id);if(el)el.innerHTML=nextRows(rowsFor(f,p))||'<p class="muted">Geen passend vertrek beschikbaar.</p>';}catch(e){if(token!==renderId)return;const el=[...document.querySelectorAll('[data-next]')].find(x=>x.dataset.next===f.id);if(el)el.textContent=e.message;}}));return;
 }
 if(hash.startsWith('station/')){const f=favorites.find(f=>f.id===decodeURIComponent(hash.slice(8).split('?')[0]));if(!f){location.hash='tijden';return;}view.innerHTML=`<a class="button" href="#tijden">← Mijn stations</a><div class="heading"><div>${header(f.country,f.name,hash.includes('?all=1')?'Alle vertrektijden':'Jouw gefilterde vertrekbord')}</div><button data-edit="${esc(f.id)}">Instellingen</button></div><div id="departures"><p role="status">Vertrekken laden…</p></div>`;try{const p=await board(f);if(token!==renderId)return;const all=new URLSearchParams(hash.split('?')[1]||'').get('all')==='1',rows=all||!f.filters?.length?(p.departures||[]):f.filters.map(filter=>({...((p.departures||[]).find(r=>matches(r,[filter]))||{missing:true}),filterLabel:filter.label||filter.direction||filter.types||'Filter'}));$('#departures').innerHTML=`<div class="${esc(f.style)}"><div class="board"><div class="departure table-head"><span>Tijd</span><span>Bestemming</span><span>Spoor</span><span>Status</span></div>${rows.length?rows.slice(0,60).map(r=>`${r.filterLabel?`<div class="filter-result-label">${esc(r.filterLabel)}</div>`:''}${r.missing?'<p class="muted filter-empty">Geen passend vertrek gevonden.</p>':`<div class="departure"><span class="time">${esc(r.time)}</span><span class="dest">${esc(r.to)}<small>${esc(r.category)} ${esc(r.number)}</small></span><span>${esc(r.track||'—')}</span>${status(r)}</div>`}`).join(''):'<p class="empty">Geen vertrekken die aan je filters voldoen. Pas je filters aan of probeer het later opnieuw.</p>'}</div></div><p class="source">Bron: ${esc(p.source)}<br>${esc(p.notice)}<br>◷ Alleen planning · ✓ Actueel op tijd · +5 Vijf minuten vertraging<br>Opgehaald om ${new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}</p><button id="refresh">Ververs</button> <a class="button" href="#station/${encodeURIComponent(f.id)}${all?'':'?all=1'}">${all?'Mijn vertrekfilters':'Alle vertrektijden'}</a>`;}catch(e){if(token===renderId)$('#departures').innerHTML=`<p>${esc(e.message)}</p><button id="refresh">Opnieuw proberen</button>`;}return;}
 const pages={tickets:['Voordelig op weg','Treintickets','Bekijk het aanbod en koop je treintickets bij Treinreiziger.','https://tickets.treinreiziger.nl/','Bekijk treintickets','▱'],posities:['Het spoor in beeld','Treinposities','Bekijk waar treinen rijden op de kaart van Treinposities.nl. De kaart opent in een apart venster.','https://treinposities.nl/','Open de treinenkaart','⌖'],internationaal:['Verder dan de grens','Internationaal','Hier komen binnenkort internationale tickets en reisinformatie. Je kunt buitenlandse vertrekborden nu al toevoegen bij Mijn treintijden.',null,null,'◎']};const p=pages[hash];if(!p){location.hash='nieuws';return;}view.innerHTML=header(p[0],p[1],'')+`<section class="card external"><div class="big-symbol" aria-hidden="true">${p[5]}</div><p>${p[2]}</p>${p[3]?`<a class="button primary" href="${p[3]}" target="_blank" rel="noopener">${p[4]} ↗</a>`:'<a class="button primary" href="#tijden">Naar mijn treintijden</a>'}</section>`;
}
function stationOptions(search='',selected=''){
 const query=norm(search.trim());
 const list=catalog.filter(s=>norm(s.name).includes(query)).sort((a,b)=>Number(norm(b.name).startsWith(query))-Number(norm(a.name).startsWith(query))||a.name.localeCompare(b.name,'nl')).slice(0,10);
 const chosen=catalog.find(s=>s.id===selected);
 $('#station').innerHTML='<option value=""></option>'+(chosen?`<option value="${esc(chosen.id)}">${esc(chosen.name)}</option>`:'');$('#station').value=selected||'';
 $('#station-selected').textContent=chosen?'Gekozen: '+chosen.name:'';
 $('#suggestions').innerHTML=chosen?'':list.map(s=>`<button type="button" data-station-choice="${esc(s.id)}">${esc(s.name)}<small>${esc(s.country)}</small></button>`).join('');
 $('#station-search-status').textContent=chosen?'':!catalog.length?'Stations laden…':!list.length?'Geen stations gevonden. Probeer een andere naam.':query?'Kies een station uit de suggesties.':'Begin met typen om een station te zoeken.';
 $('#suggestions').hidden=!!chosen||!query;
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-station-choice]');if(!b)return;const s=catalog.find(s=>s.id===b.dataset.stationChoice);if(s){$('#search').value=s.name;stationOptions(s.name,s.id);$('#style').focus();}});
$('#search').addEventListener('keydown',e=>{if(e.key==='ArrowDown'&&!$('#suggestions').hidden){e.preventDefault();$('#suggestions button')?.focus();}if(e.key==='Enter'){e.preventDefault();if(!$('#suggestions').hidden)$('#suggestions button')?.click();}});
$('#suggestions').addEventListener('keydown',e=>{const buttons=[...$('#suggestions').querySelectorAll('button')],index=buttons.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();buttons[(index+(e.key==='ArrowDown'?1:buttons.length-1))%buttons.length]?.focus();}if(e.key==='Escape'){$('#suggestions').hidden=true;$('#search').focus();}});

function addFilter(f={}){const el=document.createElement('div');el.className='filter';el.innerHTML=`<label>Naam van filter<input data-field="label" maxlength="60" value="${esc(f.label)}" placeholder="Bijvoorbeeld richting Utrecht"></label><label>Richting / tussenstation<input data-field="direction" maxlength="80" value="${esc(f.direction)}" placeholder="Bijvoorbeeld Utrecht"></label><label>Treinsoorten<input data-field="types" maxlength="80" value="${esc(f.types)}" placeholder="Bijvoorbeeld IC, ICE"></label><label>Moet via<input data-field="via" maxlength="80" value="${esc(f.via)}" placeholder="Optioneel"></label><label>Niet via<input data-field="exclude" maxlength="80" value="${esc(f.exclude)}" placeholder="Optioneel"></label><button type="button" class="remove-filter">Verwijder filter</button>`;$('#filters').append(el);}
async function openEditor(id){editing=id||null;const f=favorites.find(f=>f.id===id);$('#edit-title').textContent=f?'Station instellen':'Station toevoegen';$('#style').value=f?.style||'trr';$('#search').disabled=!!f;$('#search').value=f?.name||'';$('#station-search-status').textContent='Stations laden…';$('#station-selected').textContent='';$('#suggestions').innerHTML='';$('#filters').innerHTML='';for(const x of f?.filters||[])addFilter(x);$('#remove-station').hidden=!f;editor.showModal();try{if(!catalog.length)catalog=(await api('stations')).stations;stationOptions($('#search').value,f?.station);$('#station').disabled=!!f;$('#search').disabled=!!f;}catch(e){toast(e.message);}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit)void openEditor(b.dataset.edit);if(['add-station','empty-add'].includes(b.id))void openEditor();if(b.id==='close-editor')editor.close();if(b.id==='add-filter'){if($('#filters').children.length>=8){toast('Je kunt maximaal 8 filters toevoegen.');return;}addFilter();}if(b.classList.contains('remove-filter'))b.closest('.filter').remove();if(b.id==='remove-station'){favorites=favorites.filter(f=>f.id!==editing);save();editor.close();location.hash='tijden';void render();}if(['retry','refresh'].includes(b.id)){cache.clear();void render();}if(b.id==='help')$('#help-dialog').showModal();if(b.id==='close-help')$('#help-dialog').close();});
$('#search').addEventListener('input',e=>stationOptions(e.target.value));
$('#station-form').addEventListener('submit',async e=>{e.preventDefault();const station=catalog.find(s=>s.id===$('#station').value);if(!station){$('#station-search-status').textContent='Kies eerst een station uit de suggesties.';$('#search').focus();return;}const filters=[...$('#filters').children].map(el=>Object.fromEntries([...el.querySelectorAll('[data-field]')].map(i=>[i.dataset.field,i.value.trim()]))).filter(f=>f.direction||f.types||f.via||f.exclude);if(!editing&&favorites.length>=20){toast('Je kunt maximaal 20 stationstegels toevoegen.');return;}const f={id:editing||crypto.randomUUID(),station:station.id,name:station.name,country:station.country,style:$('#style').value,filters};if(editing)favorites=favorites.map(x=>x.id===editing?f:x);else favorites.push(f);const isNew=!editing;save();editor.close();location.hash='tijden';void render();if(isNew)void api('added',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({station:station.id})}).catch(()=>{});});
$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(favorites,null,2)],{type:'application/json'}));a.download='treinreiziger-stations.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file||file.size>100000)throw Error();const a=JSON.parse(await file.text());if(!Array.isArray(a)||a.length>20||a.some(f=>typeof f.station!=='string'||typeof f.name!=='string'||!styles.includes(f.style)||!Array.isArray(f.filters)||f.filters.length>8))throw Error();favorites=a.map(f=>({...f,id:crypto.randomUUID(),filters:f.filters.map(x=>Object.fromEntries(['label','direction','types','via','exclude'].map(k=>[k,String(x[k]||'').slice(0,80)])))}));save();$('#help-dialog').close();location.hash='tijden';void render();}catch{toast('Dit instellingenbestand kon niet worden gelezen.');}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false;});$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true;}};
window.addEventListener('hashchange',()=>{window.scrollTo(0,0);void render();});window.addEventListener('online',()=>{toast('Je bent weer online');void render();});window.addEventListener('offline',()=>toast('Je bent offline. Vertrektijden kunnen verouderd zijn.'));document.addEventListener('visibilitychange',()=>{if(!document.hidden){cache.clear();void render();}});setInterval(()=>{if(!document.hidden&&(location.hash==='#tijden'||location.hash.startsWith('#station/'))){cache.clear();void render();}},60000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('/app/sw.js',{scope:'/app/'}).catch(()=>{});void render();
