const $=s=>document.querySelector(s),view=$('#view'),editor=$('#editor'),key='treinreiziger-stations-v1';
const styles=['trr','db','it','uk','sncf','rustig','compact'];
let favorites=[],catalog=[],cache=new Map(),editing=null,timer,renderId=0,installPrompt;
try{favorites=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(favorites))favorites=[];}catch{}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function save(){try{localStorage.setItem(key,JSON.stringify(favorites));}catch{toast('Opslaan is geblokkeerd. Je instellingen blijven alleen deze sessie beschikbaar.');}}
async function api(path,options){const r=await fetch('/app/api/'+path,{...options,signal:AbortSignal.timeout(75000)});const j=await r.json();if(!r.ok)throw Error(j.error||'Ophalen mislukt');return j;}
function header(k,title,description){return `<div class="eyebrow">${esc(k)}</div><h1>${esc(title)}</h1><p class="intro">${esc(description)}</p>`;}
function status(r){return r.cancelled?'<span class="status cancel" title="Geannuleerd">Uitval</span>':!r.hasRealtime?'<span class="status" title="Alleen dienstregeling, geen actuele meting" aria-label="Alleen dienstregeling">◷</span>':r.delay>0?`<span class="status ${r.delay>=5?'late':''}" aria-label="${esc(r.delay)} minuten vertraging">+${esc(r.delay)}</span>`:'<span class="status ok" aria-label="Actueel: op tijd" title="Actueel: op tijd">✓</span>';}
function matches(r,filters){return !filters?.length||filters.some(f=>{const route=[...(r.route||[]).map(s=>typeof s==='string'?s:s.name||s.station||''),r.to].map(norm);const has=t=>route.some(s=>s.includes(norm(t)));const types=(f.types||'').split(/[,;]/).map(x=>x.trim().toUpperCase()).filter(Boolean);return (!f.direction||has(f.direction))&&(!f.via||has(f.via))&&(!f.exclude||!has(f.exclude))&&(!types.length||types.some(t=>String(r.category||'').toUpperCase()===t));});}
function rowsFor(f,p){return(p.departures||[]).filter(r=>matches(r,f.filters));}
async function board(f){const c=cache.get(f.station);if(c&&Date.now()-c.at<30000)return c.data;const data=await api('board/'+encodeURIComponent(f.station));cache.set(f.station,{at:Date.now(),data});return data;}
async function render(){const token=++renderId,hash=location.hash.slice(1)||'nieuws';document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#'+(hash.startsWith('station/')?'tijden':hash))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 if(hash==='nieuws'){view.innerHTML=header('Altijd onderweg','Het laatste treinnieuws','Nieuws, tips en ontwikkelingen op het spoor.')+'<div id="news-list" class="grid"><p role="status">Nieuws laden…</p></div>';try{const j=await api('news');if(token!==renderId)return;$('#news-list').innerHTML=(j.stale?'<p>De verbinding is tijdelijk onderbroken. Dit is het laatst opgehaalde nieuws.</p>':'')+j.items.map(n=>`<article class="card news"><time>${esc(new Date(n.date).toLocaleDateString('nl-NL',{day:'numeric',month:'long'}))}</time><a href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.title)}</a><p>${esc(n.summary)}</p><a class="read" href="${esc(n.url)}" target="_blank" rel="noopener">Lees op Treinreiziger.nl ↗</a></article>`).join('');}catch(e){if(token===renderId)$('#news-list').innerHTML=`<div class="empty"><p>${esc(e.message)}</p><button id="retry">Probeer opnieuw</button></div>`;}return;}
 if(hash==='tijden'){view.innerHTML='<div class="heading"><div>'+header('Jouw reis begint hier','Mijn treintijden','Je eigen vertrekborden. Je eigen overzicht.')+'</div><button id="add-station" class="primary">+ Station</button></div>'+(favorites.length?'<div class="grid">'+favorites.map(f=>`<article class="card station-card ${esc(f.style)}"><button class="edit" data-edit="${esc(f.id)}" aria-label="Bewerk ${esc(f.name)}">Bewerk</button><a class="station-link" href="#station/${encodeURIComponent(f.id)}"><h2>${esc(f.name)}</h2><span class="tag">${esc(f.country)}</span>${(f.filters||[]).map(x=>`<span class="tag">${esc(x.label||x.direction||x.types||'Filter')}</span>`).join('')}<div data-next="${esc(f.id)}"><p class="muted">Vertrekken laden…</p></div></a></article>`).join('')+'</div>':'<div class="empty"><div class="big-symbol">◷</div><h2>Waar begint jouw reis?</h2><p>Voeg een station toe en zie meteen je eerstvolgende vertrek.</p><button id="empty-add" class="primary">Kies je eerste station</button></div>');for(const f of favorites){try{const p=await board(f);if(token!==renderId)return;const el=[...document.querySelectorAll('[data-next]')].find(x=>x.dataset.next===f.id),r=rowsFor(f,p)[0];if(el)el.innerHTML=r?`<div class="next"><strong>${esc(r.time)}</strong><div>${esc(r.to)}<small>${esc(r.category)} ${esc(r.number)} · spoor ${esc(r.track||'—')} ${status(r)}</small></div></div>`:'<p class="muted">Geen passend vertrek beschikbaar.</p>';}catch(e){if(token!==renderId)return;const el=[...document.querySelectorAll('[data-next]')].find(x=>x.dataset.next===f.id);if(el)el.textContent=e.message;}}return;}
 if(hash.startsWith('station/')){const f=favorites.find(f=>f.id===decodeURIComponent(hash.slice(8)));if(!f){location.hash='tijden';return;}view.innerHTML=`<a class="button" href="#tijden">← Mijn stations</a><div class="heading"><div>${header(f.country,f.name,'Jouw gefilterde vertrekbord')}</div><button data-edit="${esc(f.id)}">Instellingen</button></div><div id="departures"><p role="status">Vertrekken laden…</p></div>`;try{const p=await board(f);if(token!==renderId)return;const rows=rowsFor(f,p);$('#departures').innerHTML=`<div class="${esc(f.style)}"><div class="board"><div class="departure table-head"><span>Tijd</span><span>Bestemming</span><span>Spoor</span><span>Status</span></div>${rows.length?rows.slice(0,60).map(r=>`<div class="departure"><span class="time">${esc(r.time)}</span><span class="dest">${esc(r.to)}<small>${esc(r.category)} ${esc(r.number)}</small></span><span>${esc(r.track||'—')}</span>${status(r)}</div>`).join(''):'<p class="empty">Geen vertrekken die aan je filters voldoen. Pas je filters aan of probeer het later opnieuw.</p>'}</div></div><p class="source">Bron: ${esc(p.source)}<br>${esc(p.notice)}<br>◷ Alleen planning · ✓ Actueel op tijd · +5 Vijf minuten vertraging<br>Opgehaald om ${new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}</p><button id="refresh">Ververs</button>`;}catch(e){if(token===renderId)$('#departures').innerHTML=`<p>${esc(e.message)}</p><button id="refresh">Opnieuw proberen</button>`;}return;}
 const pages={tickets:['Voordelig op weg','Treintickets','Bekijk het aanbod en koop je treintickets bij Treinreiziger.','https://tickets.treinreiziger.nl/','Bekijk treintickets','▱'],posities:['Het spoor in beeld','Treinposities','Bekijk waar treinen rijden op de kaart van Treinposities.nl. De kaart opent in een apart venster.','https://treinposities.nl/','Open de treinenkaart','⌖'],internationaal:['Verder dan de grens','Internationaal','Hier komen binnenkort internationale tickets en reisinformatie. Je kunt buitenlandse vertrekborden nu al toevoegen bij Mijn treintijden.',null,null,'◎']};const p=pages[hash];if(!p){location.hash='nieuws';return;}view.innerHTML=header(p[0],p[1],'')+`<section class="card external"><div class="big-symbol" aria-hidden="true">${p[5]}</div><p>${p[2]}</p>${p[3]?`<a class="button primary" href="${p[3]}" target="_blank" rel="noopener">${p[4]} ↗</a>`:'<a class="button primary" href="#tijden">Naar mijn treintijden</a>'}</section>`;
}
function stationOptions(search='',selected=''){const list=catalog.filter(s=>norm(s.name).includes(norm(search)));$('#station').innerHTML='<option value="">Kies een station</option>'+list.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} · ${esc(s.country)}</option>`).join('');$('#station').value=selected;}
function addFilter(f={}){const el=document.createElement('div');el.className='filter';el.innerHTML=`<label>Naam van filter<input data-field="label" maxlength="60" value="${esc(f.label)}" placeholder="Bijvoorbeeld richting Utrecht"></label><label>Richting / tussenstation<input data-field="direction" maxlength="80" value="${esc(f.direction)}" placeholder="Bijvoorbeeld Utrecht"></label><label>Treinsoorten<input data-field="types" maxlength="80" value="${esc(f.types)}" placeholder="Bijvoorbeeld IC, ICE"></label><label>Moet via<input data-field="via" maxlength="80" value="${esc(f.via)}" placeholder="Optioneel"></label><label>Niet via<input data-field="exclude" maxlength="80" value="${esc(f.exclude)}" placeholder="Optioneel"></label><button type="button" class="remove-filter">Verwijder filter</button>`;$('#filters').append(el);}
async function openEditor(id){editing=id||null;const f=favorites.find(f=>f.id===id);$('#edit-title').textContent=f?'Station instellen':'Station toevoegen';$('#style').value=f?.style||'trr';$('#search').value='';$('#filters').innerHTML='';for(const x of f?.filters||[])addFilter(x);$('#remove-station').hidden=!f;editor.showModal();try{if(!catalog.length)catalog=(await api('stations')).stations;stationOptions('',f?.station);$('#station').disabled=!!f;$('#search').disabled=!!f;}catch(e){toast(e.message);}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit)void openEditor(b.dataset.edit);if(['add-station','empty-add'].includes(b.id))void openEditor();if(b.id==='close-editor')editor.close();if(b.id==='add-filter'){if($('#filters').children.length>=8){toast('Je kunt maximaal 8 filters toevoegen.');return;}addFilter();}if(b.classList.contains('remove-filter'))b.closest('.filter').remove();if(b.id==='remove-station'){favorites=favorites.filter(f=>f.id!==editing);save();editor.close();location.hash='tijden';void render();}if(['retry','refresh'].includes(b.id)){cache.clear();void render();}if(b.id==='help')$('#help-dialog').showModal();if(b.id==='close-help')$('#help-dialog').close();});
$('#search').addEventListener('input',e=>stationOptions(e.target.value));
$('#station-form').addEventListener('submit',async e=>{e.preventDefault();const station=catalog.find(s=>s.id===$('#station').value);if(!station)return;const filters=[...$('#filters').children].map(el=>Object.fromEntries([...el.querySelectorAll('[data-field]')].map(i=>[i.dataset.field,i.value.trim()]))).filter(f=>f.direction||f.types||f.via||f.exclude);if(!editing&&favorites.length>=20){toast('Je kunt maximaal 20 stationstegels toevoegen.');return;}const f={id:editing||crypto.randomUUID(),station:station.id,name:station.name,country:station.country,style:$('#style').value,filters};if(editing)favorites=favorites.map(x=>x.id===editing?f:x);else favorites.push(f);const isNew=!editing;save();editor.close();location.hash='tijden';void render();if(isNew)void api('added',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({station:station.id})}).catch(()=>{});});
$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(favorites,null,2)],{type:'application/json'}));a.download='treinreiziger-stations.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file||file.size>100000)throw Error();const a=JSON.parse(await file.text());if(!Array.isArray(a)||a.length>20||a.some(f=>typeof f.station!=='string'||typeof f.name!=='string'||!styles.includes(f.style)||!Array.isArray(f.filters)||f.filters.length>8))throw Error();favorites=a.map(f=>({...f,id:crypto.randomUUID(),filters:f.filters.map(x=>Object.fromEntries(['label','direction','types','via','exclude'].map(k=>[k,String(x[k]||'').slice(0,80)])))}));save();$('#help-dialog').close();location.hash='tijden';void render();}catch{toast('Dit instellingenbestand kon niet worden gelezen.');}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false;});$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true;}};
window.addEventListener('hashchange',()=>{window.scrollTo(0,0);void render();});window.addEventListener('online',()=>{toast('Je bent weer online');void render();});window.addEventListener('offline',()=>toast('Je bent offline. Vertrektijden kunnen verouderd zijn.'));document.addEventListener('visibilitychange',()=>{if(!document.hidden){cache.clear();void render();}});setInterval(()=>{if(!document.hidden&&(location.hash==='#tijden'||location.hash.startsWith('#station/'))){cache.clear();void render();}},60000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('/app/sw.js',{scope:'/app/'}).catch(()=>{});void render();
