import fs from 'node:fs';import{createHash}from 'node:crypto';import{normalize,shortest,audit}from './core.mjs';
const root=new URL('../',import.meta.url),read=p=>fs.readFileSync(new URL(p,root),'utf8').replace(/^\uFEFF/,'');if(process.argv.includes('--fetch')){fs.mkdirSync(new URL('outputs/',root),{recursive:true});for(const [file,url]of [['trainkms-source.html','https://nanderv.github.io/trainkms/trains.html'],['stationcodes-source.html','https://wiki.ovinnederland.nl/wiki/Lijst_van_verkortingen_van_treinstations']]){const r=await fetch(url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('Bron ophalen mislukt: '+url);fs.writeFileSync(new URL('outputs/'+file,root),await r.text());}}const html=read('outputs/trainkms-source.html'),wiki=read('outputs/stationcodes-source.html'),score=JSON.parse(read('hilta-network.json'));
const decode=s=>s.replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&#0?39;|&#x27;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([a-f0-9]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).trim();
const stations=[...wiki.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/g)].map(m=>[...m[1].matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/g)].map(x=>decode(x[1]))).filter(c=>c.length>=3&&/^[A-Za-z]{1,7}(\/[A-Za-z]{1,7})*$/.test(c[0])&&!/busvervoer/i.test(c[3]||'')).map(c=>({code:c[0].split('/')[0].toLowerCase(),name:c[2],aliases:c[0].split('/').slice(1),validFrom:'',validTo:'',note:c[3]||''}));
const sourceStations=JSON.parse(html.match(/const stationMap\s*=\s*(\{[^\n]+\})/)[1].replace(/\\'/g,"'")),raw=JSON.parse(html.match(/\broutes\s*=\s*(\[[^\n]+\])/)[1]);for(const [code,name]of Object.entries(sourceStations)){const s=stations.find(s=>s.code===code);if(s&&name!==s.name)s.aliases.push(name);}
const aliases={ehv:['Eindhoven'],rtd:['Rotterdam C','Rotterdam CS'],asd:['Amsterdam C','Amsterdam CS'],amf:['Amersfoort'],shl:['Schiphol Airport'],gv:['Den Haag Hollands Spoor'],bdpb:['Breda Prinsenbeek'],apn:['Alphen aan den Rijn'],laa:['Den Haag Laan van NOI']};for(const s of stations)s.aliases=[...new Set([...s.aliases,...(aliases[s.code]||[])])];
const find=name=>stations.find(s=>[s.name,s.code,...s.aliases].some(v=>normalize(v)===normalize(name)))?.code;
const codeMap=new Map(Object.entries(sourceStations).map(([code,name])=>[code,stations.find(s=>s.code===code)?.code||find(name)||code]));
const edges=[...new Map(raw.map(e=>{const from=codeMap.get(e.fromStation)||e.fromStation,to=codeMap.get(e.toStation)||e.toStation,id=[from,to].sort().join(':');return [id,{id,from,to,metres:Math.round(e.distance*100)}]})).values()];
const endpoints=new Set(score.edges.flatMap(e=>[find(e.from),find(e.to)]).filter(Boolean));const trajectories=score.edges.map(e=>{const from=find(e.from),to=find(e.to),hsl=e.label.includes('HSL');let path=[],problem='';try{if(!from||!to)throw Error('Stationsnaam koppelen');if(hsl)path=[{from,to,metres:Math.round(e.km*1000)}];else{let full;try{full=shortest(edges,from,to,endpoints);}catch{full=shortest(edges,from,to);problem='Controleer doorkruist scorekaartknooppunt';}let begin=from,metres=0;for(const step of full){metres+=step.metres;if(stations.some(s=>s.code===step.to)){path.push({from:begin,to:step.to,metres});begin=step.to;metres=0;}}}}catch(err){problem=err.message;}return {id:e.id,label:e.label,points:path.length?[path[0].from,...path.map(e=>e.to)]:[from,to].filter(Boolean),parts:path.map(e=>e.metres),scoreMetres:Math.round(e.km*1000),maxCount:e.maxCount,hsl,review:'pending',problem,source:hsl?'Scorekaart 2026':'Trainkms',validFrom:'',validTo:''};});
const net={schema:1,revision:'seed-2026-09-21',name:'Volgende editie · concept',sources:[{url:'https://nanderv.github.io/trainkms/trains.html',sha256:createHash('sha256').update(html).digest('hex')},{url:'https://wiki.ovinnederland.nl/wiki/Lijst_van_verkortingen_van_treinstations',sha256:createHash('sha256').update(wiki).digest('hex')},{url:score.source,sha256:score.sha256}],importedAt:new Date().toISOString(),stations,trajectories,rules:[{id:'hsl-noord',from:'hfd',to:'rtd',label:'Hoe reisde je tussen Schiphol / Hoofddorp en Rotterdam?',defaultLabel:'Via HSL (kortste route)',options:[{id:'leiden',label:'Via Leiden Centraal',via:['ledn']}],enabled:true},{id:'hsl-zuid',from:'rlb',to:'bdpb',label:'Hoe reisde je tussen Rotterdam en Breda?',defaultLabel:'Via HSL (kortste route)',options:[{id:'dordrecht',label:'Via Dordrecht en Lage Zwaluwe',via:['ddr','zlw']}],enabled:true}]};net.revision='import-'+createHash('sha256').update(JSON.stringify({stations,trajectories,rules:net.rules})).digest('hex').slice(0,16);fs.writeFileSync(new URL('seed.json',import.meta.url),JSON.stringify(net,null,2));console.log(JSON.stringify({stations:stations.length,trajectories:trajectories.length,missing:trajectories.filter(t=>t.problem),issues:audit(net).filter(s=>!s.endsWith('nog niet gecontroleerd'))},null,2));
