import {readFileSync} from 'node:fs';import{randomUUID}from 'node:crypto';import{kkGet,kkPut,kkList,kkComparePut}from '../kk-store.mjs';import{resolve,audit,calculate,graph,routeVia,normalize}from './core.mjs';
const seed=JSON.parse(readFileSync(new URL('./seed.json',import.meta.url),'utf8').replace(/^\uFEFF/,''));const fail=m=>{throw Object.assign(Error(m),{status:400});};
export async function getNetwork(revision){if(revision&&revision!==seed.revision){const saved=await kkGet('hilta-next-version',revision);if(!saved)fail('Versie niet gevonden.');return saved.value;}if(revision===seed.revision)return structuredClone(seed);return (await kkGet('hilta-next','draft'))?.value||structuredClone(seed);}
export async function networkView(revision){const net=await getNetwork(revision);return {network:net,issues:audit(net),history:[{revision:seed.revision,name:seed.name},...(await kkList('hilta-next-version')).filter(r=>r.id!==seed.revision).map(r=>({revision:r.id,name:r.value.name,at:r.value.updatedAt,frozen:r.value.frozen}))]};}
const text=(v,max=200)=>String(v||'').trim().slice(0,max);function dates(row){for(const k of ['validFrom','validTo'])if(row[k]&&(!/^\d{4}-\d{2}-\d{2}$/.test(row[k])||!Number.isFinite(Date.parse(row[k]))||new Date(row[k]).toISOString().slice(0,10)!==row[k]))fail('Ongeldige geldigheidsdatum.');if(row.validFrom&&row.validTo&&row.validFrom>row.validTo)fail('Einddatum ligt vóór begindatum.');}
export async function saveNetwork(data){const stored=await kkGet('hilta-next','draft'),net=structuredClone(stored?.value||seed);if(data.revision!==net.revision)fail('De netwerkversie is gewijzigd. Vernieuw eerst om wijzigingen van een ander niet te overschrijven.');const expected=stored?JSON.stringify(stored.value):null;
 if(data.action==='station'){const code=text(data.code).toLowerCase();if(!/^[a-z0-9]{1,12}$/.test(code))fail('Gebruik een stationscode met letters en cijfers.');const station={code,name:text(data.name),aliases:[...new Set((Array.isArray(data.aliases)?data.aliases:[]).map(v=>text(v)).filter(Boolean))],validFrom:text(data.validFrom),validTo:text(data.validTo),note:text(data.note,1000)};if(!station.name||station.aliases.length>30)fail('Vul een stationsnaam in (maximaal 30 synoniemen).');dates(station);for(const other of net.stations.filter(s=>s.code!==code))if([station.code,station.name,...station.aliases].some(a=>[other.code,other.name,...other.aliases].some(b=>normalize(a)===normalize(b))))fail('Een naam of synoniem hoort al bij '+other.name);const index=net.stations.findIndex(s=>s.code===code);if(index<0)net.stations.push(station);else net.stations[index]=station;
 }else if(data.action==='trajectory'){const t=net.trajectories.find(t=>t.id===data.id);if(!t)fail('Traject niet gevonden.');if(!Array.isArray(data.points)||!Array.isArray(data.parts)||data.points.length<2||data.points.length>100||data.parts.length!==data.points.length-1)fail('Vul stations en de afstand tussen opeenvolgende stations in.');const points=data.points.map(p=>resolve(net,p)),parts=data.parts.map(Number);if(new Set(points).size!==points.length)fail('Een lijn mag niet hetzelfde station herhalen.');if(parts.some(n=>!Number.isSafeInteger(n)||n<=0))fail('Afstanden moeten positieve gehele meters zijn.');if(t.hsl&&points.length!==2)fail('De HSL heeft geen tussenstations.');Object.assign(t,{points,parts,scoreMetres:Number(data.scoreMetres),review:data.review==='checked'?'checked':'pending',problem:'',junctionNote:text(data.junctionNote,1000),validFrom:text(data.validFrom),validTo:text(data.validTo)});if(!Number.isSafeInteger(t.scoreMetres)||t.scoreMetres<=0)fail('Ongeldige totale scorekaartafstand.');dates(t);
 }else if(data.action==='rule'){const rule={id:data.id||randomUUID(),from:resolve(net,data.from),to:resolve(net,data.to),label:text(data.label),defaultLabel:text(data.defaultLabel)||'Kortste route',enabled:data.enabled!==false,options:(data.options||[]).map((o,i)=>({id:'option-'+i,label:text(o.label),via:(o.via||[]).map(s=>resolve(net,s))}))};if(!rule.label||rule.from===rule.to||rule.options.length<1||rule.options.length>8||rule.options.some(o=>!o.label||!o.via.length||o.via.length>10))fail('Vul een vraag en minimaal één alternatief met via-station in.');const ends=new Set(net.trajectories.flatMap(t=>[t.points[0],t.points.at(-1)]));if(!ends.has(rule.from)||!ends.has(rule.to))fail('Kies twee begin- of eindstations van de scorekaart.');const edges=graph(net),trigger=routeVia(edges,[rule.from,rule.to]);for(const o of rule.options)routeVia(edges,[rule.from,...o.via,rule.to],new Set(trigger.map(e=>e.id)));const i=net.rules.findIndex(r=>r.id===rule.id);if(i<0)net.rules.push(rule);else net.rules[i]=rule;
 }else if(data.action==='freeze'){if(audit(net).length)fail('Los eerst alle controlepunten op en markeer alle trajecten als gecontroleerd.');net.name=text(data.name);if(!net.name)fail('Geef de editie een naam.');net.frozen=true;
 }else fail('Onbekende wijziging.');if(data.action!=='freeze')net.frozen=false;if(!stored)await kkPut('hilta-next-version',seed.revision,'hilta-next',seed);net.parentRevision=net.revision;net.revision=randomUUID();net.updatedAt=Date.now();await kkPut('hilta-next-version',net.revision,'hilta-next',net);if(!await kkComparePut('hilta-next','draft',net,expected))fail('Een ander heeft intussen opgeslagen. Vernieuw eerst.');return networkView();}
export async function testNetwork(data){const net=await getNetwork(data.revision);if(!Array.isArray(data.via||[])||(data.via||[]).length>20)fail('Maximaal 20 via-stations.');try{return calculate(net,data);}catch(e){fail(e.message);}}
